### ISSUE TITLE
Demo for EventTarget does not work : Assertion failed

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#1]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=639

**Comment by joeltine** [comment]
Bug was in reference to old demos page. I tested the new event target demo, and it works.

(Beware alert spam)
http://closure-library.googlecode.com/git-history/0148f7ecaa1be5b645fabe7338b9579ed2f951c8/closure/goog/demos/index.html
