### ISSUE TITLE
goog.DebugLoader hits Chrome request pool limit

### ISSUE THREAD

**Issue by wallw-bits** [google/closure-library#1004]
Chrome (at least according to our developer who did most of the digging on this) has a 25MB limit for its outstanding request pool. `goog.DebugLoader` does not throttle the number of dependencies that can be loaded at once, resulting in hitting that limit and causing underlying network errors which cause the page to hang.

We are only seeing this behavior in Chrome on Linux (RHEL7) and have not been able to recreate in OS X (not sure about Windows yet).

We were previously using [our own script loader](https://github.com/ngageoint/opensphere-build-index/blob/v2.2.2/debug-loader.js) to get around this, but decided to switch back to Closure's for `goog.module` and ES6 module support.

For reference, our dependency file generated by `depswriter.py` lists 3,642 files in our largest application.

As a quick fix, I made this "small" change to `base.js` and that appears to fix the issue:
```
diff --git a/closure/goog/base.js b/closure/goog/base.js
index 5aa208ee0..c2c970d92 100644
--- a/closure/goog/base.js
+++ b/closure/goog/base.js
@@ -2795,6 +2795,8 @@ if (!COMPILED && goog.DEPENDENCIES_ENABLED) {
     this.deferredCallbacks_ = {};
     /** @private @const {!Array<string>} */
     this.deferredQueue_ = [];
+    /** @private @const {number} */
+    this.maxLoading_ = 500;
   };

   /**
@@ -3037,6 +3039,9 @@ if (!COMPILED && goog.DEPENDENCIES_ENABLED) {

         try {
           dep.load(controller);
+          if (loader.loadingDeps_.length >= loader.maxLoading_) {
+            pause = true;
+          }
         } finally {
           loadCallDone = true;
         }
@@ -3111,6 +3116,10 @@ if (!COMPILED && goog.DEPENDENCIES_ENABLED) {
     }

     dep.loaded();
+
+    if (this.paused_ && this.loadingDeps_.length < this.maxLoading_) {
+      this.resume_();
+    }
   };
```
That may not be the best way to go about it, but perhaps I could get a PR going with a more correct solution given some better direction.

**Comment by kjin** [comment]
Internal issue created: b/146354711

**Comment by shicks** [comment]
In general we don't recommend using the debug loader - especially not for large projects.  You'll likely have much better luck with some sort of bundler.

That said, if you want to put together a PR for this, it looks like it should be fine, except I'd prefer to see the limit configurable via a goog.define (maybe goog.DebugLoader.MAX_PARALLELISM).

**Comment by shicks** [comment]
I'm closing this as inactive, since it's not aligned with our intended usage.
