### ISSUE TITLE
goog.result.combine throws "Multiple attempts to set the state of this Result" when all results have already benn resolved.

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#102]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=495

**Comment by joeltine** [comment]
fixed in https://github.com/google/closure-library/commit/2e7eb4561a49d20205f656031906448221a1c794
