### ISSUE TITLE
Google closure few functions not supporting Jquery3.4 version

### ISSUE THREAD

**Issue by kavi93** [google/closure-library#1027]
While using JQUERY 1.7 version google-closure works fine, But updating Jquery version to 3.4 some google closure functions failed(i.e i18n,date..).
Can anyone help to come out of this issue?

**Comment by shicks** [comment]
You'll need to post some more details than that to get any useful help.  For instance, what are you doing (how are you putting them together, what are you trying to do with them)?  What do you expect to happen and what is actually happening (i.e. specific error messages)?

These libraries are completely separate so there should be absolutely no effect here.
