### ISSUE TITLE
caught JSC_TYPE_MISMATCH error

### ISSUE THREAD

**Issue by pirosikick** [google/closure-library#1043]
JSC_TYPE_MISMATCH error has occured when I updated closure-compiler from v20180910.1.0 to v20200112.0.0 and updated closure-library from v20180405.0.0 to v20190325.0.0.

The error message is the below:

```
actual parameter 2 of goog.events.EventHandler.prototype.listen does not match formal parameter
found   : goog.fx.DragListGroup.EventType<goog.events.EventId<goog.fx.DragListGroupEvent>>
required: (Array<?>|goog.events.EventId<(goog.fx.DragListGroupEvent|null)>|null|string)

    eh.listen(this.dragListGroup_, goog.fx.DragListGroup.EventType.DRAGSTART, this.handleDragStart_);
```

How can I resolve this error?

**Comment by shicks** [comment]
Is there a reason you're mixing different library and compiler versions?  In general the idea is that the library and compiler are known to work together if the version numbers are the same.  Otherwise, there may be errors.

**Comment by shicks** [comment]
I'm closing this under the assumption that it's something about the mismatched library and compiler.  If you can repro this on a matched version, please reopen and give details.
