### ISSUE TITLE
Updating jQuery 1.7 to jQuery 3.4.1 getting error

### ISSUE THREAD

**Issue by kavi93** [google/closure-library#1059]
Updating jquery version from 1.7 to  3.4.1.
While running the application  in chrome browser getting below error.

TypeError: 'undefined' is not a function (evaluating 'e.getAttribute("type")')

/js/jquery.js:2 in Pe
/jquery.js:2
/jquery.js:2 in Ie
CURRENT VERSION :Jquery-3.4.1.js

**Comment by shicks** [comment]
This issue tracker is for Closure Library, but your bug report indicates only JQuery and Chrome, neither of which we manage.  You'll need to provide some more information (a) about how this relates to Closure Library, and (b) with more thorough reproduction instructions - as it is, there's nothing I can do with this.  If you can reduce your problem to a minimal example (smallest possible self-contained HTML/JS that still demonstrates the error) then we'll have something to work with.  Until then, I'm closing this issue, but feel free to reopen if you can provide more information.
