### ISSUE TITLE
Cleanup of goog.labs

### ISSUE THREAD

**Issue by ghost** [google/closure-library#1062]
This namespace was used for newer APIs in the past and contains similar/duplicate APIs.

A cleanup of the APIs in this namespace is in order.

This issue can possibly be divided into sub-issues to tackle each of the APIs present in goog.labs piecemeal.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
