### ISSUE TITLE
Scrub http://go/xxx links from source or make them publicly available

### ISSUE THREAD

**Issue by ghost** [google/closure-library#1065]
There are many references to design docs of the form: 'http://go/xxx' which are not public.

These URLs should be scrubbed or otherwise made publicly available.

**Comment by apap04** [comment]
is it ok if I make a large PR with removal of all (or most) internal links?

**Comment by shicks** [comment]
Simply deleting these will not work - we want to keep the internal links internally, so we need to add proper scrubbing directives to them.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
