### ISSUE TITLE
Demo for split behavior does not exist.

### ISSUE THREAD

**Issue by apap04** [google/closure-library#1066]
slider behavior demo page doesn't exist.

**Comment by shicks** [comment]
Can you clarify what you expect?  Generally goog.ui is considered mostly deprecated and we don't really maintain it very thoroughly.  Feel free to send a PR with a demo if you'd like.

**Comment by apap04** [comment]
I'd expect to see a demo on split behaviors on the demos site, but instead I get a [404](https://google.github.io/closure-library/source/closure/goog/demos/splitbehavior.html).
