### ISSUE TITLE
Bundle size increase between 20200112 and 20200204?

### ISSUE THREAD

**Issue by hsubox76** [google/closure-library#1070]
We were updating some old dependencies and there is a file we were compiling: https://github.com/firebase/firebase-js-sdk/blob/master/packages/webchannel-wrapper/src/index.js

The config setup is (gulpfile):
https://github.com/firebase/firebase-js-sdk/pull/2891/files#diff-0b25b73a3929ed79cc5a86c3ccca9318

Looking at just the CJS build, which doesn't go through rollup but only closure-compiler, there is a ~5.5K increase in bundle size when we upgrade from closure-library version 20200112 to 20200204 (which has been reduced to about a 2.5K increase in the latest version, 20200406). The `closure-compiler` version doesn't seem to affect this very much. It increases the size from about 41K to about 47K.

I was just wondering if anyone knows offhand what change may have caused this increase and if there's anything we can/should do about it on our end? I guess one of the `require`s in that file went up in size?

**Comment by shicks** [comment]
After looking at a diff sent privately, it looks like a change somewhere caused the usage of Set in labs/net/webchannel/forwardchannelrequestpool.js to no longer be stripped.  We could investigate further to see what change exactly and if it's intended.

**Comment by shicks** [comment]
Given that we've found the source of the increase, I'm going to close this.  Feel free to reopen if there's more work we can do to remove the polyfill here.

**Comment by schmidt-sebastian** [comment]
This is now increasing the size of our Firebase libraries. Do we intend to fix this, now that we know the underlying cause?
