### ISSUE TITLE
Keyboard event lookup fails for Escape key

### ISSUE THREAD

**Issue by drstonebraker** [google/closure-library#1072]
When registering a shortcut with goog.ui.KeyboardShortcutHandler for the escape key with a key name, one must use 'esc' instead of 'escape', [since the  goog.events.KeyNames does not have 'escape'](https://github.com/google/closure-library/blob/38798113b27eb925f88814ba6a8913cf6232fe80/closure/goog/ui/keyboardshortcuthandler.js#L667). However, the real key name used by most modern browsers (exception being IE and Edge) for the escape key is "Escape" (per spec). So when a shortcut is registered and the escape key is pressed in a newer browser, the lookup for a registered key named "Escape" fails, and it instead falls back to using the keyCode. 

This is a problem since keyCode is deprecated and some testing libraries expect to be able to create KeyboardEvent objects using the spec'ed name for this key: 'Escape'

**Comment by shicks** [comment]
Do you see a reasonable way to support both?  What do you propose to fix this?

**Comment by drstonebraker** [comment]
Unfortunately I don't

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
