### ISSUE TITLE
Closure library has CORS errors when running in filesystem mode

### ISSUE THREAD

**Issue by joswhite** [google/closure-library#1074]
**Error:**
When running my Closure library application from the filesystem, I get the following 3 errors in my Firefox 76.0.1 browser console (similar errors occur in Chrome):
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote
resource at file:///C:/my-project/node_modules/google-closure-library/closure
/goog/math/long.js. (Reason: CORS request not http).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote
resource at file:///C:/my-project/node_modules/google-closure-library/closure
/goog/ui/map.js. (Reason: CORS request not http).

TypeError: parentCtor is undefined
```
These 3 errors occur even in the simplest example of loading the Closure library. I installed the latest version of the Closure library (20200504.0.0) and then opened up the following HTML file on the filesystem in my web browser, and I got the same errors:
```html
<!DOCTYPE html>
<html>
<head>
  <script src="./node_modules/google-closure-library/closure/goog/base.js">
  </script>
</head>
</html>
````

**Cause:**
In investigating the problem I noticed the first two errors originate from the `goog.GoogModuleDependency` class when it tries to load a `goog.module` using a synchronous XHR request in closure/goog/base.js line 1225:
```js
var xhr = new goog.global['XMLHttpRequest']();
xhr.open('get', src, false);
xhr.send();
```

The third error occurs in closure/goog/base.js line 2080 after `goog.ui.Dialog.ButtonSet` tries to call `goog.inherits` to inherit from `goog.ui.Map`, which of course throws an error since `goog.ui.Map` didn't load properly.

According to my testing, the first error was introduced in version 20190909.0.0 of the Closure library by commit [15143e1](https://github.com/google/closure-library/commit/15143e1), which converted `goog.math.Long` to a `goog.module` and the other two errors were introduced in version 20191111.0.0 of the Closure library by commit [e90df7a](https://github.com/google/closure-library/commit/e90df7a), which added `goog.ui.Map` as a `goog.module`.

**Resolution:**
Does the Closure library have any plans to load `goog.module`s properly without using the synchronous XHR requests that are blocked in modern browsers? Is it possible to load these modules using a dynamically generated `<script>` tag, just like we load the rest of the Closure library?

**Comment by shicks** [comment]
It may be possible - if you want to look into it, please feel free to.  In general, we're moving away from this style of debug loading, now that ES modules are gaining better support.  Moreover, loading directly from file: URLs is generally problematic in my experience - can you use a simple HTTP server (e.g. `npm install -g http-server`) and then use http://localhost for testing?

Given that the http-server should be a workaround, I'm going to close this.  If you want to look into fixing the debug loader, feel free to reopen it to track that investigation.

**Comment by joswhite** [comment]
Ok thank you for the heads up
