### ISSUE TITLE
ctrl+click MouseEvent.button change in Firefox

### ISSUE THREAD

**Issue by ksy36** [google/closure-library#1075]
Gecko recently landed https://bugzilla.mozilla.org/show_bug.cgi?id=1615732, which makes it so ctrl+click is no longer reported as right click on Mac (`MouseEvent.button=0` as opposed to `MouseEvent.button=2` before).

The behavior is put behind `dom.event.treat_ctrl_click_as_right_click.disabled` preference and only enabled in Firefox Nightly.

Since then we got a report about a problem with a context menu in Google Sheets where a context menu opened with ctrl+click opens and closes immediately, making it unusable (https://bugzilla.mozilla.org/show_bug.cgi?id=1638872).

This problem is not reproducible in Chrome despite the fact that ctrl+click is reported the same way as in Nightly (`MouseEvent.button=0`). So we tracked it down to this function where the event is handled differently based on UA detection:

https://github.com/google/closure-library/blob/719529feafc9d60eecd2f620756d3e5cc84a9250/closure/goog/events/browserevent.js#L379-L392

Since Gecko will be reporting ctrl+click the same way as in Chrome, would it be possible to change the above condition to handle it similarly?

**Comment by ksy36** [comment]
This is the STR for the Google Sheets issue:
    1. Open a google sheet document in https://docs.google.com/spreadsheets/
    2. press and hold control + mouse left button.
    3. Wait for the menu to show up.
    4. Move mouse left a bit to make it is not over the menu.
    5. The menu will be closed as soon as I release the mouse button.

**Comment by shicks** [comment]
My understanding here is that there should never be a situation in which we treat Ctrl+Button0 as anything but a right click on a Mac, regardless of user agent.  So the easy fix should be to just drop the WEBKIT check.

Unfortunately, this house of cards will collapse in a few months when userAgent deprecation makes the platform check no longer accessible synchronously.  So we'll need to figure out what to do with that.
