### ISSUE TITLE
goog.net.WebSocket.EventType.CLOSED does not include any information from the underlying ClosedEvent

### ISSUE THREAD

**Issue by drewkutilek** [google/closure-library#1078]
`goog.net.WebSocket.CLOSED` is triggered as an event without any payload. The underlying `ClosedEvent` has useful information about why the WebSocket was closed, including `code` and `reason`.

https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

Including a `goog.net.WebSocket.ClosedEvent` to wrap that data would be useful, especially if the server specific implementation relies on the `code` and `reason` to notify the user of a specific error and display a message.

```
/**
 * Object representing a closed event.
 *
 * @param {number} code
 * @param {string} reason
 * @param {boolean} wasClean
 * @extends {goog.events.Event}
 * @constructor
 * @final
 */
goog.net.WebSocket.ClosedEvent = function(code, reason, wasClean) {
  goog.net.WebSocket.ClosedEvent.base(
      this, 'constructor', goog.net.WebSocket.EventType.CLOSED);

  /**
   * @type {number}
   */
  this.code = code;

  /**
   * @type {string}
   */
  this.reason = reason;

  /**
   * @type {boolean}
   */
  this.wasClean = wasClean;
};
goog.inherits(goog.net.WebSocket.ClosedEvent, goog.events.Event);
```

And dispatching the event in `onClose_` like this:

```
/**
 * Called when the web socket has closed.
 *
 * @param {!Event} event The close event.
 * @private
 */
goog.net.WebSocket.prototype.onClose_ = function(event) {
  goog.log.info(this.logger_, 'The WebSocket on ' + this.url_ + ' closed.');

  // Firing this event allows handlers to query the URL.
-  this.dispatchEvent(goog.net.WebSocket.EventType.CLOSED);
+ this.dispatchEvent(new goog.net.WebSocket.ClosedEvent(event.code, event.reason, event.wasClean));

  // Always clear out the web socket on a close event.
  this.webSocket_ = null;

  // See if this is an expected call to onClose_.
  if (this.closeExpected_) {
    goog.log.info(this.logger_, 'The WebSocket closed normally.');
    // Only clear out the URL if this is a normal close.
    this.url_ = null;
    this.protocol_ = undefined;
  } else {
    // Unexpected, so try to reconnect.
    goog.log.error(
        this.logger_, 'The WebSocket disconnected unexpectedly: ' + event.data);

    // Only try to reconnect if it is enabled.
    if (this.autoReconnect_) {
      // Log the reconnect attempt.
      var seconds = Math.floor(this.nextReconnect_ / 1000);
      goog.log.info(
          this.logger_, 'Seconds until next reconnect attempt: ' + seconds);

      // Actually schedule the timer.
      this.reconnectTimer_ = goog.Timer.callOnce(
          goog.bind(this.open, this, this.url_, this.protocol_),
          this.nextReconnect_, this);

      // Set the next reconnect interval.
      this.reconnectAttempt_++;
      this.nextReconnect_ = this.getNextReconnect_(this.reconnectAttempt_);
    }
  }
  this.closeExpected_ = false;
};
```

This should remain backwards compatible, as anyone listening to `goog.net.WebSocket.EventType.CLOSED` as an event does not expect any event object

**Comment by kjin** [comment]
This looks good! Can you send a PR?

**Comment by drewkutilek** [comment]
@kjin Working through the contributor agreement with my employer's (The Walt Disney Company) Open Source Committee. If I'm being honest, that process will likely not move quickly. I will post a PR once the committee has approved it.

**Comment by kjin** [comment]
Sounds good, thanks for the update! We'll be looking forward to your PR.

**Comment by kjin** [comment]
Hi @drewkutilek, any update on the CLA situation? Thanks!

**Comment by drewkutilek** [comment]
Hi @kjin, working on the final approvals. I will put up a PR as soon as I can.

**Comment by kjin** [comment]
Hi @drewkutilek, just checking in -- any new updates on the CLA situation? Thanks!

**Comment by drewkutilek** [comment]
Hi @kjin, unfortunately it is taking quite some time to allow the different legal entities and representatives within The Walt Disney Company to come to a consensus. I have not forgotten about this! I will let you know as soon as I am able to submit a PR.

**Comment by kjin** [comment]
Ok, sure thing! We'll be checking back from time to time as well.

**Comment by kjin** [comment]
Hi @drewkutilek, we're going to stop monitoring changes to this issue internally, so please open a PR when you are ready. Thank you!

**Comment by drewkutilek** [comment]
Hi @kjin, the CLA should have been submitted and signed today! I have opened a PR:

https://github.com/google/closure-library/pull/1119

**Comment by kjin** [comment]
Great! Will take a look shortly 👍

**Comment by kjin** [comment]
Since #1119 was merged, I am closing this now!
