### ISSUE TITLE
What happen?

### ISSUE THREAD

**Issue by crouse12** [google/closure-library#1081]
When I compile old pxt-blockly by python build.py recently, it always show the following messages.

Required namespace "goog.event.EventWrapper" never defined. 
??? at line 55: 
goog.requireType('goog.events.EventWrapper');
^

I never see this error when I compiled it before.
Is it some errors on closure-library?

pxt-blockly github:
https://github.com/microsoft/pxt-blockly/tree/master

**Comment by 12wrigja** [comment]
We are going to need a lot more information to help you, including the full output of this error.

That particular error implies to me that the file containing EventWrapper ([eventwrapper.js](https://github.com/google/closure-library/blob/803aa52f65e59ee354ad40f89f18b5d847523f73/closure/goog/events/eventwrapper.js)) was never included in your build

**Comment by crouse12** [comment]
Your blockly has the same error:
Download:
https://github.com/google/blockly/releases/tag/2.20190722.1
Video
https://www.youtube.com/watch?v=zYGCjoZzLtU&feature=youtu.be

**Comment by 12wrigja** [comment]
From the video, it looks like the Blockly build doesn't provide all the right Closure Library files in order for the compiler (which seems to be the [Closure Compiler version hosted on Appspot](https://github.com/google/blockly/blob/ba68081d8f0f8e81d76baf370716d5955bae82a1/build.py#L290)) to compile successfully. 

I'm going to try moving this issue to the Blockly repository, although I wouldn't be surprised if their response is to update to a newer release. The fact they don't pin to a particular version of Closure Library / Compiler (as evidenced by using the hosted compiler) means they should be frequently updating to the latest library release to stay in sync.

**Comment by 12wrigja** [comment]
Update: I can't seem to transfer it there, so I suggest you open this issue there.
