### ISSUE TITLE
Add support for cldr RBNF

### ISSUE THREAD

**Issue by ribrdb** [google/closure-library#1082]
It would be great if goog.i18n supported rules based number formatting for spelling out numbers.

**Comment by 12wrigja** [comment]
To clarify, you mean a hypothetical

```
goog.i18n.formatAsNumbers(500); // "Five hundred" in English, or "quinientos" in Spanish
```

I think this would be a use-case best supported by the [Intl NumberFormat API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) (though it doesn't support it now as far as I can tell).

**Comment by ribrdb** [comment]
Something like that.
An analogue of the ICU RuleBasedNumberFormatter. I posted it here mainly because CLDR has data for doing this type of formatting, and they list Closure Library as one of the frameworks you should use to access CLDR data.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
