### ISSUE TITLE
IE 11 Support Removal

### ISSUE THREAD

**Issue by max19931** [google/closure-library#1086]
In October 2020 Microsoft stops the support under win 7 for IE11 and later on for more current versions, it will be best to update the source code to counter this change since other Frameworks stopped supporting IE11 awhile back.

**Comment by max19931** [comment]
IE specific code can be deleted to force users to update to "modern" Browsers

**Comment by shicks** [comment]
As much as I would love to stop supporting IE11 and force users to update, our internal customers (particularly web search) have very stringent support needs and are generally pretty averse to being the forcing function for people to upgrade their browser.  So it's a non-starter for Closure to take on this role.  We do have internal issues tracking support requirements for legacy browsers, and we do push on them from time to time, and remove support once all stakeholders agree.  But right now the discussion is over IE9, not IE11.

**Comment by max19931** [comment]
good to know!!!

IE9 is not supported since March 31, 2017, but a Seperation for IE support can make code support more easily, clients with modern code can strip IE specific code while IE users get dedicated code for them!!
