### ISSUE TITLE
Direct Object use VS document.getElementById

### ISSUE THREAD

**Issue by max19931** [google/closure-library#1087]
document.getElementById needs to be assigned to a variable.

Modern Browsers automaticily create a Object for every Id used on the Webpage!!

Source code can be cleaned up to directly use Id references on the page, without declaring a variable for the element!!

**Comment by max19931** [comment]
https://github.com/google/closure-library/blob/af616efff1792388f413cdafde4a706d6362a1da/closure/goog/style/bidi_test.js#L18

**Comment by 12wrigja** [comment]
I've never seen this behavior - can you find some documentation on it?

These tests are running on our internal CI on a variety of browsers and seem to pass just fine...

**Comment by shicks** [comment]
Are you saying we should assign these global variables since the browser doesn't do it automatically?  Browsers stopped doing this for a reason - global variables are not good practice.  Closure does not (and will not) use these variables.  Have I misunderstood what you're reporting?

**Comment by max19931** [comment]
Modern Browser let a IDed Element directory used in js Code without the need to assign a varible

**Comment by max19931** [comment]
the Issue Text was wrong, i corrected it. Browser let a dev use the id directly as an Object in js without the need to search the Dom and assign it a varible

**Comment by max19931** [comment]
I'm from Germany with a german keyboard, so my autocorrect will mess up the text

**Comment by max19931** [comment]
<p class="codepen" data-height="265" data-theme-id="light" data-default-tab="html,result" data-user="maximilian" data-slug-hash="rNePpGj" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="rNePpGj">
  <span>See the Pen <a href="https://codepen.io/maximilian/pen/rNePpGj">
  rNePpGj</a> by maximilian nasarewski (<a href="https://codepen.io/maximilian">@maximilian</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by max19931** [comment]
I was seeing it in a tutorial and was shocked because it mean i can basicly clean up a ton of code(remove document.getElementByID and all shorthands I used before)

**Comment by max19931** [comment]
SPEC: https://html.spec.whatwg.org/multipage/window-object.html#named-access-on-the-window-object

**Comment by max19931** [comment]
most people who talk about it(mozilla due to FF quirk mode) reference to http://www.whatwg.org/specs/web-apps/current-work/multipage/browsers.html#dom-window-nameditem

**Comment by shicks** [comment]
It's not clear to me that it's good practice to use this, even if it _is_ standardized.  In particular, the fact that window.foo will be either an element or an HTMLCollection (depending on if somebody else added an extra element named 'foo' somewhere) if pretty bad.  Our view therefore is that folks should avoid taking advantage of this, and we should neither promote it in documentation nor use it ourselves.

**Comment by max19931** [comment]
Ok, good to know
