### ISSUE TITLE
google-closure-deps npm package is incompatible with the latest google-closure-compiler npm package

### ISSUE THREAD

**Issue by banguit** [google/closure-library#1096]
Hi closure team,

I just tried to switch from legacy `depswriter.py` to [`google-closure-deps`](https://www.npmjs.com/package/google-closure-deps) and notice that the latest npm version is not compatible to the latest `google-closure-compiler` version due to the following changes [`In closure-deps, check in compiled jsfile_parser.js rather than depend on google-closure-compiler`](https://github.com/google/closure-library/commit/88f3857a26ec5ead36b4b49cb6c3f011cc534971). What is release cycle for [`google-closure-deps`](https://www.npmjs.com/package/google-closure-deps) npm package?

Best regards,
Dima

**Comment by kjin** [comment]
Hi @banguit, we should be releasing it whenever Closure Library is released, but haven't set up that workflow yet. In the meantime I will release it separately. Thanks for bringing this to our attention and apologies for the inconvenience!

**Comment by kjin** [comment]
It should be published now. Let us know if you are still having issues!

**Comment by banguit** [comment]
Hi @kjin, thank you for the update!
