### ISSUE TITLE
clousurebuilder.py fails if no excludes are provided

### ISSUE THREAD

**Issue by earlzero** [google/closure-library#1097]
Hi All,

I'm just starting to use this library and wasn't able to follow tutorial in https://developers.google.com/closure/library/docs/closurebuilder due to the following error message

```
user@host % python3 closure-library/closure/bin/build/closurebuilder.py \
  --root=closure-library/ \
  --root=myproject/ \
  --namespace="myproject.start"
closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
Traceback (most recent call last):
  File "closure-library/closure/bin/build/closurebuilder.py", line 295, in <module>
    main()
  File "closure-library/closure/bin/build/closurebuilder.py", line 219, in main
    if js_path not in options.excludes:
TypeError: argument of type 'NoneType' is not iterable
```

I went to check that line 219 and spotted that the code doesn't check if options.excludes is None so it silently fails. After I added that check, I was able to fix the issue.

I'll create a small PR to fix the issue.

**Comment by shicks** [comment]
Closed by merging #1098
