### ISSUE TITLE
depswriter.py - files with utf8 bom

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#11]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=625

**Comment by joeltine** [comment]
@nanaze can you PTAL at the PR for this issue? They've signed the CLA.

**Comment by ducklord** [comment]
After this has been merged into master, we are having some issues building. Running Python2.7, we get something like `goog.addDependency('../res/fontconfig.js', [u'sweeper.FONT.Setting', u'sweeper.FONT.config'], [u'jst.text.FontConfig'], false);` in our `deps.js`.

**Comment by concavelenz** [comment]
That is unfortunate. That we don't have testing for these python utilities is just lame.

**Comment by concavelenz** [comment]
I'll have a fix pushed out shortly (along with a regression test)

**Comment by concavelenz** [comment]
Should be fixed now.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
