### ISSUE TITLE
Empty table header

### ISSUE THREAD

**Issue by jbarrantes** [google/closure-library#1100]
Currently **goog.ui.DatePicker** renders an empty `<th>` in the calendar header. This accessibility issue can be found via the WAVE extension:

![Empty table header](https://user-images.githubusercontent.com/496067/100918523-35fa3800-349e-11eb-9a10-937b9517aba8.png)

The recommendations by WAVE, if the cell must remain empty is to make the cell a `<td>` rather than a `<th>`.

**Comment by shicks** [comment]
Thanks for reporting this.  The goog.ui library is more or less unmaintained and not recommended at this point.  We'd consider merging a PR to fix this, but will not work on it ourselves.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
