### ISSUE TITLE
Does `goog.string.getRandomString` ensure 64-bits of randomness?

### ISSUE THREAD

**Issue by jngbng** [google/closure-library#1101]
The document says `goog.string.getRandomString` returns a string with at least 64-bits of randomness.

But [goog.string.getRandomString](https://github.com/google/closure-library/blob/9cceadce5e7e8d34938247e0094c06c288f94841/closure/goog/string/string.js#L1140) relies on two 31-bits random numbers so that the result is of 62-bits of randomness, not 64-bits, isn't it?

`x` is `2147483648(0x80000000)` and `Math.floor(Math.random() * x)` returns a number between 0 and `2147483647((0x7FFFFFFF)`, which gives a 31-bits of randomness.

I think `x` should be `0x100000000` to ensure at lest 64-bits of randomness.

ps. 32 least significant bits of `goog.now()` is not so random, so I just say 31-bits or randomness for the later part of result.

**Comment by shicks** [comment]
`crypto.getRandomValues` has over 97% support.  The best solution would probably be to just use that when it's available?

**Comment by jngbng** [comment]
@shicks Thanks!
