### ISSUE TITLE
TOUCHEND event always have clientX and clientY set as 0, 0 in iOS Simulator 5.0 and iOS 4.2.1

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#111]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=482

**Comment by joeltine** [comment]
Fixed in https://github.com/google/closure-library/commit/b2cc62aeec361ea1279db21b3ed70823375d8dad#diff-01579e95a5b65736bffa763fc4797129
