### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by korczivo** [google/closure-library#1112]
When XhrIo's send() function causes a HTTP status code of zero, it seems to mistakenly trigger the success event. In my opinion, it means there was no response. That said, I expect the error event to be triggered instead.

Or since it's not a defined error code, just the complete event without success/error events? Up to your discussion.

How to reproduce? I've been POSTing to a non-existing local path like /v2.0/me/messages/ using JSON.

Thanks for help

**Comment by 12wrigja** [comment]
I think is is working as intended given the comments [here in XhrIO](https://github.com/google/closure-library/blob/6c1464c43b0a5b344059a2fef33060dbb652ac07/closure/goog/net/xhrio.js#L1041-L1043).

That being said, it may no longer be the case that file URIs use this status code for successful file loading, so we can change this. Would you mind investigating and seeing if the status code is actually different for success vs failure for file URIs?

**Comment by korczivo** [comment]
You right! That was from me side! Issue for close
