### ISSUE TITLE
goog.ui.Component moving an element inside component doesn't work propertly

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#112]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=481

**Comment by joeltine** [comment]
@ziegs can you help determine the appropriate priority for this?

**Comment by dferrara19** [comment]
Documentation is pretty clear
https://closure-library.googlecode.com/git-history/docs/local_closure_goog_ui_component.js.source.html#line977

You can't add a child that's already in the document, this is WAI
