### ISSUE TITLE
Murmur3 Hash

### ISSUE THREAD

**Issue by stychu** [google/closure-library#1120]
Will there be murmur3 hash available in the crypto subclass?

**Comment by kjin** [comment]
We don't have any plans to add it. What are you using it for?

I'm not well-versed in the crypto space, but based on online sources, it seems like murmur3 is not cryptographically secure?

**Comment by stychu** [comment]
I have a scenario where I need to produce a hash from nodeJs which would match the hash produced in java but I'm struggling to find an equivalent hashing function in nodeJs

So having this java example:
`
private static final HashFunction MURMUR_3_128 = Hashing.murmur3_128(SEED);

    public static String hash(String string) {
        if (string == null) {
            return null;
        }
        return MURMUR_3_128.hashUnencodedChars(string).toString();
    }
`

I would like to achieve the same HASH in nodeJs

**Comment by kjin** [comment]
If you are using Node.js, have you considered using an [murmur3 npm module](https://www.npmjs.com/search?q=keywords%3Amurmur3&ranking=popularity)? Or are you already using Closure Library for other reasons in Node.js? Closure isn't well-supported on Node.js at the moment.

**Comment by stychu** [comment]
Thanks @kjin I found xxHash is sufficient for what I look for. I couldn't find anything relevant to murmur3 in both java and javascript/nodejs that would give me the same output hash.
