### ISSUE TITLE
deps.js called by base.js but not in path

### ISSUE THREAD

**Issue by ACH1980** [google/closure-library#1125]
As mentioned in title `base.js` (`./closure-library/closure/goog/base.js`) tries to get `deps.js` from same path (`./closure-library/closure/goog/deps.js`), but there isn't any `deps.js` in that path.

![image](https://user-images.githubusercontent.com/39656381/111812387-60022980-88d8-11eb-8528-36178079e5d0.png)
![image](https://user-images.githubusercontent.com/39656381/111812895-d737bd80-88d8-11eb-87d8-5356ebb7d035.png)

**Comment by kjin** [comment]
Thanks for reporting this. Are you running a server from the root directory of the repo? If so, you'll need to run `npm install` (or `npm run gen_deps_js`, a shorthand once `npm install` has been run once) to generate `deps.js` first.

That being said, there is currently a bug that prevents `deps.js` from being generated. We're fixing the bug at the moment, but in the meantime, you'll either have to checkout b0c91b371786014e659b9923c03fb73625a1cfc1 or earlier, or patch in [this change](https://github.com/google/closure-library/commit/41fc0d31ae8d41d60cbae0fec487775c4d0ba0ec.patch).

**Comment by ACH1980** [comment]
Does this require node? I thought it was a client library that doesn't require node...

**Comment by ACH1980** [comment]
When I run `gen_deps_js` it is throwing an error that it couldn't find the module `google-closure-deps`

![image](https://user-images.githubusercontent.com/39656381/111824250-3d770d00-88e6-11eb-8b88-fc90be7275f5.png)

**Comment by ACH1980** [comment]
I've also tried applying the patch, but it remains the same problem :(

**Comment by ACH1980** [comment]
@kjin did you see the updates?

**Comment by kjin** [comment]
Did you run `npm install` first? You'll get that "Cannot find module 'google-closure-deps'" if you didn't.

Yes, we require Node.js to generate this file. It's prepackaged with the npm package (though, I guess npm is still required there). But otherwise, there is no runtime dependency on Node.

**Comment by ACH1980** [comment]
Ok thx

**Comment by ACH1980** [comment]
The installation worked, but this error remains:
![image](https://user-images.githubusercontent.com/39656381/111852322-c86ffb80-8916-11eb-87fb-ccd09e8d275a.png)

**Comment by kjin** [comment]
Can you share the contents of test.js?

**Comment by ACH1980** [comment]
`goog.provide('goog.dom');
goog.provide('goog.dom.TagName');
goog.provide('goog.dom.createDom');

goog.require('goog.dom');
goog.require('goog.dom.TagName');
goog.require('goog.dom.createDom');

function sayHi() {
    var newHeader = goog.dom.createDom(goog.dom.TagName.H1, { 'style': 'background-color:#EEE' },
        'Hello world!');
    goog.dom.appendChild(document.body, newHeader);


    const imageLoader = new goog.net.ImageLoader();
    goog.events.listen(imageLoader, goog.net.EventType.COMPLETE,
        function(e) {});
    imageLoader.addImage("image_id", "http://path/to/image.gif");
    imageLoader.start();
}`

**Comment by kjin** [comment]
You don't need the `goog.provide` statements there. `goog.provide` and `goog.require` are akin to `export` and `import` respectively (more accurately, `goog.require` loads a namespace provided by `goog.provide`). You can observe this by seeing that `closure/goog/dom/dom.js` provides `goog.dom`.

**Comment by ACH1980** [comment]
Ah thx for the info

**Comment by ACH1980** [comment]
One question came up now: What do I need to add into `goog.require`? Is the above example correct (except the `goog.provide`)? or should I add `goog.dom.appendChild` too?

**Comment by kjin** [comment]
A namespace that you `goog.require` should be `goog.provide`'d somewhere. So `goog.require('goog.dom.createDom');` wouldn't work since it's not provided (it's simply part of `goog.dom`). The same goes for `goog.dom.appendChild`.

As for `goog.dom.TagName`, although it is technically in the `goog.dom` namespace, it's good to keep requiring it because doing so indicates an explicit reference to `dom/tagname.js`. Today, it gets transitively require'd through `dom/dom.js` regardless, but if we were to remove that transitive dependency tomorrow, your code would break unless you retained that explicit reference.

**Comment by ACH1980** [comment]
But it isn't a problem, requiring more than `goog.provide`d is, right? So the above Code (without the `goog.provide`s) should still work, right? It has worked, but I'd like to understand if it is normal that it still should be functioning or if it was some random wonder or so.

Next question is, I've expanded the code to this one and it is throwing the error pasted below the code:
```goog.require('goog.dom');
goog.require('goog.dom.TagName');
goog.require('goog.dom.createDom');
goog.require('goog.dom.appendChild');
goog.require('goog.net');
goog.require('goog.net.ImageLoader');
goog.require('goog.net.EventType');
goog.require('goog.net.EventType.COMPLETE');
goog.require('goog.events');
goog.require('goog.events.listen');



function sayHi() {
    var newHeader = goog.dom.createDom(goog.dom.TagName.H1, { 'style': 'background-color:#EEE' },
        'Hello world!');
    goog.dom.appendChild(document.body, newHeader);

    const imageLoader = new goog.net.ImageLoader();
    goog.events.listen(imageLoader, goog.net.EventType.COMPLETE, ) //  function(e) {});
    imageLoader.addImage("image_id", "https://http.cat/200");
    imageLoader.start();
}```

Throws the following error:
`Assertion failed: Listener can not be null.`
I've not added the full error (especially the stacktrace, the message is the full one) because it expands very big.

The code for this addition is mostly copy and pasted from: https://google.github.io/closure-library/api/goog.net.ImageLoader.html

**Comment by kjin** [comment]
Yes, given that `goog.require` failed to find a namespace that wasn't `goog.provide`'d by another file (as you showed in your screenshot earlier) but the subsequent code still executed, there's no behavioral impact in this current situation. So I guess that's to say it's not a random fluke that it continued to execute. I say "this current situation" because the code will likely fail to be compiled by Closure Compiler.

As for this issue, could it be that the listener is commented out (in the line that starts with `goog.events.listen`)?

**Comment by ACH1980** [comment]
I thought that was a error catcher, that's the reason why I've outcommented it.

**Comment by kjin** [comment]
Ah, I see.

Since the original issue was resolved, I am closing this issue for now. Please open a new issue if you encounter one, thanks!
