### ISSUE TITLE
Assertion failed: Listener can not be null.

### ISSUE THREAD

**Issue by ACH1980** [google/closure-library#1126]
Issue described in this and the following comments in #1125 

https://github.com/google/closure-library/issues/1125#issuecomment-804414121

**Comment by kjin** [comment]
I assumed you had uncommented it again -- when you do, what happens? The function you commented out is not an error handler, it's the event listener itself.

**Comment by ACH1980** [comment]
Ah ok, when I uncomment it it doesn't work but also produces no error and only this warning:
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ base.js:1196:10`

Also I didn't understand what should be instead of the three dots in the example, so I just removed them (I assume it's a placeholder for something)...

**Comment by ACH1980** [comment]
So the actual code is:
```goog.require('goog.dom');
goog.require('goog.dom.TagName');
goog.require('goog.dom.createDom');
goog.require('goog.dom.appendChild');
goog.require('goog.net');
goog.require('goog.net.ImageLoader');
goog.require('goog.net.EventType');
goog.require('goog.net.EventType.COMPLETE');
goog.require('goog.events');
goog.require('goog.events.listen');



function sayHi() {
    var newHeader = goog.dom.createDom(goog.dom.TagName.H1, { 'style': 'background-color:#EEE' },
        'Hello world!');
    goog.dom.appendChild(document.body, newHeader);

    const imageLoader = new goog.net.ImageLoader();
    goog.events.listen(imageLoader, goog.net.EventType.COMPLETE,
        function(e) {});
    imageLoader.addImage("image_id", "https://http.cat/200");
    imageLoader.start();
}
```

**Comment by kjin** [comment]
> Ah ok, when I uncomment it it doesn't work

What do you expect to happen when `sayHi` is called?

> but also produces no error and only this warning:
> `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ base.js:1196:10`

Yes, but this shouldn't affect any behavior, as it's just a warning. I don't see any indication that `XMLHttpRequest` is used in your code snippet (it may be used -- I just can't find where), do you have code elsewhere that is making web requests?

> Also I didn't understand what should be instead of the three dots in the example, so I just removed them (I assume it's a placeholder for something)...

It is a placeholder for something. That statement means you are listening with a callback when `imageLoader` emits a `COMPLETE` event. The callback will be called when that happens. If the callback doesn't contain anything in it, then you might as well remove it, because you are essentially saying "once the image loader completes loading, react to it by doing nothing".

**Comment by ACH1980** [comment]
> What do you expect to happen when `sayHi` is called?

It should load the image

**Comment by kjin** [comment]
Can you be more specific:
* How can you tell the image isn't loaded? (For example, examining the Network tab in Chrome)
* What do you do with the image once it's loaded? (Do you expect the image to be displayed?)
* What is triggering the call to `sayHi`?

**Comment by ACH1980** [comment]
Yeah I expected the image to be shown in the `image_id` div, but you're right it is loaded in the background. Thanks for help
