### ISSUE TITLE
Closure-Library Github Pages Demos Missing JavaScript Resource

### ISSUE THREAD

**Issue by nisfornature** [google/closure-library#1129]
EDIT: Sorry, I meant **All Demos > Autocomplete > Remote**.

It appears at least one of the demos on the Closure-Library Github Page may not be working.

From https://google.github.io/closure-library/source/closure/goog/demos/ and selecting All Demos > Autcomplete > ~~Rich~~ Remote, hyperlinks and UI Autocomplete namespace calls appear to not retrieve the autocompleteremotedata.js resource?

**Comment by 12wrigja** [comment]
I cannot reproduce this - loading the Rich Remote demo does indeed allow me to retrieve that file and do autocomplete queries against it.

Can you post what error(s) you see from the DevTools console?

**Comment by nisfornature** [comment]
On Chrome Version 89.0.4389.114, I see the following:

When navigating to All Demos > Autocomplete > Remote, and adding input to the input field, I see no UI changes and errors are logged:
![goog ui ac Remote autocompleteremotedata js demo does not display selection element](https://user-images.githubusercontent.com/24690348/114768310-ad868080-9d36-11eb-87a0-5198c20b1bd9.PNG)


![console 1](https://user-images.githubusercontent.com/24690348/114768301-abbcbd00-9d36-11eb-8261-f600d1e90e0b.PNG)

On page load:
![console 2](https://user-images.githubusercontent.com/24690348/114768303-ac555380-9d36-11eb-8a37-3465e886750a.PNG)

After inputting text in the input field (with ID, "txtInput"), autcompleteremotedata.js appears not to exist on Github Pages (https://google.github.io/closure-library/source/closure/goog/demos/autocompleteremotedata.js):
![console 3](https://user-images.githubusercontent.com/24690348/114768306-acedea00-9d36-11eb-9974-80cd71b0113f.PNG)

![console 4](https://user-images.githubusercontent.com/24690348/114768307-acedea00-9d36-11eb-9542-6b2dc32b888e.PNG)

**Comment by kjin** [comment]
Ah, thanks for letting us know -- we had renamed (and re-formatted) `autocompleteremotedata.js` to `autocompleteremotedata.json` in 78cffdf but forgot to change the reference in this file. I'll fix this soon (~today). Sorry for the inconvenience!

**Comment by nisfornature** [comment]
Thanks so much!
