### ISSUE TITLE
goog.asserts.assert()

### ISSUE THREAD

**Issue by anshgo01yal** [google/closure-library#1130]
hello everyone,
 can anyone please tell me how goog.asserts.assert() work???

**Comment by kjin** [comment]
Hi @anshgo01yal, `goog.asserts.assert` checks whether a condition (provided as the first argument) evaluates to true, and throws if it does -- although this depends on whether `ENABLE_ASSERTS` define is set to true. This is from the inline docs: https://github.com/google/closure-library/blob/0b41955ad8d55aebd2217de647a6de3a8c63916e/closure/goog/asserts/asserts.js#L169-L187

Is that what you were looking for, or did you have a more specific question?

**Comment by anshgo01yal** [comment]
thanks @kjin this exactly what I am asking for.
do you have any documentation link where I can learn about goog.assert , goog.provide  and all such functions

**Comment by 12wrigja** [comment]
@anshgo01yal you might find the [API reference for goog.asserts](https://google.github.io/closure-library/api/goog.asserts) helpful in this context (and others).

**Comment by anshgo01yal** [comment]
thanks @12wrigja.
