### ISSUE TITLE
Closure Demos page not displaying demo links

### ISSUE THREAD

**Issue by gazzali** [google/closure-library#1132]
Hi,

The Closure Demos page doesn't display links at the moment so it's not possible to view any of the demo pages:
https://google.github.io/closure-library/source/closure/goog/demos/

**Comment by 12wrigja** [comment]
Thanks for the heads up - I'm investigating this today.

**Comment by 12wrigja** [comment]
We fixed this with 04d6fb3b05b8c8fdbaa743377ce263718c6bc079 and c5e0153771845507189d30eeb3e6ec530d4d67b9.

**Comment by gazzali** [comment]
Perfect, thanks!
