### ISSUE TITLE
Include `webkitFullscreenEnabled` in `goog.dom.fullscreen.isSupported`

### ISSUE THREAD

**Issue by camador-lucid** [google/closure-library#1140]
https://github.com/google/closure-library/blob/d760c8461a57f41cea6f191138bc457b42226322/closure/goog/dom/fullscreen.js#L76

This line is causing some issues in our applications. 
Should it be `(body.webkitRequestFullscreen && doc.webkitFullscreenEnabled) ||`? Following https://developer.apple.com/documentation/webkitjs/document/1630333-webkitfullscreenenabled

**Comment by kjin** [comment]
I don't see why not -- would you like to send a PR?

**Comment by camador-lucid** [comment]
Yeah, I will put it up in a minute

**Comment by camador-lucid** [comment]
I couldn't link the issue to the PR: https://github.com/google/closure-library/pull/1141

**Comment by kjin** [comment]
The PR is merged, so I think we can close this!
