### ISSUE TITLE
`goog.date.UtcDateTime.fromIsoString` does not support extended year

### ISSUE THREAD

**Issue by p-himik** [google/closure-library#1142]
According to [a reference of `Date.toISOString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString), the format is either `YYYY-MM-DDTHH:mm:ss.sssZ` or `±YYYYYY-MM-DDTHH:mm:ss.sssZ`.
However, only the former is supported:
```javascript
(new Date(-1, 1)).toISOString()
=> '-000001-01-31T21:46:32.000Z'
goog.date.UtcDateTime.fromIsoString((new Date(-1, 1)).toISOString())
=> null
```

**Comment by 12wrigja** [comment]
For what it's worth, you may find your date/time manipulation needs better solved by [Temporal](https://github.com/tc39/proposal-temporal), for which there are several polyfills available.

**Comment by shicks** [comment]
We also have an issue with the formatting - it should always pad the year to 4 unsigned or 6 signed digits, and currently it does not.
