### ISSUE TITLE
Austrian (de-AT) currency format is defaulting to a barely used format

### ISSUE THREAD

**Issue by simonbraeuer** [google/closure-library#1144]
https://github.com/google/closure-library/blob/61eef0f7ac67618a504c976a0bdb4f124f7eaa86/closure/goog/i18n/numberformatsymbols.js#L600

Usually the preferred way to display currency string is that we put the currency code at the end of the text. (Similar as for Germany)
The current pattern makes Angular create really strange currency strings when using [formatCurrency](https://angular.io/api/common/formatCurrency)(-10, 'de-AT', 'EUR', 'EUR'). It will result in "-EUR 10,00", which is really not common here and seen as a bug by the majority of the people.

From my perspective the patterns may be checked by citizens of the according countries. I suggest that the currency pattern is changed to this format for whole DACH region (Germany, Austria, Switzerland).

CURRENCY_PATTERN: '#,##0.00 ¤;-#,##0.00 ¤'

**Comment by 12wrigja** [comment]
I've created https://unicode-org.atlassian.net/browse/CLDR-15094 on your behalf. Note that CLDR releases tend to take a while (>6 months).

**Comment by shicks** [comment]
Closing this here - if it gets merged in CLDR then we'll pull it automatically.

**Comment by 12wrigja** [comment]
https://unicode-org.atlassian.net/browse/CLDR-15094

Wanted to echo the post made on this asking for official feedback - @simonbraeuer please comment on that CLDR ticket if you have more input to give directly.

> For all formats, CLDR data aligns to the most common usage in the market. That is, decisions are based on the market and usage cases, as well as language. Therefore it would be great if you are able to provide any of the following additional information. Helpful information includes:
> 
> Examples of the most prominent usage(s)
> 
> Evidence of usage in the mainstream media (for example, a newspaper or magazine)
> 
> If there are alternatives (e.g. different currency symbols), we need to see examples of those (from the most prominent sources). Please note that failure to supply alternatives if they exist significantly reduces credibility.
