### ISSUE TITLE
navigator.userAgent possible improvement showing on web inspector

### ISSUE THREAD

**Issue by fstorres49** [google/closure-library#1150]
I'm developing an application where I display the location of a user on a google map. After checking the inspector, I got this improvement message:
<img width="523" alt="possible_improvement" src="https://user-images.githubusercontent.com/60103532/146248969-43addd32-1b91-4d85-9272-e3e42e2e57fc.png">

I checked the affected resources code and it pointed to this repo:  https://github.com/google/closure-library/search?q=navigator.userAgent. Not sure if it is already mapped.

**Comment by shicks** [comment]
Thanks for the report.  We're in the process of enabling the usage of userAgentData, which is the replacement for userAgent, but such a subtle change requires a methodical staged rollout.  For now, please bear with the warnings, and we'll try to get them cleaned up as soon as we can.
