### ISSUE TITLE
goog.i18n.collation.createComparator misses locale normalization

### ISSUE THREAD

**Issue by andrew--r** [google/closure-library#1154]
Hi!

I discovered that [`goog.i18n.collation.createComparator`](https://github.com/google/closure-library/blob/master/closure/goog/i18n/collation.js#L31) throws `RangeError: Incorrect locale information provided` when `goog.LOCALE` or provided `opt_locale` contains underscore (e.g. `en_US`, `en_GB`).

Seems like it misses the locale normalization logic that is presented in [`goog.i18n.DateTimeFormat`](https://github.com/google/closure-library/blob/a8840a66c2a1e64feeda62e97b21049165b019a4/closure/goog/i18n/datetimeformat.js#L508-L509) and [`goog.i18n.NumberFormat`](https://github.com/google/closure-library/blob/master/closure/goog/i18n/numberformat.js#L783-L786).

**Comment by 12wrigja** [comment]
This seems aligned with the native Intl.Collator API's, which reject locales that use underscores:

```
new Intl.Collator('en_US')
VM151:1 Uncaught RangeError: Incorrect locale information provided
    at new Collator (<anonymous>)
    at <anonymous>:1:1
(anonymous) @ VM151:1

new Intl.Collator('en-US')
Collator {compare: ƒ}
```

**Comment by andrew--r** [comment]
@12wrigja native Intl.DateTimeFormat and Intl.NumberFormat also reject such locales, but their goog.i18n.* wrappers have normalization logic that replaces underscore with dash. You can see that by visiting the links from my original report.

**Comment by shicks** [comment]
FWIW, if we make any change here, we should make the goog.i18n APIs _less_ permissive to match the builtin Intl API restrictions.  In general, we're trying to keep as close as possible to the standards.

Is it possible for you to normalize your input before passing it to goog.i18n?

**Comment by shicks** [comment]
Closing this issue because we want to move closer to the standard platform, rather than further. We'd be open to working on a bug to stricten the other goog.i18n APIs.
