### ISSUE TITLE
"Optional catch binding" error when using ES5 output

### ISSUE THREAD

**Issue by mtruyens** [google/closure-library#1155]
When setting the output to ES5, I'm getting errors in lines 963 and 1011, preventing the compilation from succeeding

goog/i18n/numberformat.js:963:8: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT_2019 mode or better: Optional catch binding.

**Comment by 12wrigja** [comment]
This seems like maybe your compiler settings are incorrect somewhere - we definitely have clients able to compile this code down to ES5. Can you post your full set of flags being passed to Closure Compiler?

**Comment by concavelenz** [comment]
Seems like the input language is set to something before ECMASCRIPT_2019
