### ISSUE TITLE
Wrong Placement of Currency for Norwegian Locale

### ISSUE THREAD

**Issue by Akisan98** [google/closure-library#1157]
Currently Norwegian has following pattern: "¤ #,##0.00" meaning: NOK 20 or Kr 20, instead of the correct pattern: "¤ #,##0.00": 20 NOK or 20 Kr, like its in Danish or French.

Basically a mirror of Danish with Norwegian spelling of things.

**Comment by Akisan98** [comment]
NOK/kr can come before or after amount.

### Språkrådet (The Language Guild)  - https://www.sprakradet.no/svardatabase/sporsmal-og-svar/kronebelop-rekkjefolgje-komma-og-strek/

- The easiest and most natural way is 500 kr (After amount)
- NOK ideally before amount (but can be flipped).
- Normally 500 kr is the best, but in some cases it might be right to flip it.
- If there is multiple currencies then nkr should be used. rather then kr (Considering that Danmark and Sweden also call their currency Kroner)


### So both way should be possible to use in frameworks like Angular (and Flutter?), with Kr / NOK before or after amount as both are valid. 
In Norwegian ",–" is often used to indicate price rather than kr.

If only one can be used then the Facts on Ground is that both Norges Bank and DNB uses Currency after amount.

Norges Bank (The Central Bank) - The institute responsible for monitary policies notes Currency after amount:
https://www.norges-bank.no/tema/Statistikk/Valutakurser/?tab=currency&id=USD

DNB (The National Bank, where Gov. still has 34% share)
https://www.dnb.no/markets/valuta-og-renter/valutakalkulator

**Comment by 12wrigja** [comment]
As mentioned in that other issue: if you think this is a problem it is likely to affect many more projects than just Closure Library. I'd suggest reporting it upstream to CLDR and their surveyors will sort it out eventually.

https://cldr.unicode.org/index/bug-reports

**Comment by shicks** [comment]
Closing - we won't fix this locally, the correct thing is to fix it upstream and we'll pull the fix down at the next sync.
