### ISSUE TITLE
`closure-make-deps` generates incorrect paths on Windows.

### ISSUE THREAD

**Issue by yamadayutaka** [google/closure-library#1159]
### To Reproduce

1. Create working directory (e.g. C:\\work\\test).
2. Change directory (e.g. `cd C:\\work\\test`).
3. Clone closure-library (e.g. `git clone https://github.com/google/closure-library.git`).
4. Change directory (e.g. `cd closure-library`).
5. Install npm package (e.g. `npm install`).

Following the above steps will generate closure/goog/deps.js.

When you open deps.js, it has the following contents. 

```
goog.addDependency('../C:\work\test\closure-library\closure\goog\a11y\aria\announcer.js', ['goog.a11y.aria.Announcer'], ['goog.Disposable', 'goog.Timer', 'goog.a11y.aria', 'goog.a11y.aria.LivePriority', 'goog.a11y.aria.State', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string'], {'lang': 'es6'});
goog.addDependency('../C:\work\test\closure-library\closure\goog\a11y\aria\aria.js', ['goog.a11y.aria'], ['goog.a11y.aria.Role', 'goog.a11y.aria.State', 'goog.a11y.aria.datatables', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string']);
```

### Expected behavior

The following content will be generated.

```
goog.addDependency('a11y/aria/announcer.js', ['goog.a11y.aria.Announcer'], ['goog.Disposable', 'goog.Timer', 'goog.a11y.aria', 'goog.a11y.aria.LivePriority', 'goog.a11y.aria.State', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string'], {'lang': 'es6'});
goog.addDependency('a11y/aria/aria.js', ['goog.a11y.aria'], ['goog.a11y.aria.Role', 'goog.a11y.aria.State', 'goog.a11y.aria.datatables', 'goog.array', 'goog.asserts', 'goog.dom', 'goog.dom.TagName', 'goog.object', 'goog.string']);
```

### Additional context

In "depswriter.py", the path is normalized by the following code.

https://github.com/google/closure-library/blob/master/closure/bin/build/depswriter.py#L125-L136

**Comment by yamadayutaka** [comment]
I have a solution and I am preparing for PR.

**Comment by joeyparrish** [comment]
Can this be considered closed now that the PR has been merged?  Or does this project only close issues when a release is completed?

**Comment by joeyparrish** [comment]
For anyone else on this issue looking for a solution before the next release is published, this is how you use a pre-release version at the SHA1 where this issue was fixed: https://github.com/shaka-project/shaka-player/pull/4086/files

**Comment by shicks** [comment]
We usually try to set it up so that merging the PR auto-closes the issue.  I guess that didn't happen here.
