### ISSUE TITLE
`npm install` failed to generate `deps.js`

### ISSUE THREAD

**Issue by anhminhtran235** [google/closure-library#1189]
I followed the setup steps [here](https://developers.google.com/closure/library/docs/gettingstarted#step1) and ran the following commands: 
```
git clone https://github.com/google/closure-library
cd closure-library
npm install
```
At the time of this writing, [this](https://github.com/google/closure-library/commit/0e567abedb058e9b194a40cfa3ad4c507653bccf) is the latest commit

After `npm install` is run, however, `deps.js` is not generated.

When I use code from the [latest release](https://github.com/google/closure-library/releases/tag/v20230206), it works fine

Could somebody fix either the code or the [docs](https://developers.google.com/closure/library/docs/gettingstarted#step1) (and say that the latest release must be used?)

Thank you!

**Comment by anhminhtran235** [comment]
@12wrigja Could you check if `deps.js` was created? I got the same terminal output as you did but `deps.js` was not generated

**Comment by 12wrigja** [comment]
closure/goog/deps.js does exist and contains what look like relevant dependency management lines.

Can you try running `npm run gen_deps_js` and seeing if `closure/goog/deps.js` will be generated for you? It does for me.

**Comment by anhminhtran235** [comment]
@12wrigja Oh my bad. Looks like `deps.js` was generated. My VS Code just didn't see it until I gave it the full path `closure/goog/deps.js`

I still have one issue though. I followed the [Closure tutorial](https://developers.google.com/closure/library/docs/gettingstarted#step4) but got an error:

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/54651212/228020976-82603871-b71d-4c76-a643-0051c02363aa.png">

It's supposed to display "Hello World" on the screen. When I used the latest release of closure library, it worked (but not if I pull code from the latest commit on master)

Here is my code in case you want to take a look at it. I basically just copied from the tutorial: https://github.com/anhminhtran235/google-closure-playground

**Comment by 12wrigja** [comment]
Looking at that repo I don't think the link to the closure-library repo is setup properly - it's not a proper submodule link.

Why do you want to link against our repository directly? We offer no stability guarantees this way, and you are far better off consuming our NPM packages.

**Comment by anhminhtran235** [comment]
I pushed my code to git just to show you the folder structure as well as the `hello.html` and `hello.js` files. For some reason when the code is pushed to github, it links to the closure-library like that.  Here's what it looks like on my local computer

![image](https://user-images.githubusercontent.com/54651212/228060440-71cd0ec4-26fb-48b7-8b66-c2c6dd75a99f.png)

**Comment by 12wrigja** [comment]
I see.

I think what you want to do instead is something like this:

Create a new NPM project:

```
npm init -y
```

Install the Closure Library NPM package (https://www.npmjs.com/package/google-closure-library):

```
npm install --save google-closure-library
```

Then, change your hello.html file to point to base.js and deps.js from within the node module package:

```
<script src="closure-library/closure/goog/base.js"></script> <-- old
```

becomes

```
<script src="./node_modules/google-closure-library/closure/goog/base.js"></script>
```

**Comment by anhminhtran235** [comment]
That makes sense. That would use the release version so I think it'd work. Do you know who's maintaining [this doc](https://developers.google.com/closure/library/docs/gettingstarted#step1)? It'd be super helpful if somebody can change the instruction from cloning this repo to installing from npm. It took me quite a while to figure out that the latest release would work for me

**Comment by 12wrigja** [comment]
I think I've found out where that doc is being maintained internally, so I'll see if I get that updated.

**Comment by anhminhtran235** [comment]
Perfect! Thank you

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
