### ISSUE TITLE
goog.editor.Command.EDIT_HTML doesn't work in Closure Editor

### ISSUE THREAD

**Issue by shhnjk** [google/closure-library#1194]
`goog.editor.Command.EDIT_HTML` button does not seem to work anymore.

Repro:
1. Add `goog.editor.Command.EDIT_HTML` in [buttons](https://github.com/google/closure-library/blob/master/closure/goog/demos/editor/editor.html#L99).
2. While Edit HTML button appears, clicking on it does nothing.

*Note: you can test this dynamically by adding break point on buttons in the [live demo](https://google.github.io/closure-library/source/closure/goog/demos/editor/editor.html).*

**Comment by 12wrigja** [comment]
https://github.com/google/closure-library/blob/c92fcbdbcc19f88581cd72045d085fd4e0f689e0/closure/goog/demos/editor/editor.html#L85-L96

Just adding the button to the UI is not enough to get a plugin to do something. You would need to figure out which plugin enabled editing HTML (don't think there is one provided in Closure that I can find?), and register it (like the other plugins listed above) in order for the command the button triggers to do anything.

**Comment by shhnjk** [comment]
Got it, so basically the Closure Editor doesn't provide plugin, and therefore I need to implement one myself.
