### ISSUE TITLE
`goog.dom.appendChild` documentation lists incorrect type

### ISSUE THREAD

**Issue by rome-user** [google/closure-library#1201]
See the following page https://google.github.io/closure-library/api/goog.dom.html#appendChild

The parameters `parent` and `child` are both listed as `Node | null`. However, the implementation of the function tells a different story.

https://github.com/google/closure-library/blob/5918355a90382ab6d17e31ba7df8044d40f319f1/closure/goog/dom/dom.js#L1258-L1264

**Comment by shicks** [comment]
Strictly speaking, this is correct.  In practice, we've found it impossible to fix all of these incorrect nullability issues because of the mountain of legacy code that depends on them.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
