### ISSUE TITLE
URIs with empty fragments are not preserved

### ISSUE THREAD

**Issue by quoll** [google/closure-library#1209]
When the fragment portion of a URI is an empty string, then this is not distinguished from an undefined fragment.

Consequently, an empty fragment (a common construct in Semantic Web applications) is not preserved. For instance, the following returns true:
```js
new goog.Uri("http://ex.test/path#").toString() == new goog.Uri("http://ex.test/path").toString()
```
This goes against RFC 3986, [5.3 Component Recomposition](https://datatracker.ietf.org/doc/html/rfc3986#section-5.3), which states:

> Note that we are careful to preserve the distinction between a
   component that is undefined, meaning that its separator was not
   present in the reference, and a component that is empty, meaning that
   the separator was present and was immediately followed by the next
   component separator or the end of the reference.

In general, it would be simple to record a `null` or empty string on [line 154](https://github.com/google/closure-library/blob/31a330ac7e83580a1edfde418e34cbf3e32b849c/closure/goog/uri/uri.js#L154C75-L154C75), but the compatibility note points out that this may not work in IE.

**Comment by trevorade** [comment]
It doesn't appear to be possible to construct a native `URL` ending in `'#'` without setting the initial string to have one.

Setting `URL.hash` to the empty string results in no ending `#`.

In addition, `new URL('http://example.com/test#').hash === new URL('http://example.com/test').hash` returns `true`.

Using native APIs, is there a way to distinguish `window.location` with and without the fragment token?

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
