### ISSUE TITLE
goog.dom.xml is broken on MSIE9

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#126]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=456

**Comment by joeltine** [comment]
I confirmed this is actually broken for IE10 and IE11. I've pinged the original author to get a CLA.

**Comment by joeltine** [comment]
For the record... this change was an absolute nightmare to try to submit internally. A lot of internal code really wasn't equipped to work with ActiveXObject. As a compromise I added a new opt-in param to prefer ActiveXObject, when available. This can be used by those who need select*Node support on IE.
