### ISSUE TITLE
Missing cross-browser implementation of opt_title in setToken/replaceToken of history.Html5History

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#13]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=623

**Comment by joeltine** [comment]
WAI - The API is "Html5HistoryState"... for browsers that support Html5. history.js is the cross-browser alternative.
