### ISSUE TITLE
userAgent.MOBILE is false for Android 3 tablets

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#131]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=446

**Comment by vipref** [comment]
The link to the original issue is broken.

**Comment by 12wrigja** [comment]
Given the original text is gone, I'm going to guess this is referencing the non-labs UserAgent. There are comments in the source indicating that the newer labs UserAgent is more accurate, so for any readers of this issue we would recommend you use that instead.
