### ISSUE TITLE
i18n.DateTimeFormat is off by a day when crossing over DST from New_York to Los_Angeles

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#145]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=416

**Comment by joeltine** [comment]
Fixed in https://github.com/google/closure-library/commit/fc68343662bd3f1f9987a72b72bea094d8f0cab0
