### ISSUE TITLE
Dragger often doesn't work for touch* events [patch]

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#162]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=382

**Comment by elemoine** [comment]
The original bug report includes a patch. Why has this patch never been applied? Is there anything we can do to see this patch, or another patch, applied?

**Comment by elemoine** [comment]
https://code.google.com/p/closure-library/issues/detail?id=382 has `Labels: CLASigned`.

**Comment by elemoine** [comment]
See https://github.com/google/closure-library/pull/405 for the PR. I basically ported the patch that was attached to the code.google.com issue. I'm happy to make other changes if necessary.
