### ISSUE TITLE
MouseWheelHandler: Firefox mouse events not registering properly

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#17]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=618

**Comment by shicks** [comment]
Since the repro demo is no longer working, I can't verify if this is even still an issue.  There have been some changes to the mousewheel handler since this issue was filed, so potentially it's already been fixed?  If it's actually still an issue, please reopen the issue and post a new repo case.
