### ISSUE TITLE
goog.fx.Dragger and touch events (iOS) broken

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#189]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=309

**Comment by mtsgrd** [comment]
This still looks broken to me. Can anyone else confirm?

**Comment by elemoine** [comment]
Yes. There now is a PR (https://github.com/google/closure-library/pull/405), but it's not merged yet.

**Comment by mtsgrd** [comment]
@elemoine awesome, thanks.

**Comment by elemoine** [comment]
@MatrixFrog, I think you can close this one.
