### ISSUE TITLE
Remove goog.userAgent.X11 constant

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#270]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=86

**Comment by mbeijen** [comment]
Awesome, the original issue on Google Code redirects to this issue; which means the text is gone.

**Comment by vipref** [comment]
The work, as given by the title, can likely be handled as part of #1061 

The link to the original issue no longer works.

**Comment by 12wrigja** [comment]
Closing this in favour of #1061 - we will address UserAgent changes all at once there.
