### ISSUE TITLE
Figure out a good solution to third party deps

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#278]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=42

**Comment by joeltine** [comment]
@nanaze @concavelenz This was first opened in 2009. Is this still worthwhile?

**Comment by concavelenz** [comment]
The original issue is unrelated to the Apr 30 comment.  non-advanced mode dependencies is a compiler issue.  For the original issue, this comment leads me to think this is no longer an issue:
https://github.com/google/closure-library/blob/master/third_party/closure/goog/deps.js
