### ISSUE TITLE
Investigate making some internal documentation externally available

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#281]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=2

**Comment by vipref** [comment]
The link to the original issue is broken and points to an unrelated issue.

There is Closure Library documentation at: https://developers.google.com/closure/library/docs/overview

**Comment by shicks** [comment]
I think given that we can't figure out what documentation was referred to, it probably makes sense to close this.

FWIW, there's also some scant documentation at https://google.github.io/closure-library
