### ISSUE TITLE
Windows codepage / encoding issues

### ISSUE THREAD

**Issue by jds13** [google/closure-library#302]
In trying to build the Google End-To-End Chrome extension on a Windows machine, I ran up against a series of closure codepage problems when I tried to compile what I am guessing was latin-1 source code.  My system has default encoding of utf-8 as displayed by

> python -c "import sys; print(sys.getdefaultencoding())"

My Windows codepage (displayed by chcp) is 437.

First, in e2e_dev\closure-library\closure\bin\build\source.py at the end, I replaced

> "fileobj = open(path)" 

with

> "fileobj = open(path, "r", encoding="latin-1")"

Second, in e2e_dev\closure-library\closure\bin\build\jscompiler.py

> match = _VERSION_REGEX.search(version_string.decode("latin-1"))

Finally, in "closure-library/closure/bin/build/closurebuilder.py", line 257, in main, I added .decode("latin-1") to out.write(compiled_source), viz.

> out.write(compiled_source.decode("latin-1"))

My closure compile command is closure_compile.bat:

> python closure-library/closure/bin/build/closurebuilder.py
> --root <my-project> --root closure-library --root closure-templates/javascript
> --root zlib.js/src --root typedarray -o compiled -c compiler.jar %*

Compile commands look like

> closure_compile -i source-file.js > binary-output.js

The compilations I tried appeared to work OK. Thanks.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
