### ISSUE TITLE
goog.dom.getTextContent handles whitespace incorrectly

### ISSUE THREAD

**Issue by pauldraper** [google/closure-library#305]
[`goog.dom.getTextContent`](https://github.com/google/closure-library/blob/9800b931eb5047033a520ea75ed969339b3f883a/closure/goog/dom/dom.js#L1818-1859) should return the visible text content, similar to IE's `innerText`. It fails to do this for a couple cases.

```
goog.dom.getTextContent(document.createTextNode(' '))
```

Expected: `''`
Actual: `' '`

```
goog.dom.getTextContent(document.createTextNode('\xA0'))
```

Expected: `' '`
Actual: `''`

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
