### ISSUE TITLE
Some functions limited by Function.prototype.apply

### ISSUE THREAD

**Issue by pauldraper** [google/closure-library#314]
There are limitations to the number of arguments that can be passed with `Function.prototype.apply`. 

Some functions that use `Function.prototype.apply` only use it with the variable arguments in the first place. Those are limited by this anyway. There's nothing to do there, at least not without changing the API.
- `goog.array.concat`
- `goog.array.splice`
- `goog.array.join`
- `goog.array.slice`
- `goog.math.average`
- `goog.math.standardDeviation`

But some functions accept an array as a single argument and then pass that to `Function.prototype.apply`. It is reasonable, though somewhat uncommon, for there to be more than 65,537 elements in an array.
- `goog.array.extend`
- `goog.array.flatten`
- `goog.array.insertArrayAt`
- `goog.array.rotate`
- `goog.math.Path.prototype.appendPath`
- `goog.object.create`
- `goog.string.format`
- `goog.testing.PerformanceTimer.createResults`
- `goog.testing.PerformanceTimer.prototype.finishTask_`

---

The numbers seemed to vary (OS dependent?), but this is what I've measured:

| Browser | apply() | literal |
| --- | --- | --- |
| Chrome 14 | 131155 | 32767 |
| Chrome 35 | 126213 | 65535 |
| Firefox 30 | 500001 | 65535 |
| IE 9 | 254335 | 65533 |
| IE 10 | 253667 | 65533 |
| IE 11 | 252447 | 65533 |
| Opera 22 | 126063 | 65535 |
| Safari 4 | 524215 | 524205 |
| Safari 7 | 65537 | 522159 |

[JSFiddle](http://jsfiddle.net/draperp/J6jhg/)

---

Other references to this problem:
- This issue with `goog.crypt.byteArrayToString` was [mentioned](https://groups.google.com/forum/#!topic/closure-library-discuss/TTADM4GghVI) in the discussion list and then fixed by https://github.com/google/closure-library/commit/da353e0265ea32583ea1db9e7520dce5cceb6f6a.
- [Webkit bug](https://bugs.webkit.org/show_bug.cgi?id=80797), reported 2012-03-11

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
