### ISSUE TITLE
goog.ui.Slider will continue to fire change events after the mouse is moved outside the window

### ISSUE THREAD

**Issue by apond** [google/closure-library#324]
Open a page with a slider on it.  It would be nice to open the demo page (http://closure-library.googlecode.com/git/closure/goog/demos/slider.html) but the link seems to be broken.
Click and drag the mouse on the thumb of the slider, drag your mouse outside the window and release the mouse button.
Move the mouse back over the window with the slider.

Result:
The change events continue to fire and the thumb moves with the mouse.

Expect:
If the mouse is no longer down it should end the drag and stop firing change events

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
