### ISSUE TITLE
'goog.dom.htmlToDocumentFragment()' cannot render '<tr>' nodes correctly

### ISSUE THREAD

**Issue by gucheen** [google/closure-library#326]
Cause `goog.dom.htmlToDocumentFragment()` cannot render a `<tr>` node, so, if I want to insert a `<tr>` node into a table, how can I create a node of `<tr>` with closure?
Currently, I use `ele.innerHTML` and manually add a string that includes `<tr>` tag.
Is there a better way to do that?
Or, how can I use `goog.dom.appendChild()` method(because it needs a node as arguments)?

**Comment by joeltine** [comment]
Using createDom is a reasonable way to do this
