### ISSUE TITLE
'goog.i18n.NumberFormatSymbols_es_GT' missing currency symbol

### ISSUE THREAD

**Issue by caitp** [google/closure-library#327]
Cross-referencing from https://github.com/angular/angular.js/pull/8441, we aren't getting appropriate data for this locale. Our script determines that we need to use the &#8364; symbol (presumably inherited from the base `es` locale), but we should have a symbol Q

(from CLDR24)

```xml
	<numbers>
		<currencies>
			<currency type="GTQ">
				<symbol>Q</symbol>
			</currency>
		</currencies>
	</numbers>
```

So, understandably this data isn't available in the extra locales, but it might not be unreasonable to add currency symbols for these extra locales when available.

**Comment by joeltine** [comment]
This doesn't sound like an issue w/ Closure.
