### ISSUE TITLE
Link on docs pages does not lead to API docs

### ISSUE THREAD

**Issue by greggman** [google/closure-library#329]
The link on this page

https://developers.google.com/closure/library/

to "Browse the API docs" leads to this URL

http://google.github.io/closure-library/api/

which is a dead link

**Comment by donmccurdy** [comment]
API docs link seems fixed now. Although the "Check out the goog.UI demos." link on https://developers.google.com/closure/library/ is linking to https://github.com/google/closure-library/tree/master/closure/goog/demos/, but should probably be pointing to http://google.github.io/closure-library/source/closure/goog/demos/ instead.

**Comment by joeltine** [comment]
For posterity, the API link is http://google.github.io/closure-library/api/ and its on the [main github page](https://github.com/google/closure-library). 

The demos link on the developers site is pointing to http://google.github.io/closure-library/source/closure/goog/demos/
