### ISSUE TITLE
goog.fx.Dragger is not setting up mousehandlers correctly for firefox

### ISSUE THREAD

**Issue by joeheyming** [google/closure-library#339]
My customer has filed a bug where firefox won't allow me to drag and drop.
I verified with my version: firefox 31.0 that drag and drop was not firing the dragEnd event.

I traced the bug down to this variable:
goog.fx.Dragger.HAS_SET_CAPTURE_ =
    // IE and Gecko after 1.9.3 has setCapture
    // WebKit does not yet: https://bugs.webkit.org/show_bug.cgi?id=27330
    goog.userAgent.IE ||
    goog.userAgent.GECKO && goog.userAgent.isVersionOrHigher('1.9.3');

this variable is set to "true", which causes
goog.fx.Dragger.prototype.setupDragHandlers to evaluate useCapture = false.

This causes the endDrag event to get fired after other mouse event handlers that I have installed.

If I manually change useCapture to true, the endDrag event is being correctly called.

I have tested that the events fire in the correct order if I manually set the HAS_SET_CAPTURE_ flag to false.

So I guess the question I'm asking is, can we have a way for maybe the abstractdraggroup.js class configure when you want to capture mouse events for a dragger?  Or am I totally misunderstanding things?  I'd rather not have to create my own instance of a dragger and override the setupDragHandlers function.  That feels like I'm "doing it wrong"

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
