### ISSUE TITLE
'goog.i18n.NumberFormatSymbols_es_AR' contains incorrect currency symbol

### ISSUE THREAD

**Issue by jeffbcross** [google/closure-library#341]
Because es_AR uses the default es numberSymbols object, it is getting the Euro symbol as its currency symbol, whereas it should be $. Related to https://github.com/angular/angular.js/pull/8606 and https://github.com/angular/angular.js/issues/8583

**Comment by joeltine** [comment]
Duplicate of https://github.com/google/closure-library/issues/327
