### ISSUE TITLE
NativeMessagingTransport causes Chrome to log errors when PEER_HOSTNAME configuration field is set

### ISSUE THREAD

**Issue by parker** [google/closure-library#349]
### What steps will reproduce the problem?
Chrome logs "Failed to execute 'postMessage' on 'DOMWindow'" when using XPC and NativeMessagingTransport if a PEER_HOSTNAME configuration field is set to something other than the local page's domain.

These errors do not prevent the component from functioning, but are an eye sore in the Chrome console.

*How to reproduce:*
* Add the following line of code to [xpcdemo.js](https://github.com/google/closure-library/blob/fb35d5232edef340dd9a7c6e479556829d0fa452/closure/goog/demos/xpc/xpcdemo.js#L83) to set PEER_HOSTNAME 
```
cfg[goog.net.xpc.CfgFields.PEER_HOSTNAME] = pollUri.getScheme() + "://" + pollUri.getDomain();
```
* load goog/demos/xpc/index.html in Chrome specifying an alternative domain using the `peerdomain` url parameter.
For example: `http://host1.com/path/to/closure/demos/xpc/index.html?peerdomain=host2.com`
* Open the Chrome console and see the security errors being logged

As I understand it, the peer hostname should always be set to something other than the default ("*") for security reasons.

In digging into this, I've found the reason for the errors to be the following:
* the load event of the peer iframe is triggered before its domain is updated to the peer hostname
** For example, if you inspect the peer iframe at the time this error occurs, its `location.href` will be "about:blank" and its `document.domain` will not be the peer domain. 
* After the iframe actually loads the peer domain, everything works as expected without any errors.

### What is the expected output? What do you see instead?
expected: No errors in the Chrome console.
result: "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://host2.com') does not match the recipient window's origin ('http://host1.com')."

### What version of the product are you using? On what operating system?
Mac OS X - Chrome 37.0.2062.94

**Comment by joeltine** [comment]
This might've been fixed in Chrome as I can't repro the warning.
