### ISSUE TITLE
goog.events.KeyHandler not dispatching event for ESC on Windows IE 11 or Firefox 30

### ISSUE THREAD

**Issue by kvanberendonck** [google/closure-library#359]
goog.events.KeyHandler not dispatching event for ESC on Windows IE 11 or Firefox 30.

But it's working perfectly on Chrome. Tried in both capture and non capture mode. Other keys work brilliantly across all the browsers.

**Comment by joeltine** [comment]
No response.

**Comment by kvanberendonck** [comment]
We have been using a workaround for some time on the ESC key.

For some reason we recently had to amend this workaround to include the ENTER key under Internet Explorer (not EDGE, and not other versions) only.
