### ISSUE TITLE
goog.global problem after complie

### ISSUE THREAD

**Issue by oceanjack** [google/closure-library#361]
goog.global is not equal to window after complie. In IE9, the 'this' in anonymous function is not window. So it takes some problems in google closure. when it complied. it will create some anonymous function, and goog.global is in this anonymous function. So, goog.global = this is not windwo. TT

**Comment by codyebberson** [comment]
I think this could be resolved as a documentation bug.  The [FAQ](https://github.com/google/closure-compiler/wiki/FAQ) suggested this example:
```
--output_wrapper=(function(){%output%})();
```
... which does not preserve "this" in strict mode.

I just updated it to this:
```
--output_wrapper=(function(){%output%}).call(window);
```
... which fixed my build.

**Comment by MatrixFrog** [comment]
Looks like you already made the change on that wiki page; thanks!
