### ISSUE TITLE
goog.net.Websocket onclose callback remains after calling close() without network connectivity

### ISSUE THREAD

**Issue by rcfox** [google/closure-library#362]
In normal operation, when the client websocket calls close(), it starts a closing handshake and eventually the onclose callback is called. http://www.w3.org/TR/2011/WD-websockets-20110419/#dom-websocket-close

In the situation where network connectivity is lost, and the client notices before the websocket does (lack of heartbeat responses, etc), it seems logical to call close(), and then attempt to reopen the connection. However, upon re-establishing connectivity, the closing handshake will finish and the onclose callback will be triggered while the websocket is trying to establish a new connection.

I'm not sure what your philosophy is exactly, but since you're wrapping the websocket API, it seems like it should be excusable to slightly violate the spec and skip the closing handshake: unregister the callback, close the websocket and then call the callback directly. It would appear to the user that everything is behaving normally, but there would be no waiting for the handshake to finish.

Alternatively, you could prevent trying to open a new connection during the closing handshake. Users would have to create a new Websocket instance in order to connect and that might avoid the problem above. This would mean that two sockets are unusable by other things now though, instead of just one.

**Comment by joeltine** [comment]
I don't think this is behavior we want to support, but I may not be understanding your proposal. It'd be much easier to review it in code form. If you feel like this would be an improvement, create a PR and re-open this issue.
