### ISSUE TITLE
Migrating code from py script to compiler.jar

### ISSUE THREAD

**Issue by sterpe** [google/closure-library#370]
So I'm having a hard time understanding how to generate equivalent output when migrating my code off the py script

`../closure-library/closure/bin/build/closurebuilder.py --root=../closure-library/ --root=./ --namespace="foo.bar" --output_mode=compiled --compiler_jar=/usr/local/bin/closure-compiler/compiler.jar --compiler_flags="--compilation_level=ADVANCED_OPTIMIZATIONS"`

Creates my goog.provided() namespace and goog.exportProperty() and goog.exportSymbol() are replaced with the appropriate exportation _code_.

Everything is great.

But I am unclear how to make this work using a combination of command line options directly to the compiler and there doesn't seem to be any documentation on this migration?

I keep running into the problem that `goog.exportProperty()` and `goog.exportSymbol` are being minified themselves to `goog.x()` & `goog.y()` rather than being evaluated.

i.e.:
var f={}... //goog.provide('foo') was processed
...
...
....
goog.k("foo",f);goog.j(f,"bar",f.g);  //!?

Been trying something like this:

`googcc --js lib/foo.js --compilation_level ADVANCED_OPTIMIZATIONS  --closure_entry_point foo.bar --manage_closure_dependencies --process_closure_primitives`

The lack of documentation on this migration feels like a bug.

**Comment by joeltine** [comment]
Relevant docs @ https://github.com/google/closure-compiler/wiki/Manage-Closure-Dependencies
