### ISSUE TITLE
Closure not founds 

### ISSUE THREAD

**Issue by podion** [google/closure-library#375]
In this post https://developers.google.com/blockly/hacking/closure it said ( Once you have the Closure files, place them next to Blocky's root directory and ensure that the directory is named closure-library. This is the directory structure you want:) but in the blocky_test.html the file is named ( <script type="text/javascript" src="../../closure-library-read-only/closure/goog/base.js"></script>)

**Comment by Ubehebe** [comment]
[Closure Library Discuss](https://groups.google.com/forum/#!forum/closure-library-discuss) is a better place for this discussion.
