### ISSUE TITLE
Run tests automatically on Travis

### ISSUE THREAD

**Issue by MatrixFrog** [google/closure-library#379]
It would be really great to run all the tests on Travis, for every pull request. Currently we just build the code using the HEAD of the closure-compiler. I discovered that [Travis can run tests in Firefox using Karma](http://karma-runner.github.io/0.12/plus/travis.html) so if we can make our tests Karma-compatible (I have no idea if that would be easy or hard to do) then we can run them on Travis, at least in one browser.

**Comment by joeltine** [comment]
Finally done in https://github.com/google/closure-library/pull/528!
