### ISSUE TITLE
Compiler warnings in htmlsanitizer

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#38]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=595

**Comment by joeltine** [comment]
This *should* be fixed in https://github.com/google/closure-library/commit/31359fa3304a066b58c254fc73240c290cf35ead. Re-open if you're still having this issue.
