### ISSUE TITLE
Closure doesn't have an HTTP method enumeration

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#39]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=591

**Comment by joeltine** [comment]
Creating an enum for HTTP verbs doesn't add much value. These verbs never change and creating an enum would be redundant, e.g., "GET: 'GET'". What *is* useful, however, is groupings based on semantic meaning of the verbs. E.g, https://github.com/google/closure-library/blob/master/closure/goog/net/xhrio.js#L245
