### ISSUE TITLE
goog.define() fails to 'define' when using output_wrapper with closure compiler.

### ISSUE THREAD

**Issue by jarabek** [google/closure-library#393]
I recently upgraded the closure library & compiler in my project after a very long hiatus, and since the upgrade I am unable to produce a working compiled JS file (uncompiled works fine).

The problem appears to be caused by the output wrapper preventing goog.define() from correctly defining variables (I'm using the following output wrapper: (function(){%output%})();, which I think is pretty standard).  I've spent some time in the debugger I think I've narrowed down the problem to the exportsPath_ method, which is called by goog.define().

    goog.exportPath_ = function(name, opt_object, opt_objectToExportTo) {
        var parts = name.split('.');
        var cur = opt_objectToExportTo || goog.global;

        if (!(parts[0] in cur) && cur.execScript) {
            cur.execScript('var ' + parts[0]);
        }

        for (var part; parts.length && (part = parts.shift()); ) {
            if (!parts.length && goog.isDef(opt_object)) {
                // last part and we have an object; use it
                cur[part] = opt_object;
            } else if (cur[part]) {
                cur = cur[part];
            } else {
                cur = cur[part] = {};
            }
        }
    };

When a variable is specified with goog.define, (ex. goog.define("goog.LOCALE", "en");)  it is looking to define that variable on 'cur' which in this case is goog.global, which is the window object.  
However, the 'goog' that it should be looking at is the one inside the closure (because all of this code is wrapped in an anonymous function), and because it is not looking at the right 'goog' object, it creates a new one on the window object.  So at the end of the day, this leaves you with two goog objects, anything that is explicitly defined within the closure (ex. goog.foo = 123;), will be defined in the closure, and anything defined with goog.define(), will be defined on window.goog, and this is causing a bunch of down stream problems due to missing and undefined variables.  

I'm sure it's possible that I am just using the output wrapper incorrectly, but I thought I would post here on the off chance that this is a legitimate issue.

**Comment by MatrixFrog** [comment]
I think we saw a similar issue in a Google-internal project recently, and the fix was something like

`--output_wrapper='(function() { %output% }).call(this)'`

which ensures that `this` inside the function is the global object. `goog.global` gets set by `goog.global = this;` so that also ensures that `goog.global` is set correctly. We should definitely document this better.

**Comment by jarabek** [comment]
Unfortunately, that didn't do the trick.  When I use your output_wrapper, goog.global is the global window object, which is the same as it was when I was using my original wrapper.  So this still results in the case where anything that is defined with goog.define() is being added to the global window object, and anything defined directly on the 'goog' object in the closure stays within the closure.  

Is it the intention that goog.define() is supposed to be globally scoping these variables?  Because I am using a wrapper to avoid having variable collisions, but it seems like goog.define() is explicitly trying to circumvent that.

Thanks,
Chris

**Comment by MatrixFrog** [comment]
Okay, I understand now. Yes, I think it generally assumes that `goog` is the same as `window.goog`. I don't think we have a solution for this unfortunately. The `--rename_prefix_namespace` may be helpful here but to be honest I'm not entirely familiar with the details of what that does.

**Comment by jarabek** [comment]
I went looking for the --rename_prefix_namespace flag and couldn't find it.  Turns out that my compiler.jar didn't get updated correctly when I did my upgrade.  I grabbed the latest compiler, and everything works as expected, no runtime errors, no namespace pollution.

Thanks a lot for your help.

**Comment by MatrixFrog** [comment]
Oh cool. That seems to happen a lot (old compiler versions get cached in various places that we don't control) so it's always good to double-check :)
