### ISSUE TITLE
Closure Library build breaks with the newest compiler.

### ISSUE THREAD

**Issue by koto** [google/closure-library#395]
Due to [this commit](https://github.com/google/closure-compiler/commit/6a3dbf38f561217c79d3900c179bdbdad76f5fac) Closure Library build now breaks with e.g.:

```
lib/closure-library/closure/goog/functions/functions.js:130: ERROR - Bad type annotation. type not recognized due to syntax error
 * @return {function(...[?]):T} A new function.
```

This problem has been fixed internally already, so just a MOE sync is needed.

**Comment by concavelenz** [comment]
Is this still pending?

**Comment by MatrixFrog** [comment]
@Ubehebe did you want to do a MOE push now that https://github.com/google/closure-library/pull/391 is merged? If not, I'll probably have time to do one next week.

**Comment by Ubehebe** [comment]
@MatrixFrog I've got a push ready to go. @nanaze wanted me to hold off until the next compiler release, but if the library's already broken, there's nothing to lose. WDYT?

**Comment by MatrixFrog** [comment]
Good point. I say go for it :)

FWIW the last compiler release was about a month ago so we can probably do one next week.

**Comment by Ubehebe** [comment]
@koto please close this issue if the library builds at HEAD for you now.

**Comment by koto** [comment]
Works OK, thanks!
