### ISSUE TITLE
goog.userAgent.VERSION is empty on IE 11

### ISSUE THREAD

**Issue by tehbelinda** [google/closure-library#399]
Which means that goog.userAgent.isVersionOrHigher doesn't correctly detect version 11 on IE

This affects other things like goog.net.ImageLoader, which relies on goog.userAgent.isVersionOrHigher to listen to the correct LOAD vs READY_STATE_CHANGE event.

```
goog.net.ImageLoader.IMAGE_LOAD_EVENTS_ = [
  goog.userAgent.IE && !goog.userAgent.isVersionOrHigher('11') ?
      goog.net.EventType.READY_STATE_CHANGE :
      goog.events.EventType.LOAD,
  goog.net.EventType.ABORT,
  goog.net.EventType.ERROR
];
```

As a temporary workaround, goog.userAgent.isDocumentModeOrHigher(11) seems to work

**Comment by AceMood** [comment]
Does isDocumentModeOrHigher works in IE11 with a 7,8,9,10 doc mode settings?

**Comment by joeltine** [comment]
I'm not seeing this. When I emulate an IE11 UA, goog.userAgent.VERSION is 11. See https://jsfiddle.net/2mjc800g/13/. Please provide a repro case and I'll re-open.
