### ISSUE TITLE
addEventListener has wrong type

### ISSUE THREAD

**Issue by kvanberendonck** [google/closure-library#400]
There is no way to add a well typed event listener using `window.addEventListener` if the event allows the user to return a string.

One such event that does this is `onbeforeunload` which lets you return a prompt message ...

**Comment by Ubehebe** [comment]
@kvanberendonck How should we change it?

**Comment by kvanberendonck** [comment]
Just chuck a `|string` to the end of it would fix it up, but be less safe for all the other events.

**Comment by Ubehebe** [comment]
@kvanberendonck Are you referring to [goog.events.EventTarget#addEventListener](https://github.com/google/closure-library/blob/master/closure/goog/events/eventtarget.js#L150)? It's deprecated, so there's little reason to change it.

**Comment by kvanberendonck** [comment]
I was referring to the native addEventListener ....

**Comment by Ubehebe** [comment]
[This](https://github.com/google/closure-compiler/blob/master/externs/w3c_event.js#L38) is the file you want to change, but it's part of the [Closure Compiler project](https://github.com/google/closure-compiler), not the Library.

**Comment by kvanberendonck** [comment]
Ok, thanks.
