### ISSUE TITLE
treescan.py not follows symbolic link

### ISSUE THREAD

**Issue by smallsmallwolf** [google/closure-library#406]
https://github.com/google/closure-library/blob/master/closure/bin/build/treescan.py#L60

Hello Nathan:

I found `treescan.py` not follows symbolic links, and I add the third parameter `followlinks=True`, this option was added in Python 2.6, its works.
```python
for dirpath, dirnames, filenames in os.walk(root, onerror=OnError, followlinks=True):
```
Why not follows symbolic? For compatibility?

**Comment by joeltine** [comment]
Hi, I'd like to make this change, but to add your change I'll need you to sign the CLA. Please follow the instructions at https://github.com/google/closure-library/blob/master/CONTRIBUTING

**Comment by joeltine** [comment]
I'll re-open once there's a CLA.
