### ISSUE TITLE
nodejs v0.12.0 (bootstrap)

### ISSUE THREAD

**Issue by kuzmisin** [google/closure-library#411]
in OSX nodejs v0.12.0,  after **require('bootstrap/nodejs.js')** I'm getting:

```
  vm.Script.runInThisContext.call(
                            ^
TypeError: Cannot read property 'call' of undefined
    at nodeGlobalRequire (/.../closure/goog/bootstrap/nodejs.js:70:29)
    at Object.<anonymous> (/.../closure/goog/bootstrap/nodejs.js:78:1)
```

looks like **vm.Script.runInThisContext** no more exists, but **vm.runInThisContext**
possible fix:
```
// Declared here so it can be used to require base.js
function nodeGlobalRequire(file) {
  var runInThisContextFn = vm.runInThisContext ? vm.runInThisContext : vm.Script.runInThisContext;
  runInThisContextFn.call(global, fs.readFileSync(file), file);
}
```

**Comment by MatrixFrog** [comment]
I don't think this has anything to do with closure-library. Filed on wrong project?

**Comment by nicks** [comment]
@MatrixFrog closure-library has a node.js shim layer. the path to it is in the bug report?

**Comment by nicks** [comment]
I submitted a fix for this at https://github.com/google/closure-library/pull/413. I have no idea why the author used vm.Script.runInThisContext instead of vm.runInThisContext, maybe it was a node v0.11 thing

**Comment by kuzmisin** [comment]
thanks (ok for nodejs v0.10.29, v0.12.0)

**Comment by MatrixFrog** [comment]
#413 is merged so re-closing.
