### ISSUE TITLE
goog.ui.DatePicker allows selection of dates in other months when ShowOtherMonths is false

### ISSUE THREAD

**Issue by illandril** [google/closure-library#415]
When ShowOtherMonths is off for goog.ui.DatePicker, the numbers for the dates in other months is hidden, but you can still select them by clicking on the blank spot where the date would show.

**Comment by joeltine** [comment]
goog.ui is considered only in maintenance mode for serious issues. For a work around, you can just apply a similar fix that the PR was attempting to-do.  E.g.,

``` javascript
datepicker.setShowOtherMonths(false);
datepicker.setUserSelectableDataRange(
    goog.date.DateRange.thisMonth(datepicker.getDate()));
```
