### ISSUE TITLE
[feature request] bower support

### ISSUE THREAD

**Issue by AliMD** [google/closure-library#421]
Could you please add official support of bower to easy add closure-library to any project ?
something like `bower install closure-library`
thank you in advance

**Comment by concavelenz** [comment]
What is required for this? is something you can contribute?

**Comment by AliMD** [comment]
why not ? easyer install, fast access, bower is popular, bla bla ...

**Comment by AliMD** [comment]
@concavelenz 
why not ? easyer install, fast access, bower is popular, bla bla ...

**Comment by teppeis** [comment]
@concavelenz bower requires bower.json and git tag.
http://bower.io/docs/creating-packages/

If closure-library publish git tag, I can contribute about bower.json.

**Comment by concavelenz** [comment]
You are asking for regularly tagged releases?

**Comment by teppeis** [comment]
@concavelenz yes, tagged releases required to support for bower.
but it needs changing the current release flow and now it's TBD in the previous discussion #368.
Incidentally to start tagged release, it may be good to register CL with bower.

**Comment by nanaze** [comment]
@wibblymat and @paulirish are both Googlers and Bower team members. perhaps they can chime in. Sorry, but we're largely unfamiliar with Bower.

**Comment by paulirish** [comment]
@AliMD are you up for maintaining the bower package of closure on https://github.com/components ?

If so, that would be best.

**Comment by AliMD** [comment]
Hmmm
@paulirish thank you
Is any problem with bower ?!
Component is good but bower is more popular
And by the way could you please add tag versions
Thank you

**Comment by paulirish** [comment]
@AliMD components github org is used for Bower to maintain distributable packages... (like a dist folder)

(it has nothing to do with the Component package manager)

I don't see any tags either in closure. Looks like its just a matter of using latest on master (which is how we do things at Google)

@AliMD if you want to maintain something in https://github.com/components i'll set you up.

**Comment by AliMD** [comment]
@paulirish
I know it, OK I will make it
thank you for invitation

**Comment by nanaze** [comment]
Does Closure's "require what you use" model map well to Bower?

**Comment by paulirish** [comment]
Bower just gets the files on your machine. It's pretty basic.

I don't know how well it integrates with npm+browserify or jspm+system.js

But that's mostly what you'd be asking.

**Comment by AliMD** [comment]
@nanaze (excuse me paul)
Bower is not package provide for backbend or node
It's just for front end
And you can easily use for download and update js/vendor project
And don't have any relation with npm+browserify
Use can easily hosy your files contain bower files with browserify or access files with npm ...
I don't understand your question clear

**Comment by concavelenz** [comment]
If we were to tag versions, it would be something that was based on the day:

20150331.0.0

**Comment by paulirish** [comment]
​Day-based tags makes sense, yeah.

Don't worry about for now.  Once we have a reliable package maintainer then
we can sort out that side. :)

**Comment by AliMD** [comment]
Done (https://github.com/components/closure-library)
Please check the issues and continue there
Thank you
