### ISSUE TITLE
`goog.dom.getDocumentScroll` always returns 0 for a scrollTop (y coordinate) in IE on Windows Mobile 

### ISSUE THREAD

**Issue by manakor** [google/closure-library#422]
Here's how to simulate it:
 1. Create a huge container inside `document.body`, that huge so you can scroll the page right/bottom;
 2. Append something to that container, so it's not empty;
 3. Add `goog.events.EventType.SCROLL` event listener to a `window` object and debug `goog.dom.getDocumentScroll()` value inside a handler ([source code snippet](http://paste.ofcode.org/8UPsP3hiLsSnrSavYkDvLa));
 4. Open sample HTML page that loads JavaScript doing all the above in *IE11 browser on Windows Mobile* and start scrolling the page down/up (vertically), so scroll event handler is fired.

When debugging `goog.math.Coordinate` which is returned by `goog.dom.getDocumentScroll()`, you'll see that Y coordinate value is always 0.

However, when scrolling the page horizontally, X coordinate value is changing without an issue.<br /> This proves that the issue is only in identifying Y coordinate.

*Getting the issue on Windows Phone Prestigio and Nokia Lumia, both with Windows&reg; Phone 8.1 OS on IE11 browser.*

**Comment by manakor** [comment]
Just tried to simulate on IE10/11 Desktop browsers on Windows 7, issue is not presented, proving its mobile-only nature.

**Comment by joeltine** [comment]
What Doctype are you using? Any chance it's related to http://stackoverflow.com/questions/4815283/using-doctype-let-scrolltop-return-0-why.

**Comment by joeltine** [comment]
NVM, just saw your commit comment using HTML5 DocType.

**Comment by joeltine** [comment]
See comment in https://github.com/google/closure-library/pull/423.
