### ISSUE TITLE
goog.net.XhrIo.shouldUseXhr2Timeout_ may return the falsy result

### ISSUE THREAD

**Issue by AceMood** [google/closure-library#426]
As you can see, the code only check for Internet Explorer, but Chrome 38.0+ has support xhr2 level timeout property and ontimeout callback.
I test it on MAC OS with chrome.

**Comment by AceMood** [comment]
Safari6 also support it

**Comment by joeltine** [comment]
Support table for timeout: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Browser_Compatibility

**Comment by joeltine** [comment]
Feel free to create a PR.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
