### ISSUE TITLE
Cut off weekday bug in goog.date.getWeekNumber when it is 0 (goog.date.weekDay.MON)

### ISSUE THREAD

**Issue by blueoctopus** [google/closure-library#427]
The following call is expected to return `52`, but instead it returns `1`:

```javascript
goog.date.getWeekNumber(2015, 0, 1, goog.date.weekDay.MON, goog.date.weekDay.FRI);
```

The bug is in this line:

```javascript
  // Default to Thursday for cut off as per ISO 8601.
  var cutoff = opt_weekDay || goog.date.weekDay.THU;
```

`cutoff` should only default to Thursday when opt_weekDay is `undefined`, not when it's `0`.

A workaround that I was able to find (without reimplementing the whole function again) is replacing `goog.date.weekDay.MON` with `7`:

```javascript
var cutoffWeekDay = goog.date.weekDay.MON;
goog.date.getWeekNumber(2015, 0, 1, cutoffWeekDay || 7, goog.date.weekDay.FRI);
```

This will return `52`, as expected.

Because of this, it will be nice if you can keep supporting `7` as a cutoff value to mean Monday for `opt_weekDay` after patching this function.

**Comment by joeltine** [comment]
Fixed in https://github.com/google/closure-library/commit/59ef41bd24014cddaf96c5ce549b8ab7fed61744#diff-59ad00690c3488039024368101b23393
