### ISSUE TITLE
[suggested feature] idiomatic closure way to use requestAnimationFrame

### ISSUE THREAD

**Issue by dillonforrest** [google/closure-library#428]
Hi all! I discovered the closure library and am learning more and more about it due to picking up clojurescript recently. AWESOME WORK!! :D Seriously cool stuff!!

I noticed there's currently no way to leverage `requestAnimationFrame` inside the closure library. How would you feel about adding it to the library?

I'd be happy to contribute and submit a pull request. The implementation I have in mind is basically copying it from React ([cross-browser requestAnimationFrame](https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/vendor/core/nativeRequestAnimationFrame.js), and also a [polyfill](https://github.com/facebook/react/blob/2aeb8a2a6beb00617a4217f7f8284924fa2ad819/src/vendor/core/requestAnimationFrame.js) basically the same as you have already, so should reuse with existing code). It's a pretty straightforward PR from what I can tell so far.

The main questions I have are:

1. Is there a reason why this doesn't exist already in the closure library? Am I missing some context? o__O
2. If you'd like it to be added, are there opinions about how its api should function? The same, or extending it?
3. Do you have any implementation suggestions?

Thanks for your time! Either way, looking forward to learning more about this library as I keep digging into it. :+1:

**Comment by concavelenz** [comment]
If you look for requestAnimationFrame in the library you should fine the
existing work? Or did you want to change something?

**Comment by dillonforrest** [comment]
Hi, I think we're on different pages right now, as I believe I'm totally missing the mark with this issue. Thanks for clarifying that it's already there!

Initially I thought `requestAnimationFrame` wasn't in the closure library at all. I just did a more thorough search of the code and found this: https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/async/animationdelay.js#L248

This is the only area of the closure library where I see `requestAnimationFrame` created for cross-browser compatibility, but it's a private method.

Is there value in creating a separate function? Maybe `goog.async.requestAnimationFrame`? I'm not sure if it'd be best in `async`, `dom`, `fx`, or some other area.

I found myself wanting to call `requestAnimationFrame` directly, but didn't see it in the closure api, so this issue is about adding it to the api. :)

**Comment by concavelenz** [comment]
See also:

https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/dom/animationframe/polyfill.js#L33

**Comment by dillonforrest** [comment]
Cool, thanks! Does that mean I'd have to include `goog.dom.animationFrame.polyfill` just so I can use `requestAnimationFrame`? Is that the intended usage?

**Comment by dillonforrest** [comment]
Hey there @concavelenz , just want to check in again to hear your thoughts. What's the intended idiomatic way for closure users to call `requestAnimationFrame`?

**Comment by joeltine** [comment]
The libraries in [goog/dom/animationframe](https://github.com/google/closure-library/tree/eb26f425dbd99a70d2955d8fcc892f2fd0178acb/closure/goog/dom/animationframe) are for this purpose.
