### ISSUE TITLE
goog.pubsub throws Errors if you dispose during publish

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#43]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=584

**Comment by joeltine** [comment]
Can't merge the fix if I wanted to, no CLA from author. That said, this use case is pretty obscure. No one has complained in > 2 years about it, and, AFAICT, very few ppl actually dispose pubsub anyway.
