### ISSUE TITLE
goog.ui.Control.IeMouseEventSequenceSimulator_ lacks base method call in constructor.

### ISSUE THREAD

**Issue by ama-ch** [google/closure-library#430]
The class `goog.ui.Control.IeMouseEventSequenceSimulator_` inherits `goog.Disposable`. But it doesn't call base method in its constructor.

So below example throws an error.

http://jsbin.com/qojadu/1/edit?html,js,output
```js
goog.define('goog.Disposable.MONITORING_MODE',
    goog.Disposable.MonitoringMode.PERMANENT);
goog.userAgent.IE = true;
var c = new goog.ui.Control();
c.render();
c.dispose();
```

Running result:

```
Uncaught Error: [object Object] did not call the goog.Disposable base constructor or was disposed of after a clearUndisposedObjects call
```

**Comment by concavelenz** [comment]
Do you want to send a pull request?  See:
https://github.com/google/closure-library/blob/master/CONTRIBUTING

**Comment by ama-ch** [comment]
OK, I'll prepare it.

**Comment by ama-ch** [comment]
I've sent a pull request, thank you.
