### ISSUE TITLE
Sha256.update throws 'message must be string or array' when message is a Uint8Array

### ISSUE THREAD

**Issue by 4xrsJCr9** [google/closure-library#432]
The `goog.isArray` call at [goog.crypt.Sha2.prototype.update](https://github.com/google/closure-library/blob/2012c5372fdb02ce9531cf4b2561b05e3ce2ab39/closure/goog/crypt/sha2.js#L248) returns false.

`goog.isArray` returns false because the typeof a Uint8Array is 'object' and it is not considered an instance of Array.

Using chromium Version 41.0.2272.89 (64-bit) on Linux.

**Comment by joeltine** [comment]
Huh, that should probably be replaced with goog.isArrayLike
