### ISSUE TITLE
goog.module loading should support NodeJS override

### ISSUE THREAD

**Issue by rconnamacher** [google/closure-library#439]
goog.modules are loaded using XMLHttpRequest -- which NodeJS doesn't support. The NodeJS bootstrapper should be able to override this with a Node-based implementation.

A similar method is used to support loading goog.packages in Node.

**Comment by concavelenz** [comment]
Please reopen if the current node bootstrap doesn't work for you:
https://github.com/google/closure-library/blob/master/closure/goog/bootstrap/nodejs.js
