### ISSUE TITLE
Current project version and versions history

### ISSUE THREAD

**Issue by AliMD** [google/closure-library#441]
Could you please explain to me
1. What's the current project version and versions history ?
2. What's your version structure and is it compatible with semver.org ?

I need this information to make [components/closure-library](https://github.com/components/closure-library)
Thank you in advance

**Comment by nanaze** [comment]
> 1. What's the current project version and versions history ?
> 2. What's your version structure

At present, there is no versioning other than commit hashes. Google always works from head. Thus, the current version is listed here: https://github.com/google/closure-library

For example, the current version is 8294cd7b14902717d2f1cab53d80025721d75a83

> is it compatible with semver.org ?

As far as I understand it, semver requires an X.Y.Z versioning. Clearly we don't have that format.

**Comment by AliMD** [comment]
I think you need change this way if you want to Match with open sources world.
