### ISSUE TITLE
WHITESPACE_ONLY incompatible with output_wrapper

### ISSUE THREAD

**Issue by bpicolo** [google/closure-library#446]
Looks like the folks at clojurescript noticed this too, so <a href="http://dev.clojure.org/jira/browse/CLJS-510">here's a link to their relevant thread.</a>

The short description:
When compiling with an output wrapper that wraps output in a closure, in WHITESPACE_ONLY mode, you'll get errors such as "Cannot set property 'Unicode' of undefined" (goog.string.Unicode, in this case, doesn't function). Simple/Advanced optimizations seem to work as intended.

an output wrapper that's just --output_wrapper="%output%" won't cause this problem, wrapping in a closure seems to be the issue, i.e. --output_wrapper="(function(){%output%})()"

May or may not be intended behavior, but I didn't see an issue for it so figure it couldn't hurt to submit.

**Comment by concavelenz** [comment]
This is a compiler, not a library issue.
