### ISSUE TITLE
Parse error in goog.ui.PopupMenu

### ISSUE THREAD

**Issue by koto** [google/closure-library#453]
There is a merge conflict here: 

https://github.com/google/closure-library/blob/master/closure/goog/ui/popupmenu.js#L330

Do you plan to have a CI? It's possible for Travis to catch those bugs by e.g. compiling the library. Take a look at our configuration: https://github.com/google/end-to-end/blob/master/.travis.yml

**Comment by teppeis** [comment]
@koto this repo already has CI and the conflict was caught: https://travis-ci.org/google/closure-library/builds/59411093, but ignored...

**Comment by nanaze** [comment]
fixed
