### ISSUE TITLE
Duplicate variable name in goog.ui.popupmenu annotaions. (57bdfe0)

### ISSUE THREAD

**Issue by gumm** [google/closure-library#457]
The Compiler warns with the following when using goog.ui.popupmenu:
This is for the library as per commit number 57bdfe0 of Apr 25, 2015

closure-library/closure/goog/ui/popupmenu.js:573: WARNING - Bad type annotation. duplicate variable name "e"
 * @param {!goog.events.BrowserEvent} e The browser event.
                                      ^

closure-library/closure/goog/ui/popupmenu.js:593: WARNING - Bad type annotation. duplicate variable name "e"
 * @param {?goog.events.BrowserEvent} e The browser event.
                                      ^

**Comment by koto** [comment]
This seems to be because of merging error in the given file:

```
/**
 * Handles a KEYDOWN browser event on one of the popup targets.
 * @param {goog.events.BrowserEvent} e The browser event.
 * @param {!goog.events.BrowserEvent} e The browser event.
 * @private
 */
```

The @param line was modified recently in the internal version.

**Comment by koto** [comment]
This commit is a culprit: https://github.com/google/closure-library/commit/39651a984888d5386e8b7bcec58d357d9e127fcb

**Comment by concavelenz** [comment]
verify fixed.
