### ISSUE TITLE
Bug inside goog.dom.getPixelRatio

### ISSUE THREAD

**Issue by mashify** [google/closure-library#459]
[`var isFirefoxMobile = goog.userAgent.GECKO && goog.userAgent.MOBILE;`](https://github.com/google/closure-library/blob/master/closure/goog/dom/dom.js#L2181)
will always result into false because [`goog.userAgent.GECKO`](https://github.com/google/closure-library/blob/master/closure/goog/labs/useragent/engine.js#L68) will only be true if `goog.userAgent.WEBKIT` is false and [`goog.userAgent.MOBILE`](https://github.com/google/closure-library/blob/master/closure/goog/useragent/useragent.js#L155) will only be true if `goog.userAgent.WEBKIT` is true

**Comment by joeltine** [comment]
Looks like the bug mentioned in the comment above the "isFirefoxMobile" line has since been fixed. I have a fix internally that just removes isFirefoxMobile altogether.

**Comment by mashify** [comment]
@joeltine sorry but I can't see how it got fixed. I can't see any change.

**Comment by joeltine** [comment]
It's only internally. The fix will make it into master likely early next week.

**Comment by mashify** [comment]
@joeltine ohh I see that's great. So the mentioned bug (the reason why that line was added) will not be taken care of at all. Is that correct?

**Comment by joeltine** [comment]
It's for a 2 year old version of FF, so I'm not too worried. AFAIK, FF16+ has auto-update and this bug is from a specific version of FF22.

**Comment by mashify** [comment]
Alright. I thought so I just did not want to file a pull request removing support for a certain browser version on a certain device. Thanks for caring about it though.
