### ISSUE TITLE
XhrIo Progress Events

### ISSUE THREAD

**Issue by sfnelson** [google/closure-library#465]
Commit cbed1691c558fe35aa533fc6a1e0b647fb426fb9 added support for progress events in XhrIO, then 2d963940fc0b8f6beca6f3554b4b00d1eca14e9b reverted that change.

Is there any plan to reintroduce these changes?

Progress events would be very nice to have. Is there a better alternative?

**Comment by joeltine** [comment]
Had some trouble reverting the rollback internally. The blockers have been removed and we're going to try to get this change in next week. Stay tuned.

**Comment by JulianLeviston** [comment]
@joeltine can you reference this issue in the change when it drops? (Or put another way, I'd like a way for github to notify me when this drops so I can encourage clojurescript authors to depend on a later version of google closure library) :)

**Comment by joeltine** [comment]
Still more blockers on this internally :(. It's being worked on though. May take longer than we thought.

**Comment by joeltine** [comment]
Progress events are now supported as of https://github.com/google/closure-library/commit/42162f3d5ccbb2f59e3c8a9780ec2924e919dd91

**Comment by joeltine** [comment]
Had to rollback this one twice internally, but I think we finally got it to stick with https://github.com/google/closure-library/commit/1e0c8103ae97a0e568e63bf5d6906597b25a4544

**Comment by GetContented** [comment]
Thanks so much @joeltine  :)
