### ISSUE TITLE
Modify goog.structs.Map/Set to use native Map/Set if available.

### ISSUE THREAD

**Issue by freshp86** [google/closure-library#469]
Native Map/Set implementations have been on stable Chrome/Firefox for a while now (according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Browser_compatibility).

Are there any plans to make goog.structs.Set/Map use the native ones, when available and fall back to a JS implementation when not available?

**Comment by freshp86** [comment]
No response after 20 days...

Does this at least sound like a good idea? Are there any known major blockers on doing this? I was contemplating starting to investigate, but don't want to waste time if this is a no-go.

**Comment by joeltine** [comment]
Sorry for slow response. Until recently, the open-source Closure has only had volunteer based upkeep.

I'd hold off on this for now. We're still working out our plans for ES6 features and how to safely roll them out. It may involve modifying existing data structures (like goog.structs.Map) or even writing entirely new ones. Also, goog.structs.Map is one of the most commonly used libraries internally. There's a lot of room for breakages here, and a significant refactor would be hard to coordinate.
