### ISSUE TITLE
Web site doesn't work with chrome

### ISSUE THREAD

**Issue by benzen** [google/closure-library#471]
Hi,
I've noticed that the new website doesn't work
http://google.github.io/closure-library/api/

But when using opera, everything is ok.

I've got this error:
 Uncaught TypeError: Cannot read property 'length' of null  dossier.js:80

**Comment by JensVerneuer** [comment]
works for me @ Chrome Version 42.0.2311.135 (64-bit)

**Comment by benzen** [comment]
I'got the exact same 42.0.2311.135 (64-bit)
On a Macbook air.

Weird, do you have the error I,ve mentioned?

**Comment by myphysicslab** [comment]
works for me on Macbook Pro OS X 10.9.5,  Chrome  43.0.2357.65 (64-bit)

**Comment by vvvvalvalval** [comment]
Same think, on Chrome v43.0.2357.124 and Macbook Air 2015 with OSX 10.10.3.

**Comment by concavelenz** [comment]
On the mailing list this was a chome extension causing problems.  If you can reproduce this without extension, please reopen.
