### ISSUE TITLE
fireKeySequence (from goog.testing.events) does not work with Firefox 37

### ISSUE THREAD

**Issue by mathieulegrand** [google/closure-library#473]
When executing `fireKeySequence` on a new editable div for a `event.keyCode`, Google Chrome and Apple Safari will insert the keystroke in the div while Firefox will not.

Tested in both Firefox 37 and Firefox 38 - vs - Chrome 45 and Safari 8

**Comment by joeltine** [comment]
Can you provide a repro case with https://jsfiddle.net/2mjc800g/?

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
