### ISSUE TITLE
prototypical primitive values are stored in instances instead in prototype

### ISSUE THREAD

**Issue by ThFischer** [google/closure-library#477]
In multiple places of the library primitive prototypical values of members are defined on the instances instead on the prototype. This increases the memory footprint for every instance without any reason.
For example the [goog.Promise](https://github.com/google/closure-library/blob/master/closure/goog/promise/promise.js) constructor defines these properties:
```javascript
this.state_ = goog.Promise.State_.PENDING;
  this.result_ = undefined;
  this.parent_ = null;
  this.callbackEntries_ = null;
  this.callbackEntriesTail_ = null;
  this.executing_ = false;
```
... but it could be defined in the prototype:
```javascript
goog.object.extend(goog.Promise.prototype, ({
  state_: goog.Promise.State_.PENDING,
  result_: undefined,
  parent_:null,
  callbackEntries_: null,
  callbackEntriesTail_: null,
  executing_: false,
}));
```
One exception to not do so is in cases where performance requirements are more important than memory consumption (because prototype member lookups could are slower than for instance members)

**Comment by concavelenz** [comment]
Defining values on the prototype causes the class shape to change when the values are set, which cause both memory and performance issues in modern VMs.  Best practice is to only set final values on the prototype and set mutable values in the constructor.
