### ISSUE TITLE
Generated documentation is broken

### ISSUE THREAD

**Issue by metrofun** [google/closure-library#478]
Closure Library website (i.e. https://developers.google.com/closure/library/) points to http://google.github.io/closure-library/api/, which is empty

**Comment by concavelenz** [comment]
Looks live to me.

**Comment by metrofun** [comment]
For me the page is empty :
![screen shot 2015-06-06 at 1 02 28 pm](https://cloud.githubusercontent.com/assets/946519/8019393/1438d8dc-0c4c-11e5-8edc-9e44ac59c868.png)

**Comment by concavelenz** [comment]
Do you see any errors in the dev console?  What browser are you using?  It
looks fine in Chrome for me.

**Comment by concavelenz** [comment]
Click on the arrow to the right of "types" for some reason it is starting
collapsed for you.

**Comment by metrofun** [comment]
@concavelenz It's empty even when uncollapsed and there is a console error 
![screen shot 2015-06-09 at 10 20 46 am](https://cloud.githubusercontent.com/assets/946519/8053448/0b39ccae-0e91-11e5-93b9-61cf889883a9.png)

**Comment by metrofun** [comment]
Damn :) That's one of my extensions, which breaks it. In a private mode everything works fine.

**Comment by concavelenz** [comment]
Thanks for tracking it down.  Extensions injecting corrupting code is a
continous source of problems for sites that don't have CSP that protect
against it.

**Comment by metrofun** [comment]
Surprisingly, the reason was http://benvanik.github.io/WebGL-Inspector/
