### ISSUE TITLE
HTML in jsdoc is not escaped on closure-library.googlecode.com

### ISSUE THREAD

**Issue by diracdeltas** [google/closure-library#481]
If a jsdoc comment includes HTML tags, such as in https://github.com/google/closure-library/blob/eb26f425dbd99a70d2955d8fcc892f2fd0178acb/closure/goog/string/string.js#L498, it will be rendered as HTML on the auto-generated closure library documentation page, ex: http://closure-library.googlecode.com/git-history/docs/namespace_goog_string.html.

**Comment by nicks** [comment]
I believe the JavaDoc/JSDoc standard explicitly does not escape HTML. The real solution is that the comment here should use entities (e.g., `&lt;`)

**Comment by concavelenz** [comment]
googlecode does is obsolete.

http://google.github.io/closure-library/api/
