### ISSUE TITLE
style.scrollIntoContainerView works poorly with document.body

### ISSUE THREAD

**Issue by adelespinasse** [google/closure-library#484]
I know someone already tried to address this in [this change](https://github.com/google/closure-library/commit/af7c5dfffbe6fdf60b94eb28f4af38a4a6a7ee3a), but I think it's still not working as it should.

For one thing, in Chrome, it seems to work when the container is document.body, but not when it's document.documentElement. In Firefox, the opposite is true. See the following demo:

http://aldel.com/scrollintoview.html

Clicking works in Chrome but not Firefox, and shift-clicking works in Firefox but not Chrome.

Also, the intent of scrollIntoContainerView is to scroll the container as little as possible to get the element into view. If the element is already in the middle of the container, it shouldn't move at all. In the above demo, you can see that instead the element always ends up at the lower right corner, no matter where it was before clicking. (For comparison, see [this demo](http://aldel.com/scrollintoviewel.html), where the container is a div. I believe this one behaves as expected.)

(Note: for the above demo I set the width and height of the html and body elements to 100%. It doesn't seem to work at all otherwise. If there are different CSS settings that work better, I'd like to know.)

I might take a stab at fixing this if no one else wants to claim responsibility.

**Comment by joeltine** [comment]
Thanks. I'm going to see if the author of the change you linked is interested in giving it a look. Otherwise, if you're still interested, I'd definitely be willing to review a PR. I'll update this issue when I hear back.

**Comment by adelespinasse** [comment]
I actually have a [partially working fix in my fork](https://github.com/google/closure-library/compare/master...adelespinasse:master). That is, it seems to work for my purposes, but it isn't well tested, and I think it could be cleaner. I don't feel like it's ready for a PR. I'd need a better understanding of what tests might need to be updated, and how to run them, to begin with.

If someone else wants to work with my changes, or start over, that would be great. Or if you tell me how to get started on dealing with tests, I can hopefully get to it at some point.

**Comment by joeltine** [comment]
Turns out the original author is on paternity leave for 2 weeks. If you want to take a stab at fixing this, the associated test file is [style_test.js](https://github.com/google/closure-library/blob/master/closure/goog/style/style_test.js) in the same dir. To run the test, just open the style_test.html file (also in the same dir) in a browser. Otherwise, this will probably just sit until he gets back.
