### ISSUE TITLE
empty objects output for empty modules

### ISSUE THREAD

**Issue by kaaaahhhhnnnn** [google/closure-library#487]
I have some module files that don't actually export anything (they are doing things like adding event listeners to a page), but in order to include them I'm defining them as modules:

```js
goog.module('foo');
document.addEvent(...)
```

then in my top-level js file I have:

```js
goog.module('site');
goog.require('foo');
```

Each of these "empty" modules produces empty object at the end of the total output.  The last bit of my compiled file is:

```js
({});({});({});({});
```

**Comment by concavelenz** [comment]
How are you running the compiler? I don't see that in my simple test case.

http://closure-compiler-debugger.appspot.com/#input0%3Dgoog.module('foo')%253B%26input1%3Dgoog.module('bar')%253B%250Agoog.require('foo')%253B%26conformanceConfig%26externs%26refasterjs-template%26includeDefaultExterns%3D1%26CHECK_SYMBOLS%3D1%26CHECK_TYPES%3D1%26CLOSURE_PASS%3D1%26FOLD_CONSTANTS%3D1%26INLINE_VARIABLES%3D1%26MISSING_PROPERTIES%3D1%26REMOVE_UNUSED_VARIABLES%3D1

**Comment by concavelenz** [comment]
no response from author
