### ISSUE TITLE
positionAtAnchor breaking on scroll

### ISSUE THREAD

**Issue by nathan-lapinski** [google/closure-library#488]
Hello, 
We are using the goog.positioning library in our code.
We are seeing an issue in our software where we are using positionAtAnchor to reposition an iframe over a video element. However, what we are seeing is that the iframe does not stay properly positioned over the video element when we scroll the page. We've researched this issue as best we can, but it seems to boil down to an issue with positionAtAnchor not working properly on scroll.

We've noted that commenting out the line:
if (visibleBox) {
rect.intersection(goog.math.Rect.createFromBox(visibleBox));
}
in goog.positioning.getVisiblePart seems to fix the issue.

**Comment by joeltine** [comment]
Can you create a simplified repro case? Here's a template you can use: https://jsfiddle.net/2mjc800g/.

**Comment by joeltine** [comment]
Please re-open with a repro example.
