### ISSUE TITLE
Incorrect da-DK time format

### ISSUE THREAD

**Issue by tinwaisi** [google/closure-library#494]
For da-DK, the time format should use ":" instead of "." 

Current format: "HH.mm.ss",
It should be "HH:mm:ss"

**Comment by joeltine** [comment]
We generate these symbols directly from [CLDR](http://cldr.unicode.org/). Please file a change request directly against them at http://cldr.unicode.org/index/bug-reports. Once changed, it will eventually make its way into Closure.

**Comment by joeltine** [comment]
FYI: CLDR already has a ticket on this issue: http://unicode.org/cldr/trac/ticket/8417
