### ISSUE TITLE
XhrIo reporting incorrect error message on server missing

### ISSUE THREAD

**Issue by JulianLeviston** [google/closure-library#495]
When making an XhrIo request to a server before I've started it up (ie nothing answering on the port), the XhrIo object runs the ERROR callback with an object that has ERROR code 6 in it, which is "Http response at 400 or 500 level" and an HTTP code of 0.

According to https://google.github.io/closure-library/source/closure/goog/net/errorcode.js I'd expect the ERROR code to be maybe OFFLINE: 9 or TIMEOUT: 8 possibly? Is there an good way to determine the difference between these things? Should I just use the "0" response HTTP code as indication that there is no server there?

I'm using ClojureScript, which is using a somewhat old version, as can be seen here:
https://github.com/clojure/clojurescript/blob/master/project.clj

Version 0.0-20150505-021ed5b3 of Google closure library
and version v20150609 of Google closure.

I couldn't find an easy way to determine whether this has been an issue since and fixed or not.

**Comment by joeltine** [comment]
I think HTTP_ERROR (code 6) is an appropriate response for this case. It's used for non-successful HTTP response codes, which 0 falls under. The debug text you mentioned could probably be improved.

OFFLINE is when there is no network connectivity, and TIMEOUT is when there is literally a timeout.

**Comment by JulianLeviston** [comment]
Except that this happens when the server isn't online. In other words, there was no response code, because there was no response.

Could you please elucidate the difference between the error codes? What does offline mean, for example? It'd be quite lovely if the documentation explained the semamtics a bit better.

Meantime I'll run some tests of the 5 different things my codebase needs (by setting up contexts for each) and just use that to determine the error states.

Thanks! :)

**Comment by joeltine** [comment]
It's not about the server, it's about the client. OFFLINE means the *client* doesn't have internet access.

**Comment by JulianLeviston** [comment]
AH! Ok... would it be possible to explain this somewhere? Say in some docs? Just a few lines explaining what each means? Sorry if this is a hassle. Awesome thankyou :)

**Comment by joeltine** [comment]
The errorcode.js comments already do explain this.  If you think you can improve them, create a PR and I'll take a look.

**Comment by JulianLeviston** [comment]
Ah ok. I think the thing that threw me was this:
"The Http response returned a non-successful http status code." because it doesn't explain what the "Http response" is, and I naturally assumed it was the ordinary meaning of HTTP resonse, which would be something that came from the server.

In reading the online documentation, it seems to suggest that the code should return -1 if the server hasn't started sending its response.

        The HTTP status code sent by the server (200 for success, 404 if the URL wasn't found, etc.) if the
        server has started sending its response. If the server has not started responding, returns -1.

https://developers.google.com/closure/library/docs/xhrio

In order to change the error code comments, I'd need to understand what they do. I currently don't.

It's fine though, if you're happy that they're good, then I'm happy :) I had a problem understanding, but let's just treat it as an aberration, in lieu of my actually being able to make any kind of modification to the docs because of my not understanding how the code functions.

Thanks very much.
