### ISSUE TITLE
InputHandler with space as separator inserts two spaces

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#5]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=634

**Comment by adam-rocska** [comment]
@joeltine Is this issue lost? 
When I click the link to the original issue, I get redirected to an unrelated pull request with which the only common point is the id in this url, and the id of the unrelated pull request.

**Comment by shicks** [comment]
It would appear to be the case.  Looks like Google shut down code.google.com and just redirect to the same-id issues in GitHub, which is obviously wrong.

FWIW, it's still available on [archive.org](https://web.archive.org/web/20140918030542/https://code.google.com/p/closure-library/issues/detail?id=634)

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
