### ISSUE TITLE
goog.math.Integer: Division of large numbers causes an infinite loop

### ISSUE THREAD

**Issue by gfredericks** [google/closure-library#500]
As best I can tell, any number bigger than 10^309 is unprintable.

Printing a number requires serializing to base 10 which requires dividing by 1,000,000.

On dividing any such large number, the division algorithm creates an approximate answer using doubles.

The maximum representable double is somewheres around 10^308.

And so one way or another the division algorithm gets into an infinite loop.

**Comment by gfredericks** [comment]
The commit I referenced (above) from my own fork seems to fix this problem (based on my extensive tests), but might not be the best performance-wise.

It ought to be strictly better than the current situation though, since it actually works and will be a fast check for not-very-large numbers.

Should I make a PR out of that, or wait for someone to do something with more of an eye on performance?

**Comment by joeltine** [comment]
I'm not too familiar with this code. Trying to see if I can get someone more appropriate to take a look.

**Comment by joeltine** [comment]
Unfortunately, I couldn't find any volunteers, so you're going to force me to brush up on my bit arithmetic now :).

It'd be very helpful if you could provide a breakdown explanation of what your algorithm does, and also provide some example test cases that demonstrate the issue.

**Comment by gfredericks** [comment]
I will absolutely do that. I suppose I may as well upgrade this to a pull request while I'm putting in that effort.

**Comment by gfredericks** [comment]
Okay I created #518, which has inline comments in the algorithm, and includes a regression test that can double as code to reproduce the problem. Let me know if there's anything I've left unaddressed.
