### ISSUE TITLE
In a fresh Google Closure editor, a bug will "arbitrarily" delete text. This tends to happen when the user first starts using that editor.

### ISSUE THREAD

**Issue by fbsolo** [google/closure-library#502]
1)&nbsp;&nbsp;&nbsp;Open a fresh <a href="http://www.closurecheatsheet.com/demos/demos/editor/editor.html">Closure Library editor</a>.

2)&nbsp;&nbsp;&nbsp;Click "Set Field Contents"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a)&nbsp;&nbsp;&nbsp;The lower box text physically moves to the upper box. The lower box text disappears

3)&nbsp;&nbsp;&nbsp;Click the upper box text
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a)&nbsp;&nbsp;&nbsp;The upper box text disappears

<a href="https://github.com/google/closure-library/pull/468">PR #468</a> fixes this.

**Comment by def14nt** [comment]
@fbsolo wtf is that link

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
