### ISSUE TITLE
Refactor Closure Library to npm

### ISSUE THREAD

**Issue by steida** [google/closure-library#511]
Seriously, the world needs that. Bying able to consume Closure Library goodness without base and compiler would be awesome.

**Comment by concavelenz** [comment]
We would like to build a roadmap to ES6 modules but the world isn't ready for that yet and we aren't going to go to something else before that.

**Comment by steida** [comment]
World ready is. Check https://babeljs.io

**Comment by concavelenz** [comment]
No browser implements es6 modules.

**Comment by steida** [comment]
JavaScript is compiled language now. I don't know why you guys are not eating your dog food - Traceur. Or use Babel.

**Comment by disjukr** [comment]
+1

**Comment by joeltine** [comment]
You can use Closure with Node/NPM right now. Look at [the README](https://github.com/google/closure-library/blob/master/README.md).

We don't promise support for any particular library though. It's possible some are making references to web-only constructs and will break. That said, the libs that are obviously not web-based are fine (e.g., `goog.crypt`).
