### ISSUE TITLE
goog.require() when type is only used as a parameter

### ISSUE THREAD

**Issue by mtsgrd** [google/closure-library#521]
I noticed a few compiler warnings when compiling against https://github.com/google/closure-library/commit/bbb7ae68f9a90a46c6c7a43cfdb896e9439dfe2f:
```
...
closure-library/closure/goog/ui/ac/autocomplete.js:767: WARNING - Bad type annotation. Unknown type goog.ui.ac.RenderOptions
 * @param {(boolean|goog.ui.ac.RenderOptions)=} opt_options If true,
                    ^

closure-library/closure/goog/ui/ac/autocomplete.js:788: WARNING - Bad type annotation. Unknown type goog.ui.ac.RenderOptions
 * @param {(boolean|goog.ui.ac.RenderOptions)=} opt_options If true,
                    ^

closure-library/closure/goog/ui/ac/autocomplete.js:798: WARNING - Property getPreserveHilited never defined on optionsObj
      optionsObj ? optionsObj.getPreserveHilited() : opt_options;
                              ^

closure-library/closure/goog/ui/ac/autocomplete.js:820: WARNING - Property getAutoHilite never defined on optionsObj
  if (optionsObj && optionsObj.getAutoHilite() !== undefined) {
                               ^

closure-library/closure/goog/ui/ac/autocomplete.js:821: WARNING - Property getAutoHilite never defined on optionsObj
    autoHilite = optionsObj.getAutoHilite();
                            ^

0 error(s), 5 warning(s), 97.7% typed
closure-library/closure/bin/build/closurebuilder.py: JavaScript compilation succeeded.
```
 
This is because `goog.ui.ac.AutoComplete` has at least one function that takes a parameter of type `goog.ui.ac.RenderOptions`. Fixjsstyle removes `goog.require('goog.ui.ac.RenderOptions')` if added to `autocomplete.js`. Is fixjsstyle correct in removing it or what is the intended solution to this?

**Comment by concavelenz** [comment]
If you include the deps.js file, it will provide the forward declarations
needed to avoid these warnings.

We need to move the wiki over but it is mentioned here:
https://code.google.com/p/closure-library/wiki/FrequentlyAskedQuestions#When_I_compile_with_type-checking_on,_I_get_warnings_about_
"

**Comment by mtsgrd** [comment]
Thanks @concavelenz, that makes perfect sense.

**Comment by joeltine** [comment]
On a side note, I added a blurb about this in the Closure Builder documentation today: https://developers.google.com/closure/library/docs/closurebuilder?hl=en#additional-flags-to-closure-compiler
