### ISSUE TITLE
Releases closure-library to bower.js

### ISSUE THREAD

**Issue by lygstate** [google/closure-library#525]

**Comment by joeltine** [comment]
You're going to have to be more specific. What exactly is this issue? I'm assuming bower is http://bower.io/?

**Comment by lygstate** [comment]
Yes, I means http://bower.io/search/

I want to install closure library with 
`bower install closure-library`
 or something alike

**Comment by joeltine** [comment]
Sorry, I don't think this is something we want to maintain at this time. Even if we did, it would never be prioritized as there's so much else higher in the priority list.
