### ISSUE TITLE
goog.base incompatible with strict mode

### ISSUE THREAD

**Issue by supersteves** [google/closure-library#537]
I'm using Closure Compiler in WHITESPACE_ONLY mode and hence goog.base from Closure Library is appearing in my output.  I'm using ECMASCRIPT6_STRICT output language, since I'm in "development mode" (non-transpiled) and this is my source level.

Using Chrome Canary, this fails because of the first line inside goog.base:
``` javascript
goog.base = function(me, opt_methodName, var_args) {
  var caller = arguments.callee.caller;
```
The error seen in Canary is:
```
Uncaught TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
```

The workaround is to turn off STRICT mode, but then that prevents me using let, const, etc. outside of strict mode (i.e. goog.module) functions.

Also see https://github.com/google/closure-compiler/issues/611

**Comment by dferrara19** [comment]
Use the new base method (defined in goog.inherit)

MyClass = fn() {
  MyClass.base(this, 'constructor')
}

Replace 'constructor' with the base method name you want to call else where.

**Comment by supersteves** [comment]
Thanks. My bad, it was my code calling the old goog.base, not Closure Compiler transpiled outputs.
