### ISSUE TITLE
Fix documentation regarding use of goog/deps.js in compiled mode

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#54]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=565

**Comment by joeltine** [comment]
For posterity, taken from the original issue: 

The thing to note here is that it's not always necessary to include deps.js in your compilation. It's only necessary when you happen to be using a Closure library that references a type that is not goog.require'd in the file. This can happen when a file references a particular type in annotations in comments (e.g., @type {Foo}), but never actually uses the type directly (e.g., invoking via "new" or referencing its statics). For an explanation on why we do this see the thread: https://code.google.com/p/closure-library/issues/detail?id=401.

**Comment by joeltine** [comment]
Updated closurebuilder docs to mention deps.js https://developers.google.com/closure/library/docs/closurebuilder?hl=en#additional-flags-to-closure-compiler
