### ISSUE TITLE
A close button of goog.ui.Dialog does not work on touch device.

### ISSUE THREAD

**Issue by m-kojima** [google/closure-library#541]
You can confirm on the demo site with touch devices. (e.g. iPad)
https://google.github.io/closure-library/source/closure/goog/demos/

If the title bar is draggable, CLICK event does not fired.
Perhaps the cause is, preventDefault is called in goog.fx.Dragger#startDrag.

**Comment by joeltine** [comment]
@ziegs Can you label this? If valid, this seems pretty blatantly broken, but you know priority better than I.

**Comment by kjin** [comment]
Unfortunately, I can't reproduce this. If someone runs into this issue still, please comment on this issue or open a new one.
