### ISSUE TITLE
goog.userAgent.flash version detection fails on IE11 for flash player version 11

### ISSUE THREAD

**Issue by smudgeface** [google/closure-library#542]
See this similar issue with swfobject:
https://github.com/swfobject/swfobject/issues/30

This fiddle shows the issue (when run on IE11 with flash player version 11.X)
http://jsfiddle.net/noyobo/hEPb7/11/show/

Basically, IE11 has introduced support for navigator.plugins, but older versions of Flash player do not play nicely. The fallback mechanism (using ActiveXObject) should be preferred if the UA is IE, rather than simply relying on the existence of navigator.plugins.

**Comment by joeltine** [comment]
PRs welcome

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
