### ISSUE TITLE
goog.fx.Dragger marked as struct but inherits from a non-struct.

### ISSUE THREAD

**Issue by tjcegodk** [google/closure-library#552]
First of all this isn't valid [according to the documentation for the struct tag](https://github.com/google/closure-compiler/wiki/@struct-and-@dict-Annotations) since structs must only ever extend structs, but it also means the compiler cannot probably enforce the struct limitations (so the code is misleading) and that the compiler prints warnings in every project that use the dragger, including the one I am working on.

**Comment by joeltine** [comment]
@concavelenz thoughts on this?

**Comment by concavelenz** [comment]
tl;dr  use a recent compiler release

The subclass are allowed to be struct and are type checked more strictly that the non-struct super classes.  However as any subclass of a "struct" is also "struct" the superclass can't be marked struct without also fixing all the subclasses.  This makes it difficult to mark the common base classes (Disposable, etc) as struct without breaking the world (we may do this some day but not yet).

The current and recent releases of the compiler don't warn about this:
https://groups.google.com/d/msg/closure-compiler-discuss/uIMiBxKxGB8/BKHZ3t62IwAJ
