### ISSUE TITLE
Expand browsers under test for CI

### ISSUE THREAD

**Issue by joeltine** [google/closure-library#554]
We definitely want:

MS Edge
Chrome latest
Chrome 28
IE8+
Safari 8
FF latest
Some Android/iOS coverage (??)

**Comment by joeltine** [comment]
Added the "standard" set in https://github.com/google/closure-library/pull/562. Will leave this issue open for enabling some of the non-standard ones (e.g., Edge, Chrome 28, Android, etc.).

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
