### ISSUE TITLE
Poll Sauce Labs for available VMs from Travis

### ISSUE THREAD

**Issue by joeltine** [google/closure-library#573]
Sauce Labs has a 10 min timeout queue for tests waiting to use a VM. Our tests take > 10 min to run, so if two suite invocations happen in parallel, the suite who starts last will fail.

To workaround it, use the Sauce Labs Rest API to check for # of VMs available before invoking tests. Periodically poll until VMs are available.

**Comment by 12wrigja** [comment]
Closing as we stopped using Sauce Labs for testing.
