### ISSUE TITLE
Is goog.ui deprecated? Does closure library offer an alternative?

### ISSUE THREAD

**Issue by jimbojetlag** [google/closure-library#581]
Looks like `goog.ui` being retired in Google. I know there is a lot of `goog.ui` still in production in Google, but it seems like new projects in Google do not consider using it anymore.

- Why is `goog.ui` not popular anymore?
- What should people who start a new project with closure library use to build ui?
- Is closure library going to support new means of developing ui?

**Comment by joeltine** [comment]
In the future, these questions should be directed to [closure-library-discuss](https://groups.google.com/forum/#!forum/closure-library-discuss).

> Why is goog.ui not popular anymore?

TL;DR frameworks came along that people preferred using and fit their use cases better.  

> What should people who start a new project with closure library use to build ui?

Polymer? Angular? Closure is purposely not opinionated on these decisions. The onus is on the developer to decide what's best for their project. 

> Is closure library going to support new means of developing ui?

No current plans.
