### ISSUE TITLE
Html5History and query parameter

### ISSUE THREAD

**Issue by bago2k4** [google/closure-library#582]
Hi,
if i'm on this url: /test?a=1 and i use setToken to move to /test?b=2 i get the url rewritten like this:
/test?b=2?a=1
how can i solve this?

Here is the code if you want to take a look:
https://github.com/open-company/open-company-web/blob/finances-component/src/open_company_web/router.cljs#L27

**Comment by joeltine** [comment]
Questions should be asked on the public group [closure-library-discuss](https://groups.google.com/forum/#!forum/closure-library-discuss).

**Comment by andrejewski** [comment]
For anyone looking for a solution, see here: https://gist.github.com/andrejewski/3887f205fd834eea1b506a908db76e38
