### ISSUE TITLE
goog.Uri resolve decodes query data

### ISSUE THREAD

**Issue by joeltine** [google/closure-library#585]
See https://github.com/google/closure-library/pull/434 for context

**Comment by joeltine** [comment]
@irock I ran all internal tests against this and there were multiple failures. As expected, people are relying on the encoding. We can leave this issue open to track the issue, but I'm not sure it's worth the effort to land the fix. I'd recommend just working around it in your code.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
