### ISSUE TITLE
how compile *.proto to *.pb.js and use proto2 on closure library

### ISSUE THREAD

**Issue by dockbiz** [google/closure-library#589]
My project used closure library and closure compile to build bundle js package (goog.require && goog.provide ).
* for comunicate client and server ,I selected protobuf protocol module (it's exist on closure library) but none of solution for **compile *.proto to  *.pb.js by using goog.provide() - require()*** 
like
[phonenumber.proto](https://github.com/googlei18n/libphonenumber/blob/master/resources/phonenumber.proto)
to 
 [phonenumber.pb.js](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumber.pb.js)
 Your project is provide document how to compile on 
[How compile project](https://github.com/googlei18n/libphonenumber/tree/master/javascript)
But i don't want to deep on java package file and complex dependent on xml

I want to see like
`` protoc -I ./phonecall ./phonecall.proto --java_out=phonecall ``
or 
`` protoc -I ./phonecall ./phonecall.proto --go_out=plugins:grpc:phonecall``

on comnamd line like other language

I and my team really interest on protobuf concept ,May be your little advide will help my team progress for using protobuf module and your project

Thank you for your advide

**Comment by hochhaus** [comment]
Closure-library does not include the necessary plugins to compile a *.proto file to *.pb.js. Some third-party projects have written this code though. See the following projects for a starters:

https://github.com/rethinkdb/protobuf-plugin-closure
https://github.com/samegoal/protoclosure

**Comment by dockbiz** [comment]
Thank you.So useful library
