### ISSUE TITLE
base64.decodeString gives inconsistent result across platforms

### ISSUE THREAD

**Issue by joth76** [google/closure-library#600]
Currently decodeString delegates to atob() on platforms that support it, when webSafe is not set:

    goog.crypt.base64.decodeString = function(input, opt_webSafe) {
      if (goog.crypt.base64.HAS_NATIVE_SUPPORT && !opt_webSafe) {
        return goog.global.atob(input);
      }
      return goog.crypt.byteArrayToString(
          goog.crypt.base64.decodeStringToByteArray(input, opt_webSafe));
    };

This has a number of compatibility issues / surprises:
- Whitespace:
  - atob() _should_ ignore whitespace on the input, but some implementations (i.e. IE) don't.
  - decodeStringToByteArray throws an Error on whitespace on input (but by same arguments as for btoa(), it probably should ignore all whitespace)
- WebSafe handling
  - passing opt_webSafe = true forces the use of the internal decodeStringToByteArray algorithm, that actually *ignores* the opt_webSafe parameter and will gracefully accept either encoding alphabet (websafe or conventional). Hence opt_webSafe is really a flag to "allow" webSafe alphabet,
  - omitting opt_webSafe (or passing false) actually translates to "either reject webSafe input, or tolerate it, depending on whether the platform has atob() or not".

**Comment by joth76** [comment]
Fixed in these two
https://github.com/google/closure-library/commit/f52663715cbf9507708fae9e1e9dfc5f58fb5847
https://github.com/google/closure-library/commit/f2a72dde7b0374ff8b81f6af2c559ad97badf5e3

**Comment by joeltine** [comment]
Thanks for all the work on this!
