### ISSUE TITLE
Passing opt_xmlHttpFactory to the XhrManager

### ISSUE THREAD

**Issue by Polooo2** [google/closure-library#605]
Hi,
is there a reason why it isnt possible to pass a xmlHttpFactor to the XhrManager like in xhrIo requests?

**Comment by shicks** [comment]
Aside from adding even more complexity to an already poor API, I don't know of a specific reason.  I'm hesitant to add yet another optional constructor argument to the already-excessive number of them, but if you can come up with a reasonable alternative that allows injecting a factory and doesn't break existing callers (I'm at a loss, here), we'd be open to pull requests.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
