### ISSUE TITLE
goog.isString broken when using advanced compilation

### ISSUE THREAD

**Issue by BradMclain** [google/closure-library#617]
Since commit 9389e14bb122d8c97674fbdcac49045bce8dcf3b compiling using the advanced setting breaks the usage of the `goog.isString` method. It is returning `undefined` instead of a boolean.

If I remove the usage of `goog.pubsub.PubSub` (the module which was updated in that commit) then the compilation works fine again.

I had a quick look through the commit changes but I can't see anything obvious that would be causing this.

**Comment by concavelenz** [comment]
Since this isn't generally true, you will need to provide exact reproduction steps.

**Comment by nicks** [comment]
If I had to take a shot in the dark, my guess is that your webpage is stomping on variables in the global scope, and that goog.isString coincidentally got renamed to one of the variable names you're stomping on. If you remove Pubsub, it would change the renaming slightly, and a different variable would get stomped on.

**Comment by BradMclain** [comment]
I will put some time towards trying to reproduce in an isolated environment. This should confirm whether the problem lies in the application code or not.

**Comment by BradMclain** [comment]
Apologies this does appear to be our fault. We had added google analytics and forgotten to add an external.

Thanks for your help.
