### ISSUE TITLE
ILikeArray

### ISSUE THREAD

**Issue by carlitux** [google/closure-library#618]
After upgrade the library I am getting this.

```bash
client/js/vendor/google-closure-library/closure/goog/object/object.js:241: WARNING - Bad type annotation. Unknown type IArrayLike
 * @param {...(string|number|!Array<number|string>|!IArrayLike<number|string>)}
```

On this line

https://github.com/google/closure-library/commit/af8b7e475e24845561a68ef0f26fe8c76eee76a2#diff-8425eeecbb066552faec86ef40d165c4R241

After updating the closure-compiler to master still getting same error... and linter doesn't have any update.

**Comment by concavelenz** [comment]
The IArrayLike is define in the closure-compiler master:  
https://github.com/google/closure-compiler/blob/master/externs/es3.js#L41

Seems like the issue is how you are running the compiler, or you have a custom set of externs that needs to be update.
