### ISSUE TITLE
Currency fractions for ja, kr locale

### ISSUE THREAD

**Issue by clichedmoog** [google/closure-library#636]
In Korea, and in Japan, currencies does not used with fractions normally.
The Currincies does not written usually 1,000₩ not 1,000.00₩ and 1,000¥ not 1,000.00¥.
Yes, there's no coins for the fractions.
Only for the exact calculation fractions used like 1,000.11₩, 1,000.00¥.
There's may be the standards for this https://en.wikipedia.org/wiki/ISO_4217#Active_codes
In closure/goog/i18n/currency.js file follows that.
But not in i18n/closure/numberSymbolsExt.js , see each CURRENCY_PATTERN.
for the simple view, see:
https://github.com/google/closure-library/search?utf8=%E2%9C%93&q=KRW
https://github.com/google/closure-library/search?utf8=%E2%9C%93&q=JPY
How about change the currency pattern with no fractions?

**Comment by concavelenz** [comment]
As noted at the top of the file, this is generated from the CLDR.  You need
to request the change there and then we can pick it up.

**Comment by clichedmoog** [comment]
Okay thank you.
