### ISSUE TITLE
ie9 bug that affects the goog.ui.SplitPane

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#64]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=547

**Comment by joeltine** [comment]
UI being in maintenance, this isn't worth the fix unless someone sends a PR.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
