### ISSUE TITLE
Looks like a type error in goog/events/listenermap.js

### ISSUE THREAD

**Issue by bpilot** [google/closure-library#649]
On line 173, ListenerMap.removeByKey() calls markAsRemoved() method on listener.

Because, according to the type annotation, this is ListenableKey, this should not work.

```js
goog.events.ListenerMap.prototype.removeByKey = function(listener) {
  var type = listener.type;
  if (!(type in this.listeners)) {
    return false;
  }

  var removed = goog.array.remove(this.listeners[type], listener);
  if (removed) {
    listener.markAsRemoved();  // Error.
    if (this.listeners[type].length == 0) {
      delete this.listeners[type];
      this.typeCount_--;
    }
  }
  return removed;
};
```

Shouldn't it call markAsRemoved on the matched Listener instead?

This is a fantastic library, just wondering about this. Thank you!

**Comment by shicks** [comment]
Good catch.  This looks like an issue that the current compiler's type inference lets go (it assumes that since `Listener` is an implementation of `ListenableKey`, that you probably know what you're doing), but the New Type Inference will snag on this.  Would you be up for putting together a pull request that adds a `goog.asserts.assertInstsanceof(listener, goog.events.Listener);` call before the `markAsRemoved()`, which should resolve this?

**Comment by bpilot** [comment]
Pull request is ready: https://github.com/google/closure-library/pull/663

Sorry for the delay, we were busy building new functionality with the Closure Library!

As an aside, what is the best resource to complement Closure learning besides Michael Bolin's book?

**Comment by Dominator008** [comment]
@bpilot
Google Developers pages on Closure: https://developers.google.com/closure/
Closure Library Wiki: https://github.com/google/closure-library/wiki
Closure Compiler Wiki: https://github.com/google/closure-compiler/wiki

**Comment by bpilot** [comment]
I won't be able to do the PR, but enjoyed the process anyway.

Closure is really helping us better structure our code, with better consistency, quality, and completeness than the stitch-together-garden-variety-of-github-repos approach.

**Comment by Dominator008** [comment]
@bpilot Can you sign the CLA at #663 so we can accept your contribution? Thanks.
