### ISSUE TITLE
Ratings inDocument_ property never set to true

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#65]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=546

**Comment by joeltine** [comment]
Have an internal fix for this.

**Comment by jimbojetlag** [comment]
What's the right way of calling the super class method? There are more than one way of doing this in the library, why is that this is not consistent?

@joeltine how does your way of `goog.ui.Ratings.base(this, 'enterDocument');` work with closure compiler advanced mode? Doesn't `enterDocument` method get renamed, while you are referencing to it via a string?

**Comment by joeltine** [comment]
>What's the right way of calling the super class method?

The way I did in the commit.

Based on [this comment in the compiler](https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/ProcessClosurePrimitives.java#L525), the `base` calls are special cased. They get re-written without the string literal method name.

**Comment by concavelenz** [comment]
@jimbojetlag that is correct, both goog.base and the "base" method get rewritten to something like:  class.superClass_.method(...)
