### ISSUE TITLE
XhrManager doesn't fire COMPLETE event after exhausting retries

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#66]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=545

**Comment by joeltine** [comment]
From original issue:

>In goog.net.XhrManager.prototype.handleComplete_:

>var request can be undefined if the request has been retried too many times.   The request is removed from this.requests_ in the retry_ method when the retry limit is reached; a subsequent completion state change will land in handleComplete_ with the request having already been disposed.  This can occur, for example, when network connectivity is lost or a remote server goes down.

>If the request variable is undefined, then the handleComplete_ method will throw an exception when it tries to check request.hasReachedMaxRetries().

>The fix is trivial:  Just check that request is defined before asking for request.hasReachedMaxRetries().  I believe you still want to send the COMPLETE event in this case; the rest of this method is already proof against request being undefined.

>For what it's worth:  handleError_ has exactly the same problem.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
