### ISSUE TITLE
goog.math.isFiniteNumber and 

### ISSUE THREAD

**Issue by fredj** [google/closure-library#661]
`goog.math.isFiniteNumber` is:
```javascript
/**
 * Returns whether the supplied number is finite and not NaN.
 * @param {number} num The number to test.
 * @return {boolean} Whether {@code num} is a finite number.
 */
goog.math.isFiniteNumber = function(num) {
  return isFinite(num) && !isNaN(num);
};
```

But according to the [ECMAScript 5.1 spec](http://www.ecma-international.org/ecma-262/5.1/#sec-15.1.2.5), `isFinite` already returns `false` if the agrument is `NaN`.

Is the `!isNaN(num)` test here for backward compatibility for old browsers?

**Comment by joeltine** [comment]
Just seems like an oversight in the original implementation to me. I'll try to create a change that removes `isNaN` and deprecates this method internally.

**Comment by concavelenz** [comment]
isFinite coerses unlike Number.isFinite

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite

isFinite(null) returns true.
