### ISSUE TITLE
closurebuilder.py error with --output_mode=script

### ISSUE THREAD

**Issue by ruszki** [google/closure-library#665]
Running closure/bin/build/closurebuilder.py script with 'script' output_mode raise an exception "can't concat bytes to str":

> ./library/closure-library-20160208/closure/bin/build/closurebuilder.py --root=library/closure-library-20160208/ --root=library/protobuf/ --root=protobuf --input=protobuf/reference.js --output_mode=script --output_file=js/closure.js
> ./library/closure-library-20160208/closure/bin/build/closurebuilder.py: Scanning paths...
> ./library/closure-library-20160208/closure/bin/build/closurebuilder.py: 1521 sources scanned.
> ./library/closure-library-20160208/closure/bin/build/closurebuilder.py: Building dependency tree..
> Traceback (most recent call last):
>   File "./library/closure-library-20160208/closure/bin/build/closurebuilder.py", line 287, in <module>
>     main()
>   File "./library/closure-library-20160208/closure/bin/build/closurebuilder.py", line 253, in main
>     out.write(src.encode('utf-8') + '\n')
> TypeError: can't concat bytes to str

There are several problems with this code part:

- str.encode() returns a bytearray to which string cannot be added this way
- out's write doesn't accept bytearrays

Closure library version: 20160208
Python version: 3.5.1

**Comment by joeltine** [comment]
This is likely a python 2 vs 3 issue. Using python 2.X should work until we
decide on a fix internally.

**Comment by ruszki** [comment]
Yes, I've checked with version 2.7.11. It worked without problems.
