### ISSUE TITLE
goog.Uri mangles form-urlencoded fragments

### ISSUE THREAD

**Issue by nicks** [google/closure-library#667]
Run the following code:

```
goog.Uri.parse('http://google.com/callback#state=x%3Dy').toString()
```

Expected result: `http://google.com/callback#state=x%3Dy`
Actual result: `http://google.com/callback#state=x=y`

AFAIK, form-urlencoded fragments are a relatively recent thing. They come up in the OAuth spec, see  https://tools.ietf.org/html/rfc6749#section-4.2.2, though there might be earlier instances. We found this bug because we were trying to use goog.Uri to parse Google OAuth login, and it totally broke.

I'm not sure what the best way to fix this is. We fixed it in our codebase by making fragment encoding and decoding inverses of each other (in goog.Uri, they are not exact inverses). You could also imagine some sort of FragmentData api analogous to QueryData.

**Comment by shicks** [comment]
Seems like it should be fixable even without a FragmentData API, no? Then again, I haven't look at goog.Uri recently...

**Comment by concavelenz** [comment]
Did you have a PR for this @nicks ?

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
