### ISSUE TITLE
Closure API reference web design

### ISSUE THREAD

**Issue by jart** [google/closure-library#668]
Is there any possible chance you guys would consider bringing back the [old design](https://closure-library.googlecode.com/git-history/docs/namespace_goog.html) for the closure library docs? I personally find the [new one](http://google.github.io/closure-library/api/namespace_goog.html) more difficult to use and navigate.

**Comment by jart** [comment]
If you can't bring the old design back, then I highly recommend changing the old docs on Google Code so they 301 redirect to the new docs. This is because the old docs are very out of date, yet they still dominate in the search results.

**Comment by concavelenz** [comment]
It is no longer possible to modify the Google Code site, we should shut it
down entirely.  The "redesign" of the docs was unintentional and a
side-effect of changing doc generation tools.    Was there something
specific about the old docs that you miss?

**Comment by jart** [comment]
- The menu being collapsed by default
- The shade of blue in the old docs was easier to read.
- I found this: "goog.dom.**flattenElement**(element) ⇒ Element | undefined" more readable than this: "**flattenElement(element)**"
- I'm not feeling the underlines on some of the section tags

Does this new tool give you a choice of design? I would be happy to review them and give you my 2 cents :dancer: 

Another example of really readable documentation is this: https://docs.python.org/2/library/datetime.html I think that the tool that makes that is sort of general purpose.

**Comment by Dominator008** [comment]
@jart [Dossier](https://github.com/jleyba/js-dossier) is the new tool.

**Comment by shicks** [comment]
I'd bet Jason Leyba would be open to contributions to make the generated documentation easier to read, and we'd certainly welcome any improvements we got here as a result!  I fully agree with your example that explicitly including the namespace and the return type is more readable, FWIW.

**Comment by jart** [comment]
I would consider chipping in some 20% time to make Dossier's output look slightly more fabulous. But before doing that, I would like to have a better understanding of what was wrong with the old tool? Why did Closure Library choose to migrate to Dossier? Why is Dossier hosted under Jason's personal account rather than Google?

**Comment by myphysicslab** [comment]
FWIW, I've been using Dossier on my own project and IT IS FANTASTIC.  Yes,
the choice of output is limited to what Jason has set up now, but I'll bet
that is malleable somehow (perhaps not yet easily).  What is so great about
Dossier is that it works directly with Closure Compiler based code, pretty
much as good as (or better) than the equivalent JavaDoc tools in the Java
world.

Note that the current Dossier outputs a somewhat different style than what
is seen in the Closure Library docs.  I also would like to make some
changes in the output, but that is subsidiary to having a tool that is able
to grok Closure Compiler code.

--ErikN

**Comment by shicks** [comment]
@jart We migrated away because the old documentation was built by a tool based on the original internal version of Kythe, but when they moved to open-source Kythe it became incompatible and so eventually we were no longer able to regenerate the docs.  The old tool was also completely unmaintained, so there were various bugs and I think it was pretty appealing to move to a tool that was actually being maintained.  I have no idea why it's in Jason's personal account, but presumably he's cleared it through all the appropriate channels (for comparison, Truth used to also be a "moonlighting" project hosted outside of Google).

**Comment by jart** [comment]
Well I'm glad I complained. I'm in the process of launching a brand new comprehensive JavaScript build system for Bazel. It's built on the Closure Tools, has cool stuff like PhantomJS testing, and is meant to make The Google Way™ simple and accessible to external developers. (Ping me for a link to the internal staging repo.)

Dossier appears to be well-written and is actively maintained by a Googler. So I'd like to integrate it in the Closure Rules as the recommended documentation generator. But this doesn't appear like it would be a simple thing to do.

Ideally, I would like to be able to download Dossier from Maven as a single jar that includes its dependencies. This is because each external dependency I add to Closure Rules incurs a social cost. Bazel forces the developer to not only maintain his own dependencies, but also the transitive dependencies of everything he uses. If integrating with Dossier carries the cost of twelve additional dependencies, then developers may be less inclined to use the Closure Rules.

I would also like to be able to configure Dossier with flags rather than JSON. Bazel build rules aren't really able to automate writing JSON.

Are these changes you would consider @jleyba?

**Comment by shicks** [comment]
We're working a lot on Bazel rules for JS internally, and so I'd be very
interested in seeing what you've got.  Once we figure out what we're doing
internally I'm hopeful that we can push some of it out as well.

It doesn't seem like writing JSON should be too hard - IIUC, you can pass
arbitrary dicts and arrays to Bazel macros (though not to rules) and it
should be pretty easy to stringify a reasonable input.  Though command-line
flags could certainly make things easier, too.

**Comment by jleyba** [comment]
The closure API docs are several versions behind on dossier. Here's an [example](http://seleniumhq.github.io/selenium/docs/api/javascript/) of what the latest version looks like. I'd gladly welcome contributions on the design front. For instance, I need to make the keyboard shortcuts more discoverable (/ focuses the search box, n toggles the nav menu)

I do have an open issue (jleyba/js-dossier#18) for supporting custom templates.

@shicks Dossier isn't a Google project - it has been cleared through the appropriate channels.

**Comment by concavelenz** [comment]
I'll work with @jleyba to pick up the latest.

**Comment by jart** [comment]
@jleyba That search functionality in the latest version seems to work *really well*. I like the material design. The only thing that might be problematic is a lot of clicks are required to find libraries when not using the search.

Is there any chance you'd be interested in making a build rule contribution to the https://github.com/bazelbuild/rules_closure project, adding support for Dossier? I think the project could benefit greatly from your documentation generator.

**Comment by pcj** [comment]
@jart Awhile back I wrote a custom closure compiler Document pass to teach myself the compiler.  Sample output is at https://developer.pubref.org/static/apidoc/global/closure/goog/ui/Component.html.  

It does not traverse the type system as faithfully as dossier, but IMHO is easier to grok.  At some point I'll probably work to incorporate the output with dossier, but you're welcome to refer to this output as an alternative rendering.

**Comment by jart** [comment]
@pcj Oh your documentation is quite beautiful. I would like it very much if Dossier produced output that looked more more similar to this.

**Comment by concavelenz** [comment]
We just use Dossier
