### ISSUE TITLE
goog.inherits JSDoc not rendering as intended

### ISSUE THREAD

**Issue by glennsimon** [google/closure-library#674]
Looking at the JSDoc for goog.inherits
https://google.github.io/closure-library/api/namespace_goog.html#inherits
There is HTML pre tag for the code example that doesn't render as intended.  The pre tag ends too soon.

I posted this as a bug on js-dossier and got a response that closure uses a version of js-dossier that is several revs behind, and that with the latest version the error is fixed.

Here is the JSDoc in the code (closure/goog/base.js):

<pre>
2204    /**
2205     * Inherit the prototype methods from one constructor into another.
2206     *
2207     * Usage:
2208     * &lt;pre&gt;
2209     * function ParentClass(a, b) { }
2210     * ParentClass.prototype.foo = function(a) { };
2211     *
2212     * function ChildClass(a, b, c) {
2213     *   ChildClass.base(this, 'constructor', a, b);
2214     * }
2215     * goog.inherits(ChildClass, ParentClass);
2216     *
2217     * var child = new ChildClass('a', 'b', 'see');
2218     * child.foo(); // This works.
2219     * &lt;/pre&gt;
2220     *
2221     * @param {!Function} childCtor Child class.
2222     * @param {!Function} parentCtor Parent class.
2223     */
</pre>

and here is how Chrome version 48.0.2564.116 m displays it:

<div id="inherits" class="function">
  <div><h3>inherits(<wbr>childCtor, parentCtor)
    <span class="codelink"><a href="source/closure/goog/base.js.src.html#l2224">code »</a></span></h3><p>Inherit the prototype methods from one constructor into another.</p><p>Usage: </p><pre> function ParentClass(a, b) { } ParentClass.prototype.foo = function(a) { };</pre><p>function ChildClass(a, b, c) {  ChildClass.base(this, 'constructor', a, b); } goog.inherits(ChildClass, ParentClass);</p><p>var child = new ChildClass('a', 'b', 'see'); child.foo(); // This works. </p><div><div class="fn-details"><div><b>Parameters</b></div><dl><dt>childCtor<code>Function</code></dt><dd><p>Child class.</p></dd><dt>parentCtor<code>Function</code></dt><dd><p>Parent class.</p></dd></dl></div></div></div></div>

**Comment by jleyba** [comment]
This was due to a bug in an earlier version of the doc generator. It should render correctly now:

https://google.github.io/closure-library/api/goog.html#inherits

**Comment by shicks** [comment]
This seems to be fixed and/or obsolete at this point.
