### ISSUE TITLE
XhrIo returns goog.net.HTTP_ERROR when it can't connect to the host

### ISSUE THREAD

**Issue by danielcompton** [google/closure-library#687]
When XhrIo cannot connect to a host, it returns a `goog.net.HTTP_ERROR` which is only meant to be returned when there is a non-successful HTTP status code. The description for this error is: `'Http response at 400 or 500 level'`, but no HTTP connection is ever able to be made.

Looking at the other [ErrorCode](http://google.github.io/closure-library/api/enum_goog_net_ErrorCode.html)'s available, I'm not sure if there is a better alternative however.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
