### ISSUE TITLE
API documentation missing

### ISSUE THREAD

**Issue by ducklord** [google/closure-library#688]
Your "Generated API Documentation" http://google.github.io/closure-library/api/ is all gone.

**Comment by Dominator008** [comment]
It's there for me.

**Comment by ducklord** [comment]
Funny. Works fine in Firefox. In Chrome Version 50.0.2661.26 beta (64-bit) i get `dossier.js:80 Uncaught TypeError: Cannot read property 'length' of null` in the console.

**Comment by Dominator008** [comment]
I'm running Chrome Version 51.0.2687.0 on Linux x86-64 and it's working for me. If you can reproduce it feel free to file an issue against [Dossier](https://github.com/jleyba/js-dossier/issues), the tool to build the API docs.

**Comment by ducklord** [comment]
Sure, i will do that.

**Comment by ducklord** [comment]
Just an update, problem found. Was my "WebGL Inspector" plugin, that for som reason was messing up script tags.
