### ISSUE TITLE
goog.structs.Map uses toString to define object identity

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#69]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=541

**Comment by joeltine** [comment]
The TL;DR here is that using "toString" on each key in a Map isn't as robust as it could be. Other alternatives could include using "===", a deep equals like goog.object.equals, or allowing a custom key equality function.

E.g.,

```
var key1 = function () { return 'key' }
var key2 = function () { return 'key' }

map.set(key1, 'foo');
map.set(key2, 'bar');

map .get(key1); // 'bar'
map .get(key2); // 'bar'
```

**Comment by vipref** [comment]
goog.structs.Map is deprecated in favor of ES6 Map.
