### ISSUE TITLE
Does GCL need an ECCN and if so, what is it?

### ISSUE THREAD

**Issue by aharui** [google/closure-library#690]
We would like to bundle GCL in an Apache Software Foundation product.  Someone has raised concerns about the files in closure/goog/crypt.  Do any of these files require an Export Control Classification Number?

**Comment by concavelenz** [comment]
I don't know how I would find out.

**Comment by aharui** [comment]
I would be surprised if Google does not have experts in ECCN rules and regulations.  If you read up on ECCN, it seems like serious stuff.  Apache Software Foundation projects are expected to conform.  I would think Google would want its open source projects to conform as well.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
