### ISSUE TITLE
Decimal separator for currency in korean language is should be comma

### ISSUE THREAD

**Issue by krish-ram** [google/closure-library#696]
**Do you want to request a feature or report a bug?**
Currently, the decimal separator for currency in korean language is .(dot). But this should be ,(comma). Please change this and update the angular_locale_ko_kr.js files. 
**
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (template: http://plnkr.co/edit/tpl:yBpEi4).**

Please set the locale to korean and use a currency filter. This will show you a currency with dot instead of comma.
Line no: 2170 - https://github.com/google/closure-library/blob/master/closure/goog/i18n/numberformatsymbols.js#L2170

**_
goog.i18n.NumberFormatSymbols_ko = {
  DECIMAL_SEP: '.',
.
.
.
}
_**

**What is the expected behavior?**
For korean language, the decimal separator should be comma and not dot.

**Comment by concavelenz** [comment]
As noted at the start of the file, it is autogenerated from the CLDR.  You need to wrong with them to update the expectations and then we will pick it up with the next update:

http://cldr.unicode.org/

If for some reason we don't match the version of the CLDR (v29 currently), feel free to reopen this issue.

**Comment by clichedmoog** [comment]
Even this is a closed issue but I should inform that decimal separator in ko is a dot.
I also commented in the angular.js repo
