### ISSUE TITLE
'Module ' + name + ' has been loaded incorrectly.' is missing info

### ISSUE THREAD

**Issue by johnjbarton** [google/closure-library#697]
I see an error message from:

``` javascript
  if (!goog.isInModuleLoader_()) {
    throw Error('Module ' + name + ' has been loaded incorrectly.');
  }
```

"incorrectly" does not help me. The test `goog.isInModuleLoader_()` probably means something to the module loader developer.  If they shared their knowledge with the user, the user would no longer gnash teeth, curse, search SO, read source with low expectation of enlightenment. Rather they would be enlightened directly by the error message.

**Comment by shicks** [comment]
This seems to have been addressed.
