### ISSUE TITLE
Unknown "this" in goog.partial

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-library#700]
https://github.com/google/closure-library/blob/master/closure/goog/base.js#L1895

`goog.parial` is causing warnings with the `unknownThis` conformance check.

**Comment by shicks** [comment]
Could we change its type to the following?

```js
/** @param {function(this: T, ...*): R} func
    @param {...*} var_args
    @return {function(this: T, ...*): R}
    @template T, R */
goog.partial = function(func, var_args) {};
```

This should fix the definition, but could introduce problems if callers have underlying type mismatches that were getting glossed over by the raw `Function`s before.  In the interim, we could keep the `@return` type as `{!Function}` and then fix callers in a second pass.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
