### ISSUE TITLE
promise/testsuiteadapter requires nonexistent package "promises_aplus_tests"

### ISSUE THREAD

**Issue by bendavis78** [google/closure-library#701]
See [closure/goog/promise/testsuiteadapter.js:33](https://github.com/google/closure-library/blob/25cb02899b9ba20173a4e7d0c908918bfa65ac70/closure/goog/labs/promise/testsuiteadapter.js#L33)

`promises_aplus_tests` should be `promises-aplus-tests`. Also, shouldn't this dependency be reflected in package.json?

**Comment by shicks** [comment]
The link seems to be broken - I think you want https://github.com/google/closure-library/blob/master/closure/goog/promise/testsuiteadapter.js

As far as that import and `package.json` go, we don't use it internally, so I don't really know what that's all about.  Feel free to send a PR to fix it.
