### ISSUE TITLE
goog.math.Integer Multiplication Is Returning An Incorrect Value

### ISSUE THREAD

**Issue by xcthulhu** [google/closure-library#703]
I am currently getting the wrong value when I perform the following multiplication (using the google closure library version 0.0-20151016-61277aea):

```js
var b = goog.math.Integer.fromString(
        "f729d763a14ecd55ffffebab43f388d0f7cbae584d3765d509b5557d6048ea0c", 16);
console.log(b.multiply(b).toString(16))
```

this prints

eea1c478f4683b323f0953c9c8e067e2967d97e7ed0bf05862cecac60f30077f170e480beee2cd0c1d5516764d58bc260cafe5705bc6b6df63cf4c057cb9f090

The correct value can be computed with python:

```
b = 0xf729d763a14ecd55ffffebab43f388d0f7cbae584d3765d509b5557d6048ea0c
print hex(b*b)
```

this prints

0xeea1c478f4683b323f0953c9c8e067e3967d97e7ed0bf05862cecac60f30077f170e480beee2cd0c1d5516764d58bc260cafe5705bc6b6df63cf4c057cb9f090L

It is worth noting that the first 64 bits and the last 64 bits of the two printed values agree.

**Comment by gfredericks** [comment]
The smallest example of this bug I could find is 

```
ffffffff00000001 · 1ffffffffffffffff
```

which should be

```
1fffffffe0000000100000000ffffffff
```

but `goog.math.Integer` gives:

```
1fffffffd0000000100000000ffffffff
```

**Comment by concavelenz** [comment]
Thanks for the report

**Comment by joeltine** [comment]
Is this no longer an issue?

**Comment by gfredericks** [comment]
My pull request was merged, so I assume it's not an issue on master at
least. I haven't checked if it's been released.

**Comment by joeltine** [comment]
Ah, sorry. Didn't even notice that.
