### ISSUE TITLE
Provide a tool to build new-format deps.js files.

### ISSUE THREAD

**Issue by shicks** [google/closure-library#705]
depswriter.py cannot write the new deps.js format, since it cannot parse language version.

We should either (a) port it to node.js and publish a tool on NPM, or (b) add a mode (or separate tool) to the closure compiler to output deps.js files.

**Comment by teppeis** [comment]
fixed with google-closure-deps

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
