### ISSUE TITLE
Compiler errors with certain flags turned on.

### ISSUE THREAD

**Issue by acousticguru** [google/closure-library#706]
1. Update to the latest version of the compiler and the most recent version of master.
2. Set compiler flag "--warning_level=VERBOSE" or "--jscomp_error=checkVars".
3. Witness compile errors "Variable <x> first declared in <otherFile>". 
Errors appear in: 
goog/crypt/bytestring_perf.js
goog/storage/mechanism/iterablemechanismtester.js
goog/storage/mechanism/mechanismtester.js

**Comment by joeltine** [comment]
Ya, you'll want to ignore those `_perf.js` files when compiling closure. See our build script for a list of exclusions: https://github.com/google/closure-library/blob/master/scripts/ci/compile_closure.sh

**Comment by acousticguru** [comment]
Thank you much.
