### ISSUE TITLE
Support WHITESPACE_ONLY mode with goog.ENABLE_DEBUG_LOADER=false

### ISSUE THREAD

**Issue by hochhaus** [google/closure-library#711]
As of the `v20160517` compiler release when compiling in `WHITESPACE_ONLY` mode the `WhitespaceWrapGoogModules` compile pass wraps `goog.module()` files in calls to `goog.loadModule(...)`. However, when setting `goog.ENABLE_DEBUG_LOADER=false` base.js does not define `goog.loadModule()`. This makes the combination of WHITESPACE_ONLY mode and `goog.ENABLE_DEBUG_LOADER=false` currently incompatible.

I originally filed https://github.com/google/closure-compiler/issues/1815 about this issue. @MatrixFrog suggested that a library level fix (moving the definition of `goog.loadModule()` out of the `goog.DEPENDENCIES_ENABLED` conditional and guarding it on another condition) might be the best course of action.

 @concavelenz @jart

**Comment by shicks** [comment]
Should be as simple as moving goog.loadModule and goog.loadModuleFromSource_ out of the debug loader.

I don't see a reason to guard it at all - what's the argument in favor?

**Comment by concavelenz** [comment]
That seems fine, if they aren't used they will be removed.

**Comment by hochhaus** [comment]
Thanks. I send a PR fixing this issue.
