### ISSUE TITLE
`goog.structs.weak.Map` and `goog.structs.weak.Set` do not exist

### ISSUE THREAD

**Issue by pauldraper** [google/closure-library#712]
https://github.com/google/closure-library/blob/master/closure/goog/structs/weak/weak.js#L18-L20

```
 * The helpers in this file are used for the shim implementations of
 * {@code goog.structs.weak.Map} and {@code goog.structs.weak.Set}, for browsers
 * that do not support ECMAScript 6 native WeakMap and WeakSet.
```

This suggests that `goog.structs.weak.Map` and `goog.structs.weak.Set` exist, but they do not.

**Comment by concavelenz** [comment]
yes, this looks like the author lost interest after a rollback.

**Comment by shicks** [comment]
Closure compiler will be providing polyfills in the near future.  Given that it was never finished, can we just delete this file?

**Comment by vipref** [comment]
The 'weak' versions do not exist and it seems the Set and Map implementations in Closure are deprecated.

This need for this issue is likely obviated by the deprecation.

**Comment by shicks** [comment]
This file has been deleted (long ago).
