### ISSUE TITLE
goog.ui.Dialog dragger prevent hidding the window outside of desktop browser

### ISSUE THREAD

**Issue by gmalartre** [google/closure-library#713]
The structure of the dialog draggable title bar goes as follow:

```
 <div class="title-draggable">
   <span class="close-btn"/>
 </div>
```

Because the draggable is applied on the parent of the .close-btn it seems that no click event can be produced by close-btn due to touchStart being triggered and mouseDown being forbidden by dragger.js.

Step to reproduce:
http://google.github.io/closure-library/source/closure/goog/demos/dialog.html

DESKTOP BROWSER - Move over button, click (traces produced using the monitorEvents($0) method)
''mousemove MouseEvent {isTrusted: true, screenX: -364, screenY: 93, clientX: 1556, clientY: 8…}
focus FocusEvent {isTrusted: true, relatedTarget: null, view: Window, detail: 0, which: 0…}
mousedown MouseEvent {isTrusted: true, screenX: -364, screenY: 93, clientX: 1556, clientY: 8…}
mousemove MouseEvent {isTrusted: true, screenX: -364, screenY: 93, clientX: 1556, clientY: 8…}
mouseup MouseEvent {isTrusted: true, screenX: -364, screenY: 93, clientX: 1556, clientY: 8…}
blur FocusEvent {isTrusted: true, relatedTarget: null, view: Window, detail: 0, which: 0…}
click MouseEvent {isTrusted: true, screenX: -364, screenY: 93, clientX: 1556, clientY: 8…}''

IPAD EMULATION - Move over same button, click -> intercepted by dragger    - Can not produce a click event in this case, ever.
''touchstart TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false…}
touchend TouchEvent {isTrusted: true, touches: TouchList, targetTouches: TouchList, changedTouches: TouchList, altKey: false…}''

A solution would be to restructure the dialog title bar (not really convenient in terms of positionning):

```
 <div class="title-draggable">
   <h3>Your title</h3>
 </div>
<span class="close-btn"/>
```

Another solution would be to let the mousedown event continue its bubbly phase instead of halting the event in dragger.js with this.preventMouseDown_.

**Comment by dferrara19** [comment]
Probably don't want to restructure the DOM. Happy the review a PR with a solution.
You might also be able to set hysteresis on the dragger.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
