### ISSUE TITLE
goog.dom.classlist error with SVG

### ISSUE THREAD

**Issue by ice1snice** [google/closure-library#714]
When trying to apply class for a SVG by calling goog.dom.classlist.enable it results calling:

```
goog.dom.classlist.add = function(element, className) {
  if (goog.dom.classlist.ALWAYS_USE_DOM_TOKEN_LIST || element.classList) {
    element.classList.add(className);
    return;
  }

  if (!goog.dom.classlist.contains(element, className)) {
    // Ensure we add a space if this is not the first class name added.
    element.className += element.className.length > 0 ?
        (' ' + className) : className;
  }
};
```

But SVG is having field 'className' not as a string, but as an object. So, as a result, class won't be applied for SVG.

**Comment by shicks** [comment]
Does the built-in `Element.prototype.classList` meet your needs?  `goog.dom.classlist` is basically just a shim for that and shouldn't really be used.  That said, if you can fix it to work, you're welcome to send a PR.

**Comment by concavelenz** [comment]
generally, goog.dom is for HTML and SVG support is limited at best.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
