### ISSUE TITLE
base_module_test.js compilation error (2016-06-01)

### ISSUE THREAD

**Issue by jc200** [google/closure-library#716]
Got the latest version today.
Received 2 errors when js are compiled with the closure compiler: 
1. line 54: References to the global name of a module are not allowed. Perhaps you meant exports? 
2. line 119: The body of a goog.module cannot reference this.

**Comment by shicks** [comment]
This seems to be WAI.  The reference to `this` was added the same time as the use of `this` was banned, so this appears to be a test that this banned behavior is doing what it should.  My instinct is that the test should probably not be compiled.

Please see https://github.com/google/closure-library/blob/master/scripts/ci/compile_closure.sh for an example of how to compile closure and omit test files.

Does it work if you use `if (!COMPILED)` to gate the offending code?  If so, you're welcome to send a PR.
