### ISSUE TITLE
goog.base does not work in constructor with goog.defineClass

### ISSUE THREAD

**Issue by tmccombs** [google/closure-library#717]
If you attempt to use `goog.base` to call the super constructo from the constructor of a class defined with `goog.defineClass` it fails with the error "goog.base called from a method of one name to a method of a different name".

**Comment by concavelenz** [comment]
There is a static base method defined on the constructor:

var MyClass = goog.defineClass({
   constructor: function() {
       MyClass.base(this, 'constructor');
   }
});

This is compatible with goog.defineClass.   goog.base doesn't work in
strict mode and is deprecated.  See:


https://github.com/google/closure-library/wiki/How-to-migrate-from-goog.base

More generally, now that current browsers support ES6 classes consider
using them instead.  The Closure Compiler translates ES6 classes to ES5
style code classes in an efficient manner, so it is reasonable to do so
even those extremely concerned with code size (classes and arrow functions
are nearly free).

**Comment by tmccombs** [comment]
Thanks, I wasn't aware goog.base was deprecated. It isn't marked as such in the API documentation (http://google.github.io/closure-library/api/namespace_goog.html#base). 

I would like to use ES6 classes, but we still support browsers that don't support ES6 classes, and if we used ES6 we would only be able to debug these browser with compiled code, which makes debugging much more difficult.
