### ISSUE TITLE
Online API documentation is broken

### ISSUE THREAD

**Issue by dkzd** [google/closure-library#722]
The URL http://google.github.io/closure-library/api/ returns only the header and no contents:

    Closure Generated API Docs

    This is the generated documentation for the Closure Library repository at github.com/google/closure-library.

    The documentation was produced using github.com/jleyba/js-dossier

nothing more.

**Comment by joeltine** [comment]
Use the search bar. See https://github.com/jleyba/js-dossier/issues/73. It's not really obvious, sorry abou thtat.

**Comment by dkzd** [comment]
Yes, just noticed the menu on the top left corner with the contents. Not super obvious but working. Thanks.
