### ISSUE TITLE
Using single quote hangs goog.i18n.DateTimeFormat

### ISSUE THREAD

**Issue by dkzd** [google/closure-library#723]
The single quote character in DateTimeFormat string makes the constructor hang with 100% CPU usage.

      var fmt = new goog.i18n.DateTimeFormat("MMM 'yy");

Example: https://codepen.io/anon/pen/gMmVgK

Disclaimer: I do realize that the quote symbol is used in format quoting and I need to use two adjusted single quotes to escape the quote itself. I just don't think the constructor should hang so violently even when the input format string is bad.

**Comment by fabalbon** [comment]
Thanks for pointing this out. This was fixed internally and will be available on the next Closure release.
