### ISSUE TITLE
Online documentation no longer available

### ISSUE THREAD

**Issue by markviewbix** [google/closure-library#725]
It looks like the online documentation for the Closure Library is no longer available. If you search for it, you find some archived versions and if you go to the Closure Library site, it points you to the GitHub page. 

Is this a mistake which is going to be corrected or did someone decide for some reason to remove it?

**Comment by joeltine** [comment]
The UI was reworked. Use the search bar or top-left drop-down at http://google.github.io/closure-library/api/

Please reopen if this was not the page you were referring to.
