### ISSUE TITLE
goog.ui.KeyboardShortcutHandler doesn't 'provide' Modifiers enum

### ISSUE THREAD

**Issue by worrel** [google/closure-library#726]
https://github.com/google/closure-library/blob/master/closure/goog/ui/keyboardshortcuthandler.js#L222 is not `provide()`-ed, but EventType is.  Shouldn't all Enums required by the API user be uniformly exported?

**Comment by shicks** [comment]
Makes sense.  Feel free to send a PR.

**Comment by ducky427** [comment]
PR sent. #728
