### ISSUE TITLE
F5 causes strange behaviour on tree controls

### ISSUE THREAD

**Issue by NeilFraser** [google/closure-library#727]
If a tree control has the focus, then 'F5' causes an apparently arbitrary (though consistent) node to become selected.  Seen on Chrome and Firefox on Linux and OSX.  Only happens once, page needs to be reloaded to recreate (which on some systems is what F5 does).  I assume that this has something to do with accessibility, but I can't find the relevant hook to determine what the intention is.

Steps to recreate:
- Go to https://google.github.io/closure-library/source/closure/goog/demos/
- Click on any entry in the tree control on the left to give it focus.
- Press 'F5' (fn-F5 on most macs)
- Observe that "Tooltips" entry is selected on the tree.

**Comment by NeilFraser** [comment]
FYI: Still present in Chrome & Firefox & Safari on OSX in December 2019.

**Comment by kjin** [comment]
Internal issue http://b/146676073 created.

**Comment by kjin** [comment]
Thanks for the update -- I can reproduce this as well.

**Comment by kjin** [comment]
It seems that something is converting the keycode to a character. F5 -> 116 -> 'T'. Likewise F4 will select the first item (actually, the first directory?) starting with 'S', which is "Sliders". So three things going on here:
1. We shouldn't try to convert keyCodes for non-alphanumeric keys
2. This should be happening more than once -- something is causing typeahead to stop working after the first press (regardless of what key)
3. Typeahead only allows selection of directories, which may or may not be desired
