### ISSUE TITLE
Hoisted variables forgotten after yield, unless hoisted manually

### ISSUE THREAD

**Issue by JdeH** [google/closure-library#730]
Hi,

I am using Closure v20160713.
It is started up by the Transcrypt Python to JS compiler with the options given below:

	import os
	import subprocess

	from org.transcrypt import utils

	closureCompilerPath = '{}/closure_compiler/compiler.jar'.format (os.path.dirname (os.path.abspath (__file__)) .replace ('\\', '/'))

	def run (sourcePath, targetPath, postMapPath, javaScriptVersion):
		params = [
			'java', '-jar',
			closureCompilerPath,
			'--language_in=ES{}'.format (javaScriptVersion),
			'--language_out=ECMASCRIPT5_STRICT',
			'--compilation_level', 'SIMPLE_OPTIMIZATIONS',
			'--js', sourcePath,
			'--js_output_file', targetPath
		]
		
		if utils.commandArgs.map:
			params += [
				'--create_source_map', postMapPath,
				'--source_map_format=V3'
			]

		subprocess.run (params)

Function 'accumulate' (part of Python 3.5 itertools module) works correctly in Chrome without using Closure to minify, but doesn't work if minified by Closure.
No error report or warning is given.

	var accumulate = function* (iterable, func) {
		let first = true;
		if (func) {
			for (let item of iterable) {
				if (first) {
					var sum = item;
					first = false;
				}
				else {
					sum = func (sum, item);
				}
				yield sum;
			}
		}
		else {
			for (let item of iterable) {
				if (first) {
					var sum = item;
					first = false;
				}
				else {
					sum = sum + item;
				}
				yield sum;
			}
		}
	}

Manually hoising variable 'sum' circumvents the problem:

	var accumulate = function* (iterable, func) {
		let sum;
		let first = true;
		if (func) {
			for (let item of iterable) {
				if (first) {
					sum = item;
					first = false;
				}
				else {
					sum = func (sum, item);
				}
				yield sum;
			}
		}
		else {
			for (let item of iterable) {
				if (first) {
					sum = item;
					first = false;
				}
				else {
					sum = sum + item;
				}
				yield sum;
			}
		}
	}

**Comment by concavelenz** [comment]
You want to report this against the compiler.

**Comment by JdeH** [comment]
Wrong spot, thanks  & sorry...

**Comment by concavelenz** [comment]
Np
