### ISSUE TITLE
goog.ui.Container.prototype.setHighlightedIndex doesn't set this.highlightedIndex_

### ISSUE THREAD

**Issue by ghosttie** [google/closure-library#731]
goog.ui.Container.prototype.setHighlightedIndex doesn't set this.highlightedIndex_ so calling goog.ui.Container.prototype.getHighlightedIndex doesn't return the index that was just set

**Comment by joeltine** [comment]
Any chance of a PR? goog.ui is mostly in maintenance mode atm.

**Comment by ghosttie** [comment]
https://github.com/google/closure-library/pull/733
