### ISSUE TITLE
goog.string.trim remove BOM too.

### ISSUE THREAD

**Issue by vivekimsit** [google/closure-library#732]
I see that the code uses:

`return str.replace(/^[\s\xa0]+|[\s\xa0]+$/g, '');`

shouldn't we remove the BOM too as they are useless in utf-8:

`return str.replace(/^[\s\uFEFF\u00A0]+|[\s\uFEFF\u00A0]+$/g, '');`

**Comment by joeltine** [comment]
Seems reasonable enough at first glance. I'm having trouble finding useful references describing potential issues stripping BOM. If you want to create a PR, we can test it out internally.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
