### ISSUE TITLE
goog.History failure when not supplying hidden input element

### ISSUE THREAD

**Issue by igorski** [google/closure-library#742]
When goog.History is constructed without passing an HTMLInputElement for the _opt_input_ value, it should generate a input element during construction. This however fails:

    var inputId = 'history_state' + goog.History.historyCount_;
    var inputHtml = goog.html.SafeHtml.create('input', {
      type: goog.dom.InputType.TEXT,
      name: inputId,
      id: inputId,
      style: goog.string.Const.from('display:none')
    });
    goog.dom.safe.documentWrite(document, inputHtml);
    input = goog.dom.getElement(inputId);

the _getElement(inputId)_ will not retrieve the input element that was supposedly appended to the DOM by the _documentWrite_ call above.

The unit test assumes this input element is present in the DOM and always passed to the constructer.

**Comment by mashedcode** [comment]
Did you double-check that the input element was actually written to the DOM?

**Comment by joeltine** [comment]
Closing until verifiably reproducible
