### ISSUE TITLE
[Feature Request] Implementation of block padding for crypt

### ISSUE THREAD

**Issue by gregbown** [google/closure-library#752]
It seems as though the crypt package is incomplete without an implementation of block padding such as PKCS7.  All the tests  for AES involve perfect bit size blocks which I think is unrealistic for real world use. The lack of this feature leaves the closure library encryption largely useless to most applications  or individuals without a more intimate knowledge of how to implement the missing pieces. Oddly enough, the missing piece already exists in another Google library.  I was able to port Googles' own end to end pkcs7.js over to closure library third party directory in a few minutes which again seems odd that the code is not just rolled into the closure library or shared somehow?!?

https://github.com/google/end-to-end/blob/master/src/javascript/crypto/e2e/ciphermode/pkcs7.js

I would feel a bit strange as an outside contributor, using Googles one library to contribute to another Google library.

Thank you

**Comment by xcthulhu** [comment]
👍 Good catch.

**Comment by joeltine** [comment]
Google is a large company. There are several teams writing JS that might be considered "core" and not all of it is in Closure. This mainly becomes a problem for open-source users as the code doesn't appear under the same code repository as they do internally. 

TBH, it's unlikely we'll roll this library into Closure Library proper. Open-sourcing an internal project is surprisingly difficult and the Closure team doesn't have the capacity to take ownership of the e2e crypto libs. I'd recommend just using the two libs separately as you are. If you'd like to be a good citizen maybe a comment in some of the crypto libs pointing to pkcs7 would be appropriate? Maybe a wiki article?
