### ISSUE TITLE
Access to protected property disposeInternal of MockTarget.prototype not allowed here

### ISSUE THREAD

**Issue by AlesJiranek** [google/closure-library#756]
Hello,

I'm not sure what am I doing wrong but when I try to compile my project in Advanced mode, I get 3 warnings from closure library. Could someone please help me?

```
Error: node_modules/google-closure-library/closure/goog/events/eventtargettester.js:1026: WARNING - Access to protected property disposeInternal of MockTarget.prototype not allowed here.
  MockTarget.prototype.disposeInternal = function() {
  ^

node_modules/google-closure-library/closure/goog/events/eventtargettester.js:1028: WARNING - Access to protected property disposeInternal of goog.events.EventTarget.prototype not allowed here.
    MockTarget.base(this, 'disposeInternal');
    ^

node_modules/google-closure-library/closure/goog/promise/testsuiteadapter.js:72: WARNING - Property exit never defined on process
    process.exit(1);
```

**Comment by myphysicslab** [comment]
The `eventtargettester.js` code seems to be only for testing.  It probably shouldn't be included in a project other than for testing closure-library itself.  How are you using it?  Do you know how it is included into your project?

**Comment by Dominator008** [comment]
@myphysicslab is correct. https://github.com/google/closure-library/blob/master/scripts/ci/compile_closure.sh#L22 shows that this file is not supposed to be included in your project.

**Comment by AlesJiranek** [comment]
Of course, thank you, there were wrong build paths in my project, test files were not excluded, thank you
