### ISSUE TITLE
 setScrollOffset does not behave correctly in Safari 10 with RTL

### ISSUE THREAD

**Issue by FuadBalashov** [google/closure-library#761]
In Safari 10 (released on sept 20 of this year) it appears that Apple changed the way that scrollLeft values are calculated in RTL.

There is some ambiguous information in the [safari change-log ](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html)related to this issue, (search for "Right-to-Left " in the linked page). In addition, if you look at the[ jfiddle here](https://jsfiddle.net/uuphto47/34/) you can see that the values of scrollLeft change based on what version you are on:

0 <-- 3500 (Safari 9.1.3)
-3500 <-- 0 (Safari 10)

This has resulted in setScrollOffset having unpredictable behavior in Safari 10. In previous versions of Safari (and in other browsers) using setScrollOffset to scrollWidth scrolls that component to its end, in Safari this is not the case.

JS Fiddle example: https://jsfiddle.net/uuphto47/25/

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
