### ISSUE TITLE
open source data files for registerLocalNameConstants

### ISSUE THREAD

**Issue by nicks** [google/closure-library#762]
registerLocalNameConstants needs a bunch of data files that give the names of each locale written in the other locales. See here:
https://github.com/google/closure-library/blob/5769370ad747affd84b4df37d39f4f2b50371ed0/closure/goog/locale/countrylanguagenames_test.js#L37

```
 // Test data from //googledata/i18n/js_locale_data/LocaleNameConstants__de.js
```

would it be possible to open source these data files? i'm pretty sure they're generated from cldr.

**Comment by fabalbon** [comment]
Hi Nick, for the moment we are not planning to make this data publicly available. We are planning to reimplement the NativeNames and LocalizedNames APIs which will require new locale data files which we are going to make available.

**Comment by nicks** [comment]
cool! do you have any idea when that might happen?
