### ISSUE TITLE
Does closure library support webpack with closure compiler js?

### ISSUE THREAD

**Issue by ntstv** [google/closure-library#763]
Hi. I'am trying use closure compiler js with webpack and it's fine, but I can't use closure library with him, because webpack require systems much differs from `goog.require`. I've found package `closure-loader`, that's help me connect closure library, but unfortunately closure compiler cant process output bundle and generates errors around `goog.define`, and some type definitions etc.

https://github.com/google/closure-compiler-js/issues/31

**Comment by joeltine** [comment]
Maybe this will help https://github.com/roman01la/webpack-closure-compiler. Although, the js compiler team doesn't support any webpack plugin formally. 

Also, what are your exact errors? It sounds like you're just missing some compiler flags and/or are trying to compile uncompilable code.
