### ISSUE TITLE
XhrManager isn't FIFO

### ISSUE THREAD

**Issue by mikekap** [google/closure-library#769]
Creating an XhrManager with a pool size of 1 and feeding it a constant stream of equal-priority requests can sometimes result in some later requests executing before earlier requests. I think the root cause is that the priority queue that XhrManager uses isn't guaranteed to be stable.

I'm not sure this is a bug necessarily, but it feels like this behavior should be documented.

**Comment by shicks** [comment]
Agree that documentation would be good, and maybe it would be good to fix.  We'd welcome any PR to do either of those!

**Comment by c-dy** [comment]
This is in fact documented in XhrManager.send:

> Note also that requests of equal priority are sent in an implementation specific order - to get FIFO queue semantics use a monotonically increasing priority for successive requests.

**Comment by shicks** [comment]
@mikekap Does that seem sufficient?  If not, feel free to reopen and suggest where else we could document it to make it clearer.
