### ISSUE TITLE
goog.dom.fullscreen/isFullScreen test insufficient on webkit

### ISSUE THREAD

**Issue by Ninerian** [google/closure-library#779]
Description:
The function goog.dom.fullscreen.isSupported lacks the test of webkitFullScreenEnabled.

Testcase:
Put a html site inside an iframe and don't allow fullscreen. Then call the function inside the iframe. It should return false, as document.webkitFullScreenEnabled returns false.

Solution:
Change the function to:

```
goog.dom.fullscreen.isSupported = function(opt_domHelper) {
  var doc = goog.dom.fullscreen.getDocument_(opt_domHelper);
  var body = doc.body;
  return !!(
      (body.webkitRequestFullscreen && doc.webkitFullScreenEnabled) ||
      (body.mozRequestFullScreen && doc.mozFullScreenEnabled) ||
      (body.msRequestFullscreen && doc.msFullscreenEnabled) ||
      (body.requestFullscreen && doc.fullscreenEnabled));
};
```

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
