### ISSUE TITLE
Issue with deprecated goog.graphics

### ISSUE THREAD

**Issue by Joffrey** [google/closure-library#784]
Closure compiler, with advanced optimization, would involve some problems with "goog/graphics/path.js" file.

This fix could solve the issue.

```diff
--- path_original.js 2016-08-19 14:37:10.293421800 +0200
+++ path.js 2016-08-19 14:37:21.955257800 +0200
@@ -90,11 +90,11 @@
* @enum {number}
*/
goog.graphics.Path.Segment = {
- MOVETO: 0,
- LINETO: 1,
- CURVETO: 2,
- ARCTO: 3,
- CLOSE: 4
+ MOVETO: 1,
+ LINETO: 2,
+ CURVETO: 3,
+ ARCTO: 4,
+ CLOSE: 5
};
```

**Comment by Dominator008** [comment]
Could you elaborate on what the problem was?

**Comment by concavelenz** [comment]
reopen if some details are provided

**Comment by Joffrey** [comment]
The closure compiler has a weird behavior with the 0 value for an enum {number}.

**Comment by mashedcode** [comment]
@Joffrey example and more detailed explanation please!
