### ISSUE TITLE
Investigate why top level constructor call is not removed in Advanced mode

### ISSUE THREAD

**Issue by mhevery** [google/closure-library#790]
[live demo](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afunction%2520make2()%2520%257B%2520return%2520function()%2520%257B%2520return%252010%253B%2520%257D%2520%257D%250A%250Avar%2520Foo%2520%253D%2520make2()%253B%250A%250Anew%2520Foo%253B%250A)

given:
```
// ==ClosureCompiler==
// @compilation_level ADVANCED_OPTIMIZATIONS
// @output_file_name default.js
// ==/ClosureCompiler==

function make2() { return function() { return 10; } }

var Foo = make2();

new Foo;
```

Results:
```
new function(){return 10};
```

Expects nothing

**Comment by dimvar** [comment]
Filed https://github.com/google/closure-compiler/issues/2249
