### ISSUE TITLE
goog.userAgent.product.VERSION is an empty string using Chrome on iOS

### ISSUE THREAD

**Issue by jrobinson01** [google/closure-library#795]
Given the following user-agent:
`Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.79 Mobile/14D27 Safari/602.1`

goog.userAgent.product.VERSION reports an empty string. I believe it should return the CriOS version.

**Comment by concavelenz** [comment]
Do you have a suggested fix?

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
