### ISSUE TITLE
Enter one-line summary

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#80]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=525

**Comment by joeltine** [comment]
Will not fix - bug in non-browser environment

**Comment by concavelenz** [comment]
We

**Comment by concavelenz** [comment]
However, this is fixed by setting goog.json.USE_NATIVE_JSON which is required for environments like Chrome Extensions.
