### ISSUE TITLE
Can't use en_ISO DateTimeSymbols by setting goog.LOCALE

### ISSUE THREAD

**Issue by martinklepsch** [google/closure-library#813]
I'm not sure if this is intentional or not but there's no clause to use the `en_ISO` `DateTimeSymbols` if the LOCALE is set to `en_ISO`. Is there a reason for this or is it maybe just an oversight? (see [datetimesymbols.js](https://github.com/google/closure-library/blob/f68f494fd33b4ae7efa8f66701313eb56692fb80/closure/goog/i18n/datetimesymbols.js))

**Comment by martinklepsch** [comment]
```js
/**
 * First day of week. 0 = Mon, 6 = Sun.
 * @type {number}
 * @private
 */
goog.date.Date.prototype.firstDayOfWeek_ =
    goog.i18n.DateTimeSymbols.FIRSTDAYOFWEEK;
```

Given [this implementation](https://github.com/google/closure-library/blob/master/closure/goog/date/date.js#L789-L795) of `firstDayOfWeek_` it becomes even more troubling because the pattern used in the tests (as below) is effectless on what's regarded as first day of the week.
```js
goog.i18n.DateTimeSymbols = goog.i18n.DateTimeSymbols_en_ISO;
```

**Comment by fabalbon** [comment]
This is a bug, thanks for reporting!

**Comment by fabalbon** [comment]
This bug was fixed internally and will be available in the next closure release.
