### ISSUE TITLE
testrunner.js uses deprecated goog.testing.TestCase.getTestResults

### ISSUE THREAD

**Issue by keghani** [google/closure-library#821]
Greetings from https://github.com/googlei18n/libphonenumber!

I'm getting errors compiling our JS library with the latest closure dependencies (closure-library, closure-compiler) because [testrunner.js](https://github.com/google/closure-library/blob/0592a220b21b53db3cb77caaaea69cadec20789d/closure/goog/testing/testrunner.js#L440) is making a call to deprecated [goog.testing.TestCase.getTestResults](https://github.com/google/closure-library/commit/acf652655b8f67ed36e01cdfff03765f1595c901#diff-f2db8d43347663cf7438b30cc1701fb0R712) which is deprecated; and we treat deprecation issues as errors ([our compilation flags](https://github.com/googlei18n/libphonenumber/blob/master/javascript/build.xml#L41)).

Is there a plan to update the code in testrunner.js?

The deprecation message is also in this repo's [Travis output](https://travis-ci.org/google/closure-library/builds/221324571#L3713), but probably not stopping builds because of [this compilation flag](https://github.com/google/closure-library/blob/e5a94170fbdc5eb759cfc4edfff4b55d95eb4fee/scripts/ci/compile_closure.sh#L15).

To reproduce:
```
git clone https://github.com/googlei18n/libphonenumber.git
cd libphonenumber
ln -s $CLOSURE_LIBRARY_DIR_PATH ../closure-library
ln -s $CLOSURE_COMPILER_DIR_PATH ../closure-compiler
ant -f javascript/build.xml compile
```

Output contains:
```
     [exec] /tmp/closure-library/closure/goog/testing/testrunner.js:440: ERROR - Property getTestResults of type goog.testing.TestCase has been deprecated.
     [exec]     return this.testCase.getTestResults();
     [exec]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     [exec] 
     [exec] 1 error(s), 0 warning(s), 97.6% typed
     [exec] calcdeps.py: JavaScript compilation failed.
```

**Comment by joeltine** [comment]
No concrete plans that I know of. We're kind of understaffed atm and
cleaning up deprecated methods is rather low priority. Feel free to submit
a PR (or CL) if you'd like.

**Comment by keghani** [comment]
Thanks @joeltine! I just realized the deprecated method is part of this project (d'oh) so sent a PR.

**Comment by shicks** [comment]
@dankurka Can you take a look at this?

**Comment by dankurka** [comment]
We have an internal CL that removes the deprecation and updates some other things. I'll take care of landing this and making sure it hits OS soon.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
