### ISSUE TITLE
v20170423 release

### ISSUE THREAD

**Issue by fredj** [google/closure-library#823]
Please create a v20170423 release to match the [latest closure-compiler release](https://github.com/google/closure-compiler/releases/tag/v20170423)

**Comment by joeltine** [comment]
Can start that, but was there any compatibility issue between the two versions? I am not aware of any backward incompatible changes between the two (but I could be wrong).

**Comment by fredj** [comment]
> was there any compatibility issue between the two versions?

Not to my knowledge. I will use the v20170409 release of the library

**Comment by joeltine** [comment]
Ya, just took a look, and it turns out we don't have a repo equivalence between the 4/9 and 4/23 closure compiler release. In other words, the 4/23 release would be the same as the 4/9. So you should be good.
