### ISSUE TITLE
Depswriter doesn't support multiple imports using curly braces

### ISSUE THREAD

**Issue by DustinJSilk** [google/closure-library#829]
The depswriter currently doesn't allow importing multiple dependencies like so:

```javascript
const {myDep} = goog.require('a.b.c');
const {Foo, Bar} = goog.require('a.b.d');
```

This is the [original regex pattern](https://github.com/google/closure-library/blob/master/closure/bin/build/source.py#L31):

```python
_REQUIRE_REGEX_STRING = (r'^\s*(?:(?:var|let|const)\s+[a-zA-Z_$][a-zA-Z0-9$_]*'
                         r'\s*=\s*)?goog\.require\(\s*[\'"](.+)[\'"]\s*\)')
```

My quick and probably not ideal solution for now looks like this:
```python
_REQUIRE_REGEX_STRING = (r'^\s*(?:(?:var|let|const)\s+(?:'
                         r'(?:\{+[a-zA-Z_$][,\sa-zA-Z0-9$_]+\})|'
                         r'(?:[a-zA-Z_$]?[a-zA-Z0-9$_])'
                         r')*\s*=\s*)?goog\.require\(\s*[\'"](.+)[\'"]\s*\)')
```

This means we have to compile the entire project when developing and cant run the app in browser which significantly slows down dev time.

**Comment by mashedcode** [comment]
Feel free to complete what was started here in #739
