### ISSUE TITLE
goog.dom.forms getValue and setValue both require `type` to be set but not all HTML elements with value have a type

### ISSUE THREAD

**Issue by thedavidmeister** [google/closure-library#833]
For example, `meter` and `progress` HTML elements have a `value` accessible via. `element.value` but not a `type`.

The default fallback for `getValue` and `setValue` should work for these elements.

Is there a reason to return at the start of these functions if elements don't have a type, because it seems unrelated to the whether the element might have a value?

**Comment by shicks** [comment]
I dug through the history a bit and it looks like it's been there from the start.  I think it was just added because back in 2007, all form elements had a type, and they wanted to not blow up when lowercaseing it.

If you want to send a PR that falls through to the default case if type isn't given, that would be fine.

**Comment by thedavidmeister** [comment]
ok, there's a PR up @shicks 

I'm seeing this failing in the tests but not sure how to resolve:

```
0.01s$ ./scripts/ci/lint_pull_request.sh
+java -jar ../closure-compiler/target/closure-compiler-linter-1.0-SNAPSHOT.jar closure/goog/dom/forms.js
Error: Unable to access jarfile ../closure-compiler/target/closure-compiler-linter-1.0-SNAPSHOT.jar
```

Also, soz that there's a lot of noise in the commits because I didn't realise that the tests were all repeated in different browsers and the behaviour of `goog.dom.forms.getValue()` is inconsistent in IE9 for `meter` elements that have no `value` set yet (it returns `null` while other browser return whatever `min` is set to).
