### ISSUE TITLE
package.json version incorrect and out-of-date

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-library#837]
The version specifier in the package.json isn't valid semver - need to leave off the leading 'v' character.

Also, it's significantly out of date with the version published to npm. Is this not getting MOE sync'd?

**Comment by shicks** [comment]
The NPM publishing is all black magic to me.  I don't think MOE manages this file at all.  No idea how it's kept in sync/generated/etc.  Are you saying it should be simply "20170626.0.0"?
