### ISSUE TITLE
goog.editor.Field does not fire onChange/onDelayedChange event when inner text is replaced through spellcheck.

### ISSUE THREAD

**Issue by e45lee** [google/closure-library#847]
On Chrome 61, replacing misspelled text by right-clicking and selecting a correction from the resulting dropdown menu triggers a single `input` event.

As far as I can tell, the logic that handles change events does not listen on `input` events at all;
changes are only triggered on keyup/paste/drop events.

I'm guessing that these lines:
https://github.com/google/closure-library/blob/6d7f198ed0f6253ec772d7bcf10411b6a791839e/closure/goog/editor/field.js#L886-L887

need to be replaced with something like this:
```
    this.addListener(
        ['cut', 'paste', 'input'], goog.functions.lock(this.dispatchChange));
```

**Comment by shicks** [comment]
If you can put together a PR and see that it passes the tests in Chrome and doesn't break older browsers, that would be awesome.

I wonder if there's a good way to simulate this correction in a unit test?

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
