### ISSUE TITLE
XhrIo and CORS not working 

### ISSUE THREAD

**Issue by lellisga** [google/closure-library#852]
I'm currently trying to do a simple call to any external url and I always get this message:
`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

here's the code

```js
ns.getImage = function(domObject){
    var dataUrl = domObject.target.value;
    var headers = new goog.structs.Map({
	'Access-Control-Allow-Origin': '*',
	'Content-Type': 'text/html'
    });

    console.log('!Sending simple request for ['+ dataUrl + ']');

    goog.net.XhrIo.send(
	dataUrl,
	ns.processResponse,
	'GET',
	undefined,
	headers
    );
};
```

I tried to with amazon and twitter. Anyone ran into this before?

**Comment by joeltine** [comment]
The access-control-allow-origin header should be set in the server response, not the client request.

**Comment by lellisga** [comment]
Sorry, why did you closed this? Removing that params still doesn’t solve the issue.

**Comment by jplaisted** [comment]
As joeltine said, this is up to the server to grant your app permission to the response by giving you an appropriate "Allow-Access-Control-Origin" response header. This is not a bug with the Closure Library.

Suggested reading:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://www.html5rocks.com/en/tutorials/cors/
