### ISSUE TITLE
api documentation is broken

### ISSUE THREAD

**Issue by ribrdb** [google/closure-library#856]
I recently started getting errors when I try to use the api docs. Some classes load fine and others give errors. It doesn't seem to be consistent either. Earlier today I could not load the docs for EventTarget. Now I can open EventTarget but other classes throw errors, like Delay.
Here is the error I get:
Uncaught TypeError: Cannot assign to read only property '0' of string 'g'
    at af (dossier.js:95)
    at dossier.js:95
    at Array.forEach (<anonymous>)
    at t (dossier.js:9)
    at $e (dossier.js:95)
    at dossier.js:7
    at Array.forEach (<anonymous>)
    at t (dossier.js:9)
    at I (dossier.js:94)
    at new Tf (dossier.js:106)

**Comment by jplaisted** [comment]
Closed by #861

**Comment by ribrdb** [comment]
This is not fixed. I still randomly get javascript errors at https://google.github.io/closure-library/api/
and the documentation fails to load.

**Comment by jplaisted** [comment]
What page(s) are giving you errors and in what browser(s)?

**Comment by ribrdb** [comment]
I'm using chrome. My teammate has also seen the same issue on chrome.
It's really inconsistent. Sometimes a page will load, but none of the links do anything when you click on them. Sometimes it's the search results that are broken. Once the page for a class loaded but all the methods were missing. When I reloaded the page it worked.

**Comment by nicks** [comment]
for what it's worth, I sometimes get errors like 

```
The FetchEvent for "https://google.github.io/closure-library/api/goog.Delay.html" resulted in a network error response: the promise was rejected.
serviceworker.js:2 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at serviceworker.js:2
    at <anonymous>
```

so it might be a service worker caching issue, which would explain the non-determinism

**Comment by ribrdb** [comment]
Could be service worker. I just hit this again. In the console I see two of the stack traces I originally posted, then "Service Worker termination by a timeout timer was canceled because DevTools is attached."
I opened a new tab, typed DateTime into the search box, and clicked on goog.date.DateTime. Nothing visibly happened but I found the error in the console after. Not sure if it's relevant but I have 3 other tabs open on the docs.

**Comment by ribrdb** [comment]
Also I tried reloading the page, didn't fix it in this case. But manually changing the url from https://google.github.io/closure-library/api/ to https://google.github.io/closure-library/api/goog.date.DateTime.html did fix it.

**Comment by jplaisted** [comment]
+@jleyba who owns js-dossier

**Comment by orian** [comment]
Take a look at:
https://google.github.io/closure-library/api/goog.module.html

The doc is empty, but when I go to source it has description: 
https://github.com/google/closure-library/blob/master/closure/goog/base.js#L378

**Comment by jplaisted** [comment]
This probably has to with the fact that goog.module is a function and a namespace.

https://github.com/google/closure-library/tree/master/closure/goog/module

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
