### ISSUE TITLE
Not supporting chrome 61 or above, due to the scrolling Element change

### ISSUE THREAD

**Issue by wangjl1110** [google/closure-library#857]
Seem closure library is not compatible with chrome 61 or above, because document.body is no longer a scrolling element in that version. https://bugs.chromium.org/p/chromium/issues/detail?id=157855

So the source code here is not correct. https://github.com/google/closure-library/blob/master/closure/goog/dom/dom.js#L742

All other places where calls this method and get scrollTop from scrolling element always get zero as return value, even though the scrollTop is not 0.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
