### ISSUE TITLE
Setting body to empty string on GET requests breaks for android in react native

### ISSUE THREAD

**Issue by Naomarik** [google/closure-library#858]
https://github.com/google/closure-library/blob/9e1fdcab653bed917bc81fe4a88d05883a8c7188/closure/goog/net/xhrio.js#L562

Specifically this line is causing issues. Could we conditionally set the body to an empty string only if the request method is not GET?

This causes react native on Android to fail with error code 6 (invalid HTTP response) even though it never hits the endpoint, and last error is unhelpfully set to "undefined [0]".

I've verified that changing the content back to null after this line solves the issue and successfully performs the request.

RN version 50.4

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
