### ISSUE TITLE
goog.crypt.base64.decodeString behaves differently depending on JS engine

### ISSUE THREAD

**Issue by vikeri** [google/closure-library#864]
The method `goog.crypt.base64.decodeString` behaves differently on JavaScriptCore compared to SpiderMonkey/V8.

If given `null` it will successfully complete on V8/SpiderMonkey but throw an error on JavaScriptCore.

I have a demonstration of the issue in this project: https://github.com/vikeri/closure-decode-fail

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
