### ISSUE TITLE
Faster goog.date.DateRange.Iterator and a thought on good.date.DateRange

### ISSUE THREAD

**Issue by gazzali** [google/closure-library#865]
1. goog.date.DateRange.Iterator uses
constructor, line 397: this.endDate_ = Number(dateRange.getEndDate().toIsoString());
next(), line 404: if (Number(this.nextDate_.toIsoString()) > this.endDate_) {

The simpler getTime() is faster:
constructor, line 397: this.endDate_ = dateRange.getEndDate().getTime();
next(), line 404: if ( this.nextDate_.getTime() > this.endDate_) {

2. For goog.date.DateRange, may I suggest a change from 
@param {goog.date.Date}
to
@param {goog.date.Date|goog.date.DateTime}? 

Calculations in goog.date.DateRange are done with goog.date.Interval.(MONTHS|DAYS) 
and time is untouched. I think letting the time be only 
00:00:00 (as is with goog.date.Date) is limiting (but could be the default?). 
Being able to pass in a goog.date.DateTime would be a plus.

The code change needed to include goog.date.DateTime would be in the iterator,
as in #1 above. As it is now, Number( datetime.toIsoString()) is NaN and the iterator 
won't terminate; iterator with getTime() works correctly.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
