### ISSUE TITLE
Aggressive sanitizing of URLs in test runner

### ISSUE THREAD

**Issue by emaxx-google** [google/closure-library#872]
When running tests using testrunner.js from a "file:///..." URL in the Debug mode, assertions are filed when trying to log the test results, because the URL for the constructed <A> node is passed through the safe URL validation, and as the "file:///..." URL isn't safe. See goog.testing.TestRunner.prototype.writeLog() - the point where it calls into goog.dom.safe.setAnchorHref().

This regressed after commit 84df94702de5e0bbc9f2d1f60c18d3fa41852383, AFAICS.

Could we just omit the URL safety validation for the test runner?

**Comment by jplaisted** [comment]
Duplicate of #869
