### ISSUE TITLE
Event Bubbling Triggers Additional Event Handlers

### ISSUE THREAD

**Issue by pentapache** [google/closure-library#873]
In the attached file, bugmaker.js, demonstrates how a sequence of events, the first event intended to bubble, causes events dispatched in that chain, to trigger event listeners that were not supposed to be called.

Consider a deeply nested button that dispatches an event which bubbles up to an event listener on a DIV. That event listener function makes a call on a sub-component public function. In that function, an event is dispatched as non-bubbling. It just so happens that this event type is commonly used throughout the web app. Because the initial event set parentEventTarget on its UI hierarchy, this secondary event is causing other event handlers to be called which would not have been called under normal circumstances.

The bugmaker.js file simplifies the issue. In the bugmaker.js file you'll see how the button fires an event picked up by the outer DIV element. That handler then dispatches an event on its child inner DIV. That event was only supposed to be handled at the inner DIV level, but because the initial event sequence - which setParentEventTarget - is currently in play, the outer DIV element's event handler is also called.

It seems that the internal event dispatch mechanism should assemble the list of ancestors based on the parentEventTargets and then clear those settings because actually dispatching the events.
[EventBubbleBug.zip](https://github.com/google/closure-library/files/1690673/EventBubbleBug.zip)

**Comment by pentapache** [comment]
Suggested solution to this issue: prior to dispatching with ancestorsTree, clear the parentEventTargets, then dispatch with the ancestorsTree array, then restore the parentEventTargets using the ancestorsTree.
[eventtarget.js.zip](https://github.com/google/closure-library/files/1708988/eventtarget.js.zip)

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
