### ISSUE TITLE
thumb in  goog.ui.Slider widget will drift off 

### ISSUE THREAD

**Issue by ivanixgames** [google/closure-library#876]
The thumb in slider will drift off when MoveToPointEnabled is true and thumb has style offset properties perpendicular to orientation of slider.

For horizontal sliders, if the thumb has a style property such as margin-top: -1px,  it will slowly drift in that direction when slider track is clicked on.
For vertical sliders, a style such as margin-left: -1px will cause the thumb to drift to the left.

A couple of attached photos show the issue:

![sliderhorzthumb](https://user-images.githubusercontent.com/858678/36078378-4a4e5a0e-0fb0-11e8-8abb-ae6ef686261d.png)

![sliderverticalthumb](https://user-images.githubusercontent.com/858678/36078382-50669f32-0fb0-11e8-9a1f-f3e17f7fa323.png)

**Comment by shicks** [comment]
Fixed by ed1785bf558c7119186f89163a01898a8a873ae0
