### ISSUE TITLE
Travis build died on my PR

### ISSUE THREAD

**Issue by ivanixgames** [google/closure-library#878]
Can someone take a look at it? 
https://travis-ci.org/google/closure-library/builds/340279494

**Comment by jplaisted** [comment]
I kicked off a restart but looking closely at the logs looks like it isn't connecting to sauce labs (though we don't run that anymore, can probably rip it out?). But I don't see your environment being set correctly. There's no SAUCE_USERNAME/SAUCE_ACCESS_KEY like in [passing builds.](https://travis-ci.org/google/closure-library/builds/338177964).

That being said, can probably just disable connecting to sauce labs for now; we aren't runny tests.

**Comment by ivanixgames** [comment]
@jplaisted   apologies for my ignorance, but I am not sure what i can do from my side to get travis to pass.
I don't have a sauce labs account. I did link travis to my github account and enabled the forked repo.  From what i can tell at https://docs.travis-ci.com/user/pull-requests/,   as I am an external contributor, the encrypted variables used by travis are not available and the tests will fail.

**Comment by jplaisted** [comment]
No worries, I'm pretty new at dealing with Travis as well. Thanks for the link, that appears to be the culprit. When I encrypted our sauce labs credentials I did not realize that would break travis with external PRs without additional handling. I'll be sure to fix this, thanks!

**Comment by jplaisted** [comment]
Better yet @concavelenz to avoid getting out of sync can you fix this right after you do a push? Should be a simple one liner in our travis config, see @ivanixgames' link above.

**Comment by jplaisted** [comment]
Was a little eager on closing since the Library's own build started to fail last week. It is fixed now and I restarted your build to make sure yours passes too. Looks like it is still trying to connect to sauce labs, need to sync first?

**Comment by nreid260** [comment]
Closing as stale.
