### ISSUE TITLE
Some undisposed objects in goog.editor

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#88]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=516

**Comment by joeltine** [comment]
Create and dispose goog.editor with monitoring instances as below.

goog.Disposable.MONITORING_MODE = goog.Disposable.MonitoringMode.PERMANENT;
document.body.appendChild(goog.dom.createDom('div', {'id': 'toolbar'}));
document.body.appendChild(goog.dom.createDom('div', {'id': 'editMe'}));
var myField = new goog.editor.Field('editMe');

/**
 * @param {goog.editor.Plugin} plugin The plugin to register.
 */
var registerPlugin = function(plugin) {
  myField.registerPlugin(plugin);
  myField.registerDisposable(plugin);
};

// Create and register all of the editing plugins you want to use.
registerPlugin(new goog.editor.plugins.BasicTextFormatter());
registerPlugin(new goog.editor.plugins.RemoveFormatting());
registerPlugin(new goog.editor.plugins.UndoRedo());
registerPlugin(new goog.editor.plugins.ListTabHandler());
registerPlugin(new goog.editor.plugins.SpacesTabHandler());
registerPlugin(new goog.editor.plugins.EnterHandler());
registerPlugin(new goog.editor.plugins.HeaderFormatter());
registerPlugin(new goog.editor.plugins.LoremIpsum('Click here to edit'));
registerPlugin(new goog.editor.plugins.LinkDialogPlugin());
registerPlugin(new goog.editor.plugins.LinkBubble());

// Specify the buttons to add to the toolbar, using built in default buttons.
var buttons = [
  goog.editor.Command.BOLD,
  goog.editor.Command.ITALIC,
  goog.editor.Command.UNDERLINE,
  goog.editor.Command.FONT_COLOR,
  goog.editor.Command.BACKGROUND_COLOR,
  goog.editor.Command.FONT_FACE,
  goog.editor.Command.FONT_SIZE,
  goog.editor.Command.LINK,
  goog.editor.Command.UNDO,
  goog.editor.Command.REDO,
  goog.editor.Command.UNORDERED_LIST,
  goog.editor.Command.ORDERED_LIST,
  goog.editor.Command.INDENT,
  goog.editor.Command.OUTDENT,
  goog.editor.Command.JUSTIFY_LEFT,
  goog.editor.Command.JUSTIFY_CENTER,
  goog.editor.Command.JUSTIFY_RIGHT,
  goog.editor.Command.SUBSCRIPT,
  goog.editor.Command.SUPERSCRIPT,
  goog.editor.Command.STRIKE_THROUGH,
  goog.editor.Command.REMOVE_FORMAT
];
var myToolbar = goog.ui.editor.DefaultToolbar.makeToolbar(buttons, goog.dom.getElement('toolbar'));

// Hook the toolbar into the field.
var myToolbarController = new goog.ui.editor.ToolbarController(myField, myToolbar);

goog.events.listen(myField, goog.editor.Field.EventType.LOAD, function() {
  myField.makeUneditable();
  myField.dispose();
  myToolbarController.dispose();
  var undisposedObjects = goog.Disposable.getUndisposedObjects();
  console.log(undisposedObjects.length);
});

myField.makeEditable();


What is the expected output? What do you see instead?
The console output
expected: 0
actual: 3


What version of the product are you using? On what operating system?
r2325


Please provide any additional information below.
The undisposed objects:
goog.async.Delay in goog.editor.Field
(https://code.google.com/p/closure-library/source/browse/trunk/closure/goog/editor/field.js?r=2325#140)
(https://code.google.com/p/closure-library/source/browse/trunk/closure/goog/editor/field.js?r=2325#868)
goog.events.EventHandler in goog.editor.plugins.AbstractBubblePlugin
(https://code.google.com/p/closure-library/source/browse/trunk/closure/goog/editor/plugins/abstractbubbleplugin.js?r=2325#63)

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
