### ISSUE TITLE
Calling super(this) in constructor of child ES6 class

### ISSUE THREAD

**Issue by gramic** [google/closure-library#882]
Using ES6 `class` with `extends` can't call super class with `this` argument.
This is in raw mode without any optimization.

```javascript
goog.require('goog.events.EventHandler');

class Child extends goog.events.EventHandler {
  constructor() {
    // Call EventHandler consturctor with opt_scope equal to this
    super(this); // exception is thrown here
  }
}

var child = new Child();
```
The good old prototype based approach works and not the ES6 way.

**Comment by jplaisted** [comment]
It is an optional parameter that you shouldn't need. If you take a look at the implementation the scope has a precedence that ends with itself.

`opt_scope /* argument to listen */ || self.handler_ /* constructor argument */ || self /* this */`

To put it another way, `super()` should have the functionality you're looking for with `super(this)`.
