### ISSUE TITLE
goog.events.KeyHandler can not catch the enter key operation on windows10 On-Screen keyboard

### ISSUE THREAD

**Issue by weiwl** [google/closure-library#889]
Device: Surface Pro4
OS: Windows10 Pro 1709.16299.309
Browser: Chrome 65.0.3325.162 / Edge

Enable the tablet mode of Surface Pro4, focus on an input element , and then press the enter key on On-Screen keyboard. There are only keydown and keyup event fired. There is no keypress event fired.

However, the current implementation of goog.events.KeyHandler is considering there should be a following keypress event after keydown event because of keycodes.js#L322 . For a physical keyboard it is quite true but for On-Screen keyboard it is not.

https://github.com/google/closure-library/blob/a959ebc8101b93c7850b91d8a4490bfe16e99489/closure/goog/events/keycodes.js#L322

Seems that there is also a similar problem on android tablet.
https://stackoverflow.com/questions/30743490/capture-keys-typed-on-android-virtual-keyboard-using-javascript

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
