### ISSUE TITLE
AVL tree has wrong height

### ISSUE THREAD

**Issue by kevin-dp** [google/closure-library#896]
Nodes (`goog.structs.AvlTree.Node`) of the AVL tree (`goog.structs.AvlTree`) sometimes have a wrong height.
When this happens on the root node, the AVL tree's instance method `getHeight` is also corrupted.

An example of this bug:

```
require("google-closure-library");
goog.require("goog.structs.AvlTree");
const tree = new goog.structs.AvlTree();
tree.add(0);
tree.add(8);
tree.add(5);

console.log('Tree height: ' + tree.getHeight());

const root  = tree.root_;
const left  = tree.root_.left;
const right = tree.root_.right;

console.log(`\t${root.value}`);
console.log(`${left.value}\t\t${right.value}`);
console.log('--------');

console.log(`Root details: `);
console.log('\theight: '      + root.height);
console.log('\tcount: ' + root.count);
console.log('\tleft child: '  + root.left.value);
console.log('\tright child: ' + root.right.value);
console.log('--------');

console.log(`Left details: `);
console.log('\theight: '      + left.height);
console.log('\tcount: '       + left.count);
console.log('\tleft child: '  + left.left);
console.log('\tright child: ' + left.right);
console.log('--------');

console.log('right details:');
console.log('\theight: '      + right.height);
console.log('\tcount: '       + right.count);
console.log('\tleft child: '  + right.left);
console.log('\tright child: ' + right.right);
console.log('--------');
```

Prints:

```
Tree height: 3      <-- WRONG
        5
0               8
--------
Root details: 
        height: 3      <-- WRONG
        count: 3
        left child: 0
        right child: 8
--------
Left details: 
        height: 1
        count: 1
        left child: null
        right child: null
--------
right details:
        height: 2     <-- WRONG
        count: 1
        left child: null
        right child: null
--------
```

The above tree, clearly has a height of 2, but `tree.getHeight()` incorrectly returns 3.
Analyzing in more detail, we observe that the root has a height of 3 which is wrong, also the right child has a height of 2 which is wrong.

**Comment by jplaisted** [comment]
Looks like the common balance method messes it up. An insert will insert, then recursively (balance then update height). So as it goes up the tree balancing the heights are incorrect. Because it is balancing on incorrect heights it stays incorrect. I'm also guessing this will lead to broken AVL-trees (less rigid balancing). I'm not sure it will break the order of elements though, which is more critical than balancing.

I'll look into a fix, thanks!
