### ISSUE TITLE
"jscomp.getCurrentModulePath is not a function" in code generated from latest Closure compiler service

### ISSUE THREAD

**Issue by AnmAtAnm** [google/closure-library#897]
One of the [Blockly](https://github/google/blockly) demo projects no longer works when running code built by the latest version of the Closure online compiler.

The version built from our `master` branch can be seen online [here](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html). Today, when I build either our `master` or `develop` branch, then run the demo, I see [these errors](https://github.com/google/blockly/issues/1830):

```
base.js:552 Uncaught TypeError: jscomp.getCurrentModulePath is not a function
    at Object.goog.isInEs6ModuleLoader_ (base.js:552)
    at Object.goog.isInModuleLoader_ (base.js:521)
    at Object.goog.provide (base.js:298)
    at analytics.js:25
goog.isInEs6ModuleLoader_ @ base.js:552
goog.isInModuleLoader_ @ base.js:521
goog.provide @ base.js:298
(anonymous) @ analytics.js:25
base.js:552 Uncaught TypeError: jscomp.getCurrentModulePath is not a function
    at Object.goog.isInEs6ModuleLoader_ (base.js:552)
    at Object.goog.isInModuleLoader_ (base.js:521)
    at Object.goog.provide (base.js:298)
    at block_definition_extractor.js:28
goog.isInEs6ModuleLoader_ @ base.js:552
goog.isInModuleLoader_ @ base.js:521
goog.provide @ base.js:298
(anonymous) @ block_definition_extractor.js:28
base.js:552 Uncaught TypeError: jscomp.getCurrentModulePath is not a function
    at Object.goog.isInEs6ModuleLoader_ (base.js:552)
    at Object.goog.isInModuleLoader_ (base.js:521)
    at Object.goog.provide (base.js:298)
    at factory_utils.js:35
```

Our `master` branch is our release branch, and has not seen changes since the release last week. This is the same code that is present at the [online version of the demo](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html) (same link as above).

Other demos appear to work fine, and this is by far the most complex of our demos. There is a possibility the code is not doing something correctly, this still indicates a drastic behavior change from last week.

**Comment by jplaisted** [comment]
I don't see these errors. Have you rolled something back? Investigating in the mean time.

**Comment by AnmAtAnm** [comment]
@jplaisted The version served by blockly-demo.appspot.com was compiled April 20th and does not have errors. Today, recompiling the same code gives the errors listed above. Obviously we are not going push such code out to our server with this error.

**Comment by jplaisted** [comment]
So a quick peek in the inspector shows you have a `$jscomp` object that only has a `scope` property. You have a blockly_compressed.js file that defines this. This looks like something compiled with Closure Compiler that has some optimizations turned on that removes the runtime but does not run Closure pass or rename anything. So `$jscomp` still exists and the `goog.provide` calls are preserved. Thus `goog.provide` ends up erroring with the stack trace above.

Simple fix to just check if that method exists before calling it. This only breaks certain compiled bundles as described above.

**Comment by AnmAtAnm** [comment]
> So a quick peek in the inspector shows you have a $jscomp object that only has a scope property.

This is not new. The object existed in previous builds from Closure. Latest build on `master` branch: https://github.com/google/blockly/blob/7679d227df8f62a12316334ee708d4a9a800ef17/blockly_compressed.js#L4

It is not clear to me why this object was created or how we could influence it.

> Simple fix to just check if that method exists before calling it. This only breaks certain compiled bundles as described above.

Then this sounds like a correction that needs to occur in `isInEs6ModuleLoader_`. Correct?

**Comment by jplaisted** [comment]
Yep, I have the fix internally and am getting it through review.

**Comment by AnmAtAnm** [comment]
Still seeing the same error on the compiler service.  What is the schedule to get this to production?

**Comment by jplaisted** [comment]
I assume you mean a release. We should push a library release with the next compiler release. @lauraharker when is that?

**Comment by lauraharker** [comment]
The next compiler release is in progress. I should be finished today.
