### ISSUE TITLE
The old Closure Library UI package is stale. Any plans to open source Material Design UI for Closure Library?

### ISSUE THREAD

**Issue by jimbojetlag** [google/closure-library#898]
Closure Library is used in Gmail and Google Maps implementing Material Design. Material Design 2 is now available in new Gmail. Is there a plan to open source the MD UI?

**Comment by jplaisted** [comment]
We have no plans to update the Closure UI widgets (`goog.ui`). Google has many other UI frameworks that are recommended, including Polymer and Angular. While Gmail and Google Maps use Closure Library they are not using the `goog.ui` package and are using other UI frameworks.

**Comment by jimbojetlag** [comment]
Thanks for this information.

> While Gmail and Google Maps may use Closure Library they are not using the goog.ui package and are using other UI frameworks.

Which UI frameworks are these? Are they open source?
