### ISSUE TITLE
Conformance check returns "Global declarations are not allowed" error for functions/classes in ES6 modules

### ISSUE THREAD

**Issue by luzhang** [google/closure-library#900]
Hey Closure library team,

I was trying to use Closure compiler to compile ES6 modules, but it returns error "Global declarations are not allowed" for the functions and classes defined in the ES6 modules. The errors are gone after I turned off the conformance checks in the Closure compiler. I used the conformance_proto.txt provided by Google Closure library to enable the conformance check, so I wonder if it is a bug in the conformance_proto file to support ES6 modules.

I pasted the configurations here:

const defaultFlags = {
  compilation_level: 'ADVANCED',
  warning_level: 'VERBOSE',
  language_in: 'ECMASCRIPT6_STRICT',
  language_out: 'ECMASCRIPT5_STRICT',
  rewrite_polyfills: true,
  angular_pass: true,
  export_local_property_definitions: true,
  generate_exports: true,
  module_resolution: 'NODE',
  dependency_mode: 'STRICT',
  entry_point: 'app',
  output_wrapper: '(function(){\n%output%\n}).call(this)',
  js_output_file: 'main.min.js',
  externs: externsPath,
  // conformance_configs: path.join(closureLibrarySrcDir,
  //   'conformance_proto.txt'),
  // jscomp_error: 'conformanceViolations',
};

Thanks,
Lu

To make it work, I have to turn

**Comment by luzhang** [comment]
Thanks for looking into this issue John!

**Comment by jplaisted** [comment]
I fixed this in the compiler. When it is committed to github I'll link it here and close this then.

**Comment by luzhang** [comment]
Thanks for fixing it John, it will be rolled out with the next Closure release? Any idea when that will happen?

**Comment by jplaisted** [comment]
@lauraharker Are you still on release / do you know when the next compiler release is scheduled?
