### ISSUE TITLE
Karma Closure preprocessor to support ES6 module

### ISSUE THREAD

**Issue by luzhang** [google/closure-library#902]
Hey Closure team,

I used both Closure goog.module and ES6 modules in my project and I am trying to find a way to do unit tests with Karma.  I have a few options: 
a. Use [karma-closure processor](https://github.com/nckh/karma-closure) with other tools like webpack or babel to transpile ES6 modules.
b. Update the above karma-closure processor to support ES6 module.
c. There is an [issue](https://github.com/karma-runner/karma/issues/2903) opened about adding Karma support for es6 modules. If this feature is added, we can just use the karma-closure processor mentioned above. 

Can you share some thought on these options? I also wonder if Closure team has a plan to offer an official Karma-Closure preprocessor to handle ES6 modules.

Thanks,
Lu

**Comment by jplaisted** [comment]
We don't own the karma-closure processor. The karma team does (at least the [original version](https://github.com/karma-runner/karma-closure), not sure what your fork of a fork is). We don't currently have any plans to support Karma on our end but we're glad that Karma does on theirs. I suggest just waiting for Karma to add support for ES6 modules.

I suspect for Karma _usable_ ES6 module support is a larger task than just ES6 module support - generally people don't want to write browser compliant paths.

If at the point at which Karma does support ES6 modules but Closure-ES6 module interop fails in Karma I'd be more than happy to take a look. But as far as base support for ES6 modules go I'd wait for Karma to add it.
