### ISSUE TITLE
goog.Timer.defaultTimerObject is not a valid timer object if closure compiled code is served via browserify

### ISSUE THREAD

**Issue by AnmAtAnm** [google/closure-library#903]
`goog.Timer.defaultTimerObject` defaults to `goog.global`, but `goog.global` is may be (errantly?) assigned the node module (referenced as `this` [here](https://github.com/google/closure-library/blob/master/closure/goog/base.js#L49)) instead of Node's [`global`](https://nodejs.org/api/globals.html#globals_global).

The result when code is served through browserify is that the expected `setTimeout()`, etc. functions do not exist. This breaks Timer functions, and may also break other code dependent of `goog.global` acting like `window`. See https://github.com/google/blockly/issues/1901.

**Comment by jplaisted** [comment]
You can require the package `google-closure-library` and it works fine. However that isn't compiled. Looks like our [bootstrap script](https://github.com/google/closure-library/blob/master/closure/goog/bootstrap/nodejs.js) evals Closure's base.js with the `global` context.

So yeah, without special handling Closure Compiled output will be pretty broken in Node. I think most people just don't use the compiled code in Node as code size isn't generally an issue and instead will require the npm package.

So question is that a valid work flow? Type check with Closure but don't build if you plan to run in Node?

**Comment by concavelenz** [comment]
Many things break if goog.global isn't set correctly.  Having it use global
in node would be the correct thing.   That should be fixed.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
