### ISSUE TITLE
Share design docs linked from fileoverview

### ISSUE THREAD

**Issue by stringham** [google/closure-library#905]
In https://github.com/google/closure-library/blob/master/closure/goog/module/loader.js there is a file overview which says:

```javascript
/**
 *
 * @fileoverview This class supports the dynamic loading of compiled
 * javascript modules at runtime, as described in the designdoc.
 *
 *   <http://go/js_modules_design>
 *
 */
```

and I'd like to get more information about how this works, but don't have access to the design doc. Is it possible to update this to be a publicly accessible url?

There are many other instances of `http://go/*` urls in this project and it may be worth considering updating them to be public urls when appropriate.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
