### ISSUE TITLE
Incorrect gh-pages documentation for goog.debug.ErrorReporter.setXhrSender

### ISSUE THREAD

**Issue by frenchy64** [google/closure-library#906]
The first argument to the setXhrSender method on [this page](https://google.github.io/closure-library/api/goog.debug.ErrorReporter.html) has type

```
function(string, string, string, ()): ?
```

but it should be

```
function(string, string, string, (Object|goog.structs.Map)=): ?
```

**Comment by jplaisted** [comment]
Thanks for filing all of these.

FYI we use https://github.com/jleyba/js-dossier to generate this documentation, so these bugs lie there. I'll re-file these issues there.
