### ISSUE TITLE
FileDropHandler error on IE10

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#91]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=513

**Comment by joeltine** [comment]
Fixed in https://github.com/google/closure-library/commit/572dbc8b6aaae1660930dd3f4992a5c74ea117b5#diff-e68c15d9233319f7494503a7f1a813e3
