### ISSUE TITLE
Rounding error in NumberFormat with large maximumFractionDigits

### ISSUE THREAD

**Issue by ribrdb** [google/closure-library#916]
Steps to reproduce:
```js
const nf = new NumberFormat(NumberFormat.DECIMAL);
nf.setMaximumFractionDigits(12);
nf.format(1.1e5);
```

Expected result: `"110,000"`
Actual result: `"110,000.000000000016"`

**Comment by nreid260** [comment]
I'm not able to reproduce this under Chrome, Edge, Firefox, IE9, IE10, IE11, or Safari 10. Do you have any more context?

**Comment by touletan** [comment]
I have been able to reproduce a similar issue with the following code:
const nf = new NumberFormat(NumberFormat.DECIMAL);
nf.setMaximumFractionDigits(12);
nf.format(1.1e15);

I raised PR #922

**Comment by nreid260** [comment]
Could you tell me the browser/platform? We're disinclined to accept changes until we can verify the problem.

**Comment by touletan** [comment]
you can probably reproduce the problem on your side . In one of the test file comparison is done againts a result that is not good in the current version:
/closure/goog/i18n/numberformat_test.js
One of the test is showing that fmt.format(1.3456E20) = 134,559,999,999,999,980,000
With the proposed PR the value is now = 134,560,000,000,000,000,000

@@ -85,7 +85,7 @@ function testVeryBigNumber() {
   fmt = new goog.i18n.NumberFormat(goog.i18n.NumberFormat.Format.DECIMAL);
  str = fmt.format(1.3456E20);
  assertTrue(veryBigNumberCompare('134,559,999,999,999,980,000', str));
  assertTrue(veryBigNumberCompare('134,560,000,000,000,000,000', str));

**Comment by touletan** [comment]
let me know if you need more input to reproduce to issue.

**Comment by nreid260** [comment]
Sorry for the very long delay!

After giving it a second shot, I can indeed reproduce this. I had some concerns with the proposed fix so I've put something together on my end. It will most likely appear in the next release.

Thanks for your pointers and patience :)

**Comment by touletan** [comment]
Could you please let me know how this has been fixed?

**Comment by nreid260** [comment]
We've switched to doing decimal place shifts using string representations rather than multiplication and division.
