### ISSUE TITLE
goog.Promise's timing differs from native

### ISSUE THREAD

**Issue by jplaisted** [google/closure-library#925]
One could argue if this is a bug; Promise/A+ makes no mention of this. However I think we eventually want to consolidate goog.Promise and native Promise if possible.

goog.Promise has a different then() callback order than native Promise. goog.Promise batches callbacks where as native Promise does not. Example:

```
var p1 = Promise.resolve(() => resolve());
var p2 = Promise.resolve(() => resolve());
var arr = [];
Promise.all([
  p1.then(() => arr.push(1)),
  p2.then(() => arr.push(2)),
  p1.then(() => arr.push(3)),
  p2.then(() => arr.push(4)),
]).then(() => console.log(arr));
```

Is `[1, 3, 2, 4]` for goog.Promise, `[1, 2, 3, 4]` for native.

**Comment by jplaisted** [comment]
I think this will break using mock clock to tick promises in tests. When you have an async test (returns a thenable) then the test framework will use `goog.Promise` to resolve them. It will call you `n`th test (where `n` > 0) in a `goog.Promise` callback.

Right now mock clock can be installed and then it will intercept all `goog.Promise` calls made afterwards because they each will have their own callback queue.

But if we have a global callback queue, which is in the middle of being processed in a test, then mock clock won't intercept any `goog.Promise`s made in the test.

Don't get me wrong, ticking Promises synchronously was always a bad idea, but we'll have to migrate people off this pattern or think of something else. Right now this seems blocked on mock clock.

**Comment by concavelenz** [comment]
I think the test framework can be migrated to use Promise rather than goog.Promise.    The polyfill should work.

**Comment by jplaisted** [comment]
Then you get into different timing issues. `MockClock` forces `goog.Promise` to use next tick to schedule, rather than native `Promise`. It never undoes this action. Even if we did make it undo the action on uninstallation, if anyone installs the mock clock over multiple tests we're not better off.

I think, without going to far, we can say this probably isn't going to be trivial due to various issues around `MockClock`.

**Comment by concavelenz** [comment]
I think we are talking past each other.  The test framework itself should be as independent of the test running as we can make it.  It should use the native Promise whenever possible for scheduling tests, just as it saves off the native setTimeout, etc to do its own scheduling so MockClock can't interfere with it.

**Comment by jplaisted** [comment]
You're right, I wasn't clear sorry. But upon further investigation I was incorrect anyway.

I thought what was happening was `MockClock` forced `goog.Promise`s to use macrotasks, but if the test runner was microtasks then you could get interference between tests where they was none before.

However looking a bit deeper the issue is actually that uninstalling or resetting a `MockClock` that was never installed will wipe out the `goog.async` queue. This happens in the `goog.Promise` tests. When each `goog.Promise` had its own callback queue this didn't matter - the promises made in the individual tests would not run callbacks after the test is run if the mock clock wasn't installed. However now that there's a global queue, running that gets cancelled, and `goog.Promise` will never schedule anything ever again since it is still waiting to run its callbacks that it thinks it scheduled.



But the tl;dr of all my posts is `MockClock` will be a larger headache than we probably think.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
