### ISSUE TITLE
html sanitizer should not trim whitespace from data-* attributes

### ISSUE THREAD

**Issue by ribrdb** [google/closure-library#931]
Say I sanitize the string '&lt;span data-latex="\\ ">&lt;/span>'. The html sanitizer will trim the whitespace, resulting in invalid latex '&lt;span data-latex="\\">&lt;/span>'.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
