### ISSUE TITLE
Remove UA sniffing around event.keyCode/charCode for keypress events in Firefox

### ISSUE THREAD

**Issue by miketaylr** [google/closure-library#932]
In order to ship `window.event` in Gecko, we've discovered that [supporting `event.keyCode` for `keypress` events is required](https://bugzilla.mozilla.org/show_bug.cgi?id=1479964). 

Our plan is to essentially do what Chrome does, explained by the first part of the commit message:

> Chrome sets both KeyboardEvent.keyCode and KeyboardEvent.charCode of "keypress" event to same value. On the other hand, our traditional behavior is, sets one of them to 0. 
>
> Therefore, we need to set keyCode value to charCode value if the keypress event is caused by a non-function key, i.e., it may be a printable key with specific modifier state and/or different keyboard layout for compatibility with Chrome. Similarly, we need to set charCode value to keyCode value if the keypress event is caused by a function key which is not mapped to producing a character.

See https://hg.mozilla.org/mozilla-central/rev/a9db3033d9cb

However, once we landed this we discovered that keyboards shortcuts break in sites using Closure break (GMail, GSuite, Remember The Milk, etc). 

Places that need to be updated (possibly more?) to not expect a Firefox UA string will have 0 for `event.keyCode` or `event.charCode` in `keypress` events:

https://github.com/google/closure-library/blob/719529feafc9d60eecd2f620756d3e5cc84a9250/closure/goog/events/keyhandler.js#L400-L413
https://github.com/google/closure-library/blob/719529feafc9d60eecd2f620756d3e5cc84a9250/closure/goog/events/keyhandler.js#L439-L449
https://github.com/google/closure-library/blob/719529feafc9d60eecd2f620756d3e5cc84a9250/closure/goog/events/keycodes.js#L413-L415

**Comment by miketaylr** [comment]
cc @jplaisted @dtapuska @masayuki-nakano

**Comment by jplaisted** [comment]
Hey @miketaylr,

Thanks for reporting this. We've tried testing with Firefox Nightly on both OS X and Linux, enabling the `dom.keyboardevent.keypress.set_keycode_and_charcode_to_same_value` flag, and are not seeing any obvious issues with keyboard shortcuts on Docs, Slides, and Gmail.

Can you give a more specific repro case? Thanks!

**Comment by miketaylr** [comment]
Hi @jplaisted, thanks!

Here's more specific pointers to bugs, with better STR, all assuming `dom.keyboardevent.keypress.set_keycode_and_charcode_to_same_value` is set to true (which shouldn't require a browser restart):

***Gmail***
1. https://bugzilla.mozilla.org/show_bug.cgi?id=1497519

1. go to gmail
2. in settings, enable keyboard shortcuts
3. from your inbox, use `j` or `k` shortcuts to navigate between messages

(However, I can't reproduce that bug with the pref flipped... I'll ping the reporter on that)

***Google Docs***
In https://bugzilla.mozilla.org/show_bug.cgi?id=1497518#c6

It says the user was not able to type certain keys.
1. go to google docs, start a new document
2. try to type the top letters of a QWERTY keyboard: qwertyuiop

expected output: 
qwertyuiop

actual output:
eio

**Comment by miketaylr** [comment]
(ok, i've updated the gmail STR -- i can reproduce it now)

**Comment by masayuki-nakano** [comment]
The new behavior can be detected with:
```
function onKeyPress(event) {
  let keyCode, charCode;
  if (isGecko) {
    if (event.keyCode === event.charCode) {
      if (event.keyCode < 0x20) {
        keyCode = event.keyCode;
        charCode = 0;
      } else {
        keyCode = 0;
        charCode = event.charCode;
      }
    } else {
      keyCode = event.keyCode;
      charCode = event.charCode;
    }
  }
  ...
}
```

Note that Gecko won't take the new behavior without stopping dispatching non-printable keypress events. So, you need to treat only Enter key press specially if keyCode and charCode are same.
