### ISSUE TITLE
Slider setValue(0) does not move the thumb

### ISSUE THREAD

**Issue by tarehart** [google/closure-library#936]
Hello,

I noticed that if a slider is freshly constructed, setValue(0) does not move the thumb at all. This is a problem when the slider has a range that spans positive and negative numbers.

```javascript
  var slider = new goog.ui.Slider();
  slider.setUnitIncrement(0.1);
  slider.setStep(0.1);
  slider.setMinimum(-1);
  slider.setMaximum(1);

  // This should move the thumb to the middle of the range, but the
  // thumb does not move and stays on the left (where -1 is)
  slider.setValue(0);
```

It's possible to work around this by setting a non-zero value first, then setting zero. I suspect this is a defect with goog.ui.RangeModel: https://github.com/google/closure-library/blob/master/closure/goog/ui/rangemodel.js#L116

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
