### ISSUE TITLE
closuremakedeps hangs producing no output while consuming a lot of CPU

### ISSUE THREAD

**Issue by jimbojetlag** [google/closure-library#937]
I tried running closuremakedeps both with the npm package and the master version like this:

```sh
npx closure-make-deps \
  --closure-path ./node_modules/google-closure-library/closure/goog \
  --root ./myapp
```

But there is no output, the executable hangs using 200-300% CPU on macOS.

The reason I tried using google-closure-deps is that I need to use ES6 modules in debug mode during development. Following [this wiki page](https://github.com/google/closure-library/wiki/ES6-modules-and-Closure-Library), it seems like the existing depswriter.py is not able to do this, and the only way to achieve this is by using google-closure-deps, is that correct?

**Comment by jimbojetlag** [comment]
It looks like deps maker process does something, but it's painfully slow. Moe debugging showed that the call to closure-compiler's `gjd()` takes an average of 1 second per file. Is this a known issue?

**Comment by jplaisted** [comment]
> Following this wiki page, it seems like the existing depswriter.py is not able to do this, and the only way to achieve this is by using google-closure-deps, is that correct?

Correct. The idea was to try to consolidate our code around this (reuse the code from the compiler), and also  to write our tooling in JavaScript rather than Python going forward.

> It looks like deps maker process does something, but it's painfully slow. Moe debugging showed that the call to closure-compiler's gjd() takes an average of 1 second per file. Is this a known issue?

Do you have any more details about your machine?

Running on my linux desktop for Closure Library (1567 files) I get.

```
real	0m13.691s
user	0m19.947s
sys	0m0.491s
```

Running the same thing on my macbook air I get similar results:

```
real	0m15.002s
user	0m18.720s
sys	0m0.586s
```

If you'd like to reproduce to compare, I cloned the github repro, then ran:

```
cd closure-deps/
npm install
node ./bin/closuremakedeps.js --root ./node_modules/google-closure-library/closure/goog/ --root ./node_modules/google-closure-library/third_party/closure/goog/ --exclude ./node_modules/google-closure-library/closure/goog/transpile.js --exclude ./node_modules/google-closure-library/closure/goog/testing/testdata --exclude ./node_modules/google-closure-library/closure/goog/bin --exclude ./node_modules/google-closure-library/closure/goog/conformance --exclude ./node_modules/google-closure-library/closure/goog/css --exclude ./node_modules/google-closure-library/closure/goog/demos --exclude ./node_modules/google-closure-library/closure/goog/docs --exclude ./node_modules/google-closure-library/closure/goog/transpile --exclude ./node_modules/google-closure-library/closure/goog/debug_loader_integration_tests --exclude ./node_modules/google-closure-library/closure/goog/base_debug_loader_test.js
```

**Comment by jplaisted** [comment]
Another question would be: do you have any super large files (or even directories) that can be excluded? Use the `--exclude` flag.

**Comment by jimbojetlag** [comment]
Maybe I'm missing something here. This is the tool that makes closure dependencies during application development. The python implementation takes 0.5-2 seconds. With the javascript implementation, Is the developer supposed to wait 10-15 seconds after each changes for a page refresh? That'd be 10x to 30x slower than the python implementation.

As a reference I tried to compile https://github.com/google/jsaction on a macbook pro, with python:

```sh
time ./node_modules/google-closure-library/closure/bin/build/depswriter.py \
  --root_with_prefix='./node_modules/jsaction/ ../../../jsaction' \

[output omitted]

real	0m0.451s
user	0m0.129s
sys	0m0.181s
```

With javascript:
```sh
time node ./node_modules/google-closure-library/closure-deps/bin/closuremakedeps.js \
  --closure-path ./node_modules/google-closure-library/closure/goog \
  --root ./node_modules/jsaction/ \

Error: Error in source file "[...]/node_modules/jsaction/actionflow.js": Could not find "goog.array".
    at new SourceError ([...]/node_modules/google-closure-library/closure-deps/lib/sourceerror.js:27:5)
    at validate ([...]/node_modules/google-closure-library/closure-deps/lib/depgraph.js:285:19)
    at Graph.validate ([...]/node_modules/google-closure-library/closure-deps/lib/depgraph.js:337:9)
    at main ([...]/node_modules/google-closure-library/closure-deps/bin/closuremakedeps.js:194:30)

real	1m3.412s
user	2m21.133s
sys	0m5.773s
```

**Comment by jplaisted** [comment]
Something seems wrong with your machine / environment. Can you try it on another machine, just to get another data point? Here's JS Action for me on linux with node 11:

```
real	0m0.862s
user	0m1.525s
sys	0m0.071s
```

And on my macbook air with node 10.1:

```
real	0m1.153s
user	0m1.591s
sys	0m0.096s
```


> The python implementation takes 0.5-2 seconds. With the javascript implementation, Is the developer supposed to wait 10-15 seconds after each changes for a page refresh? That'd be 10x to 30x slower than the python implementation.

Yeah, this is a good point. On the other hand, dependencies most likely not updated often. As an FYI, the python version does simple regex searches, while the new JS version performs an AST traversal, which probably slows things down, but is more correct.

I think what we could add to the JS version is an incremental update mode. You give it the existing deps file that needs updating, and what files updated, and it will look at only those files. It should also be simple to make a wrapper around this that actively watches for changes and updates your deps file automatically. That should significantly speed things up if it only updates what actually changed, during development.

**Comment by jimbojetlag** [comment]
I had graalvm installed on my machine (trying to make a native-image of closure compiler), which apparently comes with its own Node. After removing graalvm Node from the path, the timings are much better.

Could you provide the command you used for compiling jsaction? I keep getting the above `Could not find "goog.array"` error. When compiling my own application, should I just use `--closure-path path/to/goog/closure` instead of `--root path/to/goog/closure` to speed up dependency generation?

I think the incremental approach you mentioned is a must for development. It'd be great to have that feature.

**Comment by jplaisted** [comment]
You either need to include Closure Library when running the command, or just add `--no-validate`. And since we're on the subject of feature requests, we could also add support for reading in other deps.js files. So you wouldn't need `--no-validate`, but just add Closure Library's deps.js file as input, and it would see `goog.array` is provided there.

**Comment by jplaisted** [comment]
fyi @ChadKillingsworth @concavelenz about graalvm (see @jimbojetlag 's post above)

**Comment by jimbojetlag** [comment]
> You either need to include Closure Library when running the command, or just add --no-validate. 

Thanks for the detailed explanation, but I'm still having a hard time getting the right arguments for `closuremakedeps.js`.

By 'including Closure Library' do you mean using `--closure-path path/to/goog.closure`, or `--root path/to/goog.closure`?

I assumed that `--closure-path` means that `closuremakedeps.js` will use the existing `deps.js`, apparently that is not what's happening, and it's unclear to me what `--closure-path` does.

Would you please provide the command you used for compiling jsaction that gave you the timing of `real	0m0.862s` in the above?

**Comment by jplaisted** [comment]
> By 'including Closure Library' do you mean using --closure-path path/to/goog.closure, or --root path/to/goog.closure?

The latter. But that will also scan all of Closure Library, and include it in the output, which is probably not what you want. `--no-validate` will disable the validation of the dependency graph entirely, so that `goog.array` doesn't need to be seen at all. As above, it'd probably be nicer to edit this tool to be able to read in Closure's deps.js file, see `goog.array` in there, and use that for validation.

> I assumed that --closure-path means that closuremakedeps.js will use the existing deps.js, apparently that is not what's happening, and it's unclear to me what --closure-path does.

Correct, it does not do that. It's just used to determine the relative path to Closure (which is needed in the output).

> Would you please provide the command you used for compiling jsaction that gave you the timing of real 0m0.862s in the above?

Assuming your first run `npm install google-closure-deps` and `npm install jsaction`:

```
time node ./node_modules/google-closure-deps/bin/closuremakedeps.js   --closure-path ./node_modules/google-closure-library/closure/goog   --root ./node_modules/jsaction/ --no-validate
```

**Comment by jimbojetlag** [comment]
Thanks a lot, usage of `closuremakedeps.js` is now more clear.

I am closing this issue as the performance problem was due to the graalvm Node, and not related to closuremakedeps. You may want to reopen this if the issue applies to the discussed feature request.

**Comment by ChadKillingsworth** [comment]
Native images of closure compiler are now published on npm.
