### ISSUE TITLE
goog.ui.SplitBehavior menu button height is wrong in FF in the demo

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#94]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=507

**Comment by joeltine** [comment]
Confirmed only on FF16, let you decide what you want to do.

**Comment by dferrara19** [comment]
goog.ui is not actively maintained.

**Comment by kjin** [comment]
It seems that SplitBehavior was removed in 76b2508 in March 2017, and the demo along with it.
