### ISSUE TITLE
Deps.js generated by new closure-deps is broken on Windows

### ISSUE THREAD

**Issue by anwerso** [google/closure-library#940]
On Windows generaed `deps.js` looks like: `goog.addDependency('..\..\..\..\path\to\file.js', ...` and browser unable to load such files (`Uncaught SyntaxError: Invalid Unicode escape sequence`).

I think we need to normalize pathnames using posix style.

**Comment by jplaisted** [comment]
Really these are URLs, not posix paths. But we may have to use posix paths, I'm not sure node really support making relative URLs.

**Comment by anwerso** [comment]
Well, at least it should be escaped to work on Windows (`..\\..\\..\\..\\path\\to\\file.js`). But it is not an ideal solution when you commit `deps.js` to repo (like in CL). Python script always generated path with forward slashes. Reasonable aproach would be to repeat this behavior.

**Comment by mprobst** [comment]
Internal issue created: b/144353153

**Comment by shicks** [comment]
This is not something we run into internally, or even really have a way of testing.  If you want to send in a PR to replace \ with / in these paths, that would be welcome.

**Comment by anwerso** [comment]
New version works even worse. It generates something like:
`goog.addDependency('../C:\path-to-app\node_modules\google-closure-library\closure\goog\base.js', ['goog'], [], {});`

**Comment by pistacio520** [comment]
> New version works even worse. It generates something like: `goog.addDependency('../C:\path-to-app\node_modules\google-closure-library\closure\goog\base.js', ['goog'], [], {});`

You can use regexp to replace them.
look like that replaced:
goog.addDependency('.\\bootstrap\\webworkers.js', [], []);

**Comment by shicks** [comment]
We would welcome any contribution that applies this change automatically.  Nobody on our development team uses (or really even has access to) Windows, so it's difficult to know how to do this correctly.  If you send a PR that works for you, we'll be happy to review and merge it.
