### ISSUE TITLE
goog.userAgent.MOBILE does not detect embedded iOS WebView

### ISSUE THREAD

**Issue by AnmAtAnm** [google/closure-library#941]
In an embedded iOS WebView (tested with iOS simulator and attached Safari debugger):
```
> goog.userAgent.MOBILE
false
>navigator.userAgent
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko)"
```

On the same device, when running directly in mobile Safari:
```
> goog.userAgent.MOBILE
true
>navigator.userAgent
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1"
```

The problem is you are explicitly looking for the word Mobile [here](https://github.com/google/closure-library/blob/master/closure/goog/useragent/useragent.js#L186), but that is part of the Safari browser version name ("12.0 Mobile"; may need to scroll the above code block). Outside the browser, the user agent doesn't have "Mobile".

[Here](https://github.com/google/blockly/tree/master/demos/mobile/ios) is my example project that combines both an embedded WebView and closure. In this case, some behavior does not adapt correctly to the mobile environment because Blockly tests using `goog.userAgent.MOBILE`.

**Comment by jplaisted** [comment]
`goog.userAgent.isMobile_` has the comment `TODO(nnaze): Investigate swapping in goog.labs.userAgent.device.isMobile().`. Now may be a good time to address that?

**Comment by jplaisted** [comment]
(So at the very least, for now, you could use that labs method)

**Comment by vipref** [comment]
The labs method - me being the original author - checks explicitly for iPhone in the UA string and hence produces the correct result for this use case.

It might just be the right time to consolidate the user agent utils in goog.labs and the top level namespace.

**Comment by shicks** [comment]
Closing this in favor of #1061.
