### ISSUE TITLE
How to use closure library inside a worker in JavaScript?

### ISSUE THREAD

**Issue by asanzesp** [google/closure-library#942]

**Comment by nreid260** [comment]
Hello!

What have you tried and what didn't work? We don't currently know of any blockers with using Closure in a WebWorker.

**Comment by asanzesp** [comment]
This is my WebWorker:

self.addEventListener('message', function(e) {

   importScripts("../js/closure-library/closure/goog/base.js");

   mainFunction();

   self.postMessage("message");

   self.close();

}, false);

From inside the Web Worker does not recognize the libraries.
This is the log that I get:

Cannot use default debug loader outside of HTML documents. base.js:826:5
goog.logToConsole_
http://localhost/js/closure-library/closure/goog/base.js:826:5
goog.Dependency.prototype.load
http://localhost/js/closure-library/closure/goog/base.js:3332:7
goog.DebugLoader_.prototype.loadDeps_/<
http://localhost/js/closure-library/closure/goog/base.js:2960:11
goog.DebugLoader_.prototype.loadDeps_
http://localhost/js/closure-library/closure/goog/base.js:2875:8
goog.DebugLoader_.prototype.loadClosureDeps
http://localhost/js/closure-library/closure/goog/base.js:2776:5
<anónimo>
http://localhost/js/closure-library/closure/goog/base.js:3979:5
<anónimo>
http://localhost/dashboard/do_work.js:18:4
Consider setting CLOSURE_IMPORT_SCRIPT before loading base.js, or setting CLOSURE_NO_DEPS to true. base.js:826:5
goog.logToConsole_
http://localhost/js/closure-library/closure/goog/base.js:826:5
goog.Dependency.prototype.load
http://localhost/js/closure-library/closure/goog/base.js:3339:9
goog.DebugLoader_.prototype.loadDeps_/<
http://localhost/js/closure-library/closure/goog/base.js:2960:11
goog.DebugLoader_.prototype.loadDeps_
http://localhost/js/closure-library/closure/goog/base.js:2875:8
goog.DebugLoader_.prototype.loadClosureDeps
http://localhost/js/closure-library/closure/goog/base.js:2776:5
<anónimo>
http://localhost/js/closure-library/closure/goog/base.js:3979:5
<anónimo>
http://localhost/dashboard/do_work.js:18:4

**Comment by nreid260** [comment]
Per that stack trace, it looks like `CLOSURE_IMPORT_SCRIPT` is your issue. Please take a look at [closure-library/closure/goog/bootstrap/webworkers.js](https://github.com/google/closure-library/blob/b86cde2489dc50868e2769e42961318a2fd50859/closure/goog/bootstrap/webworkers.js). It should have a solution.

Basically (and I'm no expert) it looks like the DebugLoader uses script tags to load code by default. This doesn't make sense inside a WebWorker. By setting `CLOSURE_IMPORT_SCRIPT` to a different value before trying to load your main app, a different loading mechanism, appropriate for a Worker, will be used instead.

**Comment by jplaisted** [comment]
Hey Asier,

I'm going to assume this is resolved with the Closure web worker bootstrap file. Feel free to reopen if not!
