### ISSUE TITLE
goog.Uri,removeDotSegments returns wrong results for leading ../

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#95]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=506

**Comment by joeltine** [comment]
asertEquals('../a.js', goog.Uri.removeDotSegments('../a.js'))

The .. case needs to updated to:

        } else if (segment == '..') {
          if (out.length > 1 || out.length == 1 && out[0] != '') {
            out.pop();
          } else if (leadingSlash && pos == segments.length) {
            out.push('');
          } else {
            out.push(segment);
          }

I haven't run the tests so maybe this is incomplete or breaks something else

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
