### ISSUE TITLE
Documentation about unit testing

### ISSUE THREAD

**Issue by jkevingutierrez** [google/closure-library#963]
It would be great to have some documentation about how to test modules using closure-library, having some examples.

**Comment by jplaisted** [comment]
Hey, sorry for the delayed response! Do you mean specifically issues with modules (e.g. mocking out modules), or just unit testing in general?

**Comment by vipref** [comment]
The tests accompanying the implementation for mocks and assertions (in good.labs.mock and goog.labs.testing, for example) also serve as good clues on how to use the utilities to mock and use assertions.

**Comment by shicks** [comment]
We're more or less moving off of these libraries and encouraging the use of other testing frameworks.  If somebody wants to contribute documentation, it would be welcome, but it's pretty low priority for us.

**Comment by shicks** [comment]
This issue is being closed as a preparation step before archiving the repository.  See the [README](https://github.com/google/closure-library) for more detail.
