### ISSUE TITLE
testSuite: assertObjectEquals and TypedArrays

### ISSUE THREAD

**Issue by michaelfig** [google/closure-library#969]
Hi,

I'm trying to fix test cases from google/tink#190, and have found several failures around the testing of TypedArrays.

Basically, the test expects things like the following to pass:

```javascript
goog.module('tink.TypedArrayTest');
goog.setTestOnly('tink.TypedArrayTest');
const testSuite = goog.require('goog.testing.testSuite');
testSuite({
  testTypedArrays() {
    const buf1 = new ArrayBuffer(3);
    const buf2 = new ArrayBuffer(4);
    const ta1 = new Uint8Array(buf1, 0, 3);
    const ta2 = new Uint8Array(buf2, 1, 3);
    for (let i = 0; i < ta1.length; i ++) {
      ta1[i] = ta2[i] = i;
    }
    assertObjectEquals(ta1, ta2);
  }
});
```

but when I run it, I get:

```
-> 21:58:40.160 : Starting tests: Untitled Test Case
-> 21:58:40.160 : Running test: testTypedArrays
-> Expected <[object Uint8Array]> (Object) but was <[object Uint8Array]> (Object)
->    byteOffset: Expected <0> (Number) but was <1> (Number)
   buffer.byteLength: Expected <3> (Number) but was <4> (Number)
-> 21:58:40.164 : testRead : FAILED
```

I would argue that when testing TypedArray values, the user probably cares about value-equality (i.e. same array type, length, and contents), and not the attributes related to the backing buffer, much like the way Date objects are compared.

Does this warrant the introduction of a new assertion, say `assertContentEquals(ta1, ta2)`, or do you think it should be handled differently?  I can't do this easily in the project's code, as the TypedArrays being compared are nested deeply within other objects.  So,  I need to have something recursive that handles TypedArrays specially.

Please let me know what the design should be, and I will be willing to cook up a PR to do the right thing.

Thanks,
Michael.

**Comment by shicks** [comment]
Create Google internal issue b/130244740

**Comment by shicks** [comment]
Given that we already have logic in findDifferences for Map and Set, it makes sense to extend this to deal with TypedArrays automatically, rather than add a new assertion.

That said, I'm not enthusiastic about enumerating all the different types of typed arrays (though maybe that's just [the thing to do](https://github.com/ljharb/is-typed-array/blob/master/index.js)).  I think what we'd expect is that the types would be the same and the elements would be the same.

If you want to give it a go, we'd appreciate it!

**Comment by michaelfig** [comment]
Okay, I'll work on this in the coming week.  Thanks for the design advice.
