### ISSUE TITLE
Version mismatch between package.json and .tgz filename causes issues with private registries

### ISSUE THREAD

**Issue by arghya** [google/closure-library#972]
We use artifactory as a private npm registry. New libraries are published to artifactory by pulling from npm registry and publishing to our private repository. In case of google-closure-library, we are running into some issues because the version in the package.json and the tar.gz file are different.

For more context see this: 
https://jfrog.com/knowledge-base/issue-with-npm-package-install-not-found/

Below is the json file artifactory calculates while pulling from npm registry. Note the two fields:
  "version" : "v20190325.0.0"
 "tarball" : "-/google-closure-library-20190325.0.0.tgz"

```json
{
  "name" : "google-closure-library",
  "description" : "Google's common JavaScript library",
  "version" : "v20190325.0.0",
  "author" : "The Closure Library Authors",
  "homepage" : "https://developers.google.com/closure/library/",
  "repository" : {
    "type" : "git",
    "url" : "https://github.com/google/closure-library.git"
  },
  "bugs" : {
    "url" : "https://github.com/google/closure-library/issues"
  },
  "main" : "closure/goog/bootstrap/nodejs.js",
  "dist" : {
    "tarball" : "...../-/google-closure-library-20190325.0.0.tgz",
    "shasum" : "9093adfa028cd3c11ebbf46b6ead51ecadfc1b4e"
  },
  "devDependencies" : {
    "promise" : "^7.0.4",
    "protractor" : "^2.1.0"
  },
  "keywords" : [ "javascript", "library", "goog", "closure" ],
  "license" : "Apache-2.0"
}
```

These values are derived from what's specified in the package.json file of this library and what the .tgz file is called.

**Comment by jplaisted** [comment]
Sorry, what's the problem and the fix? Those versions are the same. I'm not sure what the correct naming scheme is here to fix it.

**Comment by arghya** [comment]
The problem is the v in front of the version
"version" : "v20190325.0.0"

Note that the version as per the .tgz file is 20190325.0.0 (without the v). We also opened a case with Artifactory and they mentioned that the "v" at the beginning is a problem for artifactory. This may have been fixed in newer versions of artifactory though.

To make it work, here's what I did:
- download the .tgz file
- modify the version in the package.json inside the .tgz archive to remove the v
- recreate the archive
- publish to artifactory

After this, it worked fine. In general it might be a good practice to follow the version scheme consistently in file naming.

**Comment by jplaisted** [comment]
Yeah I acknowledge that our version scheming is non standard. But I don't know how inclined we are to change it now. At the very least, this version needs to match the compiler's version.

Passing this off to @concavelenz

**Comment by shicks** [comment]
Internal issue created b/131718212

**Comment by brad4d** [comment]
This sounds like a problem with artifactory to me.
I don't know where the "v" is coming from, because when I do `npm install google-closure-library`, then look at the `package.json` file in the installed package, it doesn't have the "v".

**Comment by brad4d** [comment]
Wait, maybe I do see where it's coming from in the main `package.json` file here
http://go/gh/google/closure-library/blob/master/package.json
which is different from the one that ends up with the NPM package.

**Comment by brad4d** [comment]
The corresponding 'package.json' files in the various forms of the compiler NPM do not have the 'v'.
e.g.
https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler-js/package.json#L3

So it does seem that this is something that could be changed in the closure-library release process.

**Comment by concavelenz** [comment]
Looks like Mar 26, 2016 release was the first that included the "v":
https://github.com/google/closure-library/commit/5933ab8b8de57288403accc4152f16285c06789d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by concavelenz** [comment]
Let's remove "v" from our versions in our package.json files.

**Comment by teppeis** [comment]
@concavelenz @brad4d 
I suppose removing "v" from package.json.

It causes problems in some tools that assume that "v" does not exist.
ex): https://github.com/ds300/patch-package/pull/122
`npm install` normalizes package.json and removes "v", but `npm ci` doesn't.

**Comment by brad4d** [comment]
So, who's going to do that work?
@jplaisted or @shicks  maybe?

**Comment by shicks** [comment]
We're working on fixing up how we handle package.json and should address this when we do.
