### ISSUE TITLE
closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected

### ISSUE THREAD

**Issue by afckd** [google/closure-library#988]
closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected

**Comment by kjin** [comment]
Can you elaborate on how you came across this issue? The line in question doesn't seem to have a syntax error: https://github.com/google/closure-library/blame/13a702155814c84950b16027035bf3e29d6fa5be/closure/goog/streams/full_test_cases.js#L635

**Comment by proxiaoyi** [comment]
> closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected

refer from csdn：（this work for me）
go run setup.go (this fails)
cd third_party/closure-library/
git reset --hard v20170409
cd -
go run setup.go (this passes)

**Comment by nreid260** [comment]
Created Google internal issue b/142081541

**Comment by nreid260** [comment]
@afckd We need more information to do anything about this issue

**Comment by lx610** [comment]
i have the same problem:  closure-library/closure/goog/streams/full_test_cases.js:635: ERROR - Parse error. '(' expected  .  And i solve the problem by using realse version before 2017 year.

**Comment by nreid260** [comment]
What version of the compiler is reporting the parse error? Those tests (I think) use async functions and will need a parser that supports them.

**Comment by fudongbai** [comment]
I upgraded to go1.13.4 and still has this issue:
go version go1.13.4 darwin/amd64

Could you tell what go version has parser support?

**Comment by fudongbai** [comment]
I run into this issue by issuing 'go run setup.go' in battery-historian, this can be fixed by updating *closureCompilerVersion* in setup.go to 20191027, hope this will help people using battery-historian.

**Comment by mprobst** [comment]
This is working as intended then, closing the issue. Please reopen if there's more here.
