### ISSUE TITLE
goog.declareModuleId doesn't appear to work as documented

### ISSUE THREAD

**Issue by rapodaca** [google/closure-library#989]
I'm trying to follow the documentation on combining ES6 modules and the Closure Library at:

https://github.com/google/closure-library/wiki/ES6-modules-and-Closure-Library

There are two files, `application.js` and `entry.js`. `entry.js` invokes `application.js` as per the documentation:

> Additionally you should not import your program's entry point - you will need to either goog.require or goog.bootstrap it. Thus it is recommended your program entry point call goog.declareModuleId if it is an ES6 module, so that you have something to pass to goog.require / goog.bootstrap.

In `src/application.js`:

```js
goog.declareModuleId('my.application');

const application = () => {
  console.log('IT WORKS!');
};

export default application
```

In `src/entry.js`:

```js
goog.provide('my');

goog.require('my.application');

const entry = () => {
  console.log('my.application', my.application);
};

goog.exportSymbol('my.entry', entry);
```

I'm compiling with:

```
node_modules/google-closure-compiler-osx/compiler \
  --js_output_file build/close.js \
  --js=src/**.js \
  --js=node_modules/google-closure-library/closure/goog/**.js \
  --dependency_mode=STRICT \
  --entry_point=src/entry.js \
  --module_resolution=NODE \
  --process_common_js_modules \
  --language_in ECMASCRIPT_2018 \
  --language_out ECMASCRIPT_2015 \
  --rewrite_polyfills=false \
  --warning_level=VERBOSE \
  --compilation_level=SIMPLE
```

When running my compiled script, I expect to see a log of the `my.application` function, but instead `my.application` comes out undefined in `entry.js`.

I'm using the NPM library, version 20190729.0.0, but the latest one from September also gives the same result.

If I try to assign

```js
my.application = application
```

in application.js, I get this error on running:
 "TypeError: undefined is not an object (evaluating 'my.application=application$$module$src$application')"

What am I missing?

**Comment by kjin** [comment]
In `src/application.js`, I don't think it works to use `goog.declareModuleId('my.application');` and expect `my.application` to contain the value of `application`. You can ES6 `import` it into `src/entry.js` (you'd also replace the `goog.provide('my')` with `goog.declareModuleId('my')` to make it accessible to `goog.require`/`goog.bootstrap` elsewhere).

**Comment by nreid260** [comment]
Created Google internal issue b/141552512

**Comment by shicks** [comment]
Sorry for the slow response - we've been changing our triage process recently and I think this got lost.

The short answer is that your usage of `goog.declareModuleId` and `goog.require` is incorrect - in short, you cannot import an ES module into a `goog.provide` file.  You can only import it into a `goog.module`.  `goog.declareModuleId` _does not_ create a global symbol, nor does the `goog.require`, so `my.application` simply does not exist.  This is different from how `goog.module.declareLegacyNamespace()` behaves (it allows you to import a `goog.module` into a `goog.provide` by creating that global symbol).  But there is no analogue to a legacy namespace for ES modules.

If you really need to import an ES module into a `goog.provide` script (which we don't recommend - in general you should be migrating all your scripts to modules as much as possible), the only option is to make a shim `goog.module` with `declareLegacyNamespace()` and then use an aliasing require and re-export it on the legacy namespace.

(As an aside it's also generally a bad idea to have one namespace be the parent of another - i.e. `my` and `my.application`.  Instead, they should be siblings: `my.entry` and `my.application`.  This doesn't cause problems in most cases, but it can be disastrous when you have a `declareLegacyNamespace` in the mix.)

I've updated the documentation to hopefully make this clearer.
