### ISSUE TITLE
Inconsistency in goog.text.LoremIpsum.prototype.generateParagraph

### ISSUE THREAD

**Issue by nanaze** [google/closure-library#99]
This issue was imported from Closure Library's previous home at http://closure-library.googlecode.com

The link to the original issue is:
https://code.google.com/p/closure-library/issues/detail?id=499

**Comment by joeltine** [comment]
Fixed in https://github.com/google/closure-library/commit/5c7b7354f1eae77c45a4a8d577d481b482fff3a8#diff-0e9f1694ef03072a1ec1a38c6fdafb69
