### ISSUE TITLE
When "calcdeps.py" is executed, the exception "WindowsError: [Error 87]" is caused by the "proc = subprocess.Popen(args, stdout=subprocess.PIPE)" parameter "args" of the function "Compile".

### ISSUE THREAD

**Issue by gisshare2015** [google/closure-library#991]
When "calcdeps.py" is executed, the exception "WindowsError: [Error 87]" is caused by the "proc = subprocess.Popen(args, stdout=subprocess.PIPE)" parameter "args" of the function "Compile".

Currently, the temporary processing scheme optimizes the parameter "args" more often.
Such as:
The "testA" folder contains files: a.js, b.js, c.js
The "testB" folder contains files: a2.js, b2.js, c2.js
The files that need to be compiled are: testA\a.js, testA\b.js, testA\c.js, testB\a2.js, testB\b2.js
Not optimized:
`args = ['--js', 'testA\a.js', '--js', 'testA\b.js', '--js', 'testA\c.js', '--js ', 'testB\a2.js', '--js', 'testB\b2.js']`
Optimized:
`args = ['--js', 'testA\**.js', 'testB\a2.js', '--js', 'testB\b2.js']`

Code:
Add function:
```
def GetFileExtension(path):
  arr = os.path.splitext(path)
  return arr[len(arr) - 1]

def GetKeyPathFile(file):
  dir = os.path.dirname(file)
  ext = GetFileExtension(file)
  if len(ext) == 0: 
    ext = '.'
  else:
    ext = ext.lower()
  key = dir + '\\**' + ext
  return key
  
def TotalFile(path, ex):
  count = 0
  for name in os.listdir(path):
    # logging.info(name)
    if os.path.isfile(os.path.join(path, name)):
      if name.lower().endswith(ex):
        count += 1
  return count
  
def Simplify(source_paths):
  dic = {}
  for path in source_paths:
    key = GetKeyPathFile(path)
    if not dic.has_key(key):
      dir = os.path.dirname(path)
      ext = GetFileExtension(path)
      value = {'t': TotalFile(dir, ext), 'n':0}
      dic[key] = value
      # logging.info(key)
    if dic.has_key(key):
      dic[key]['n'] += 1
  array = []
  for key,value in dic.items():
    # logging.info(key)
    if value['t'] == value['n']:
      array.append(key)
    # logging.info(str(value['t']) + ' = ' + str(value['n']))
  for one in array:
    logging.info(one)
  return array
```

Modified in the function "Compile":
```
  args = ['java', '-jar', compiler_jar_path]
  for path in source_paths:
    args += ['--js', path]
```

Replace with:
```
  array = Simplify(source_paths)
  args = ['java', '-jar', compiler_jar_path]
  for path in source_paths:
    if GetKeyPathFile(path) not in array:
      args += ['--js', path]
  for one in array:
    args += ['--js', one]
```

**Comment by lauraharker** [comment]
Created internal Google issue http://b/143616292

**Comment by lauraharker** [comment]
Hi, I think I understand what you're suggesting, but wanted to make sure.

Your problem is that calcdeps.py is causing an error when the number of dependencies is too large. You found that this is because the script passes too many arguments to a subprocess.

Your suggestion is to reduce the number of arguments by globbing individual files together into one argument, in the case that all js files from a given directory are dependencies.

Is that correct?

**Comment by shicks** [comment]
Are you able to use the closure-deps package for this?  calcdeps.py is generally unmaintained.  Alternatively if you want to make a PR, that would also be a possibility.

**Comment by shicks** [comment]
I'm going to close this as unresponsive.  Please reopen and respond if it's still an issue.
