### ISSUE TITLE
Failed to install latest google-closure-deps@20191027.0.1

### ISSUE THREAD

**Issue by teppeis** [google/closure-library#996]
The latest ` google-closure-deps@20191027.0.1` requires `google-closure-compiler@^v20191027.0.1`, but it's missing.

```console
$ npm i google-closure-deps
npm ERR! code ETARGET
npm ERR! notarget No matching version found for google-closure-compiler@^v20191027.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'google-closure-deps'
npm ERR! notarget 
```

https://www.npmjs.com/package/google-closure-compiler?activeTab=versions

**Comment by mprobst** [comment]
Internal issue created: b/144351395

**Comment by teppeis** [comment]
Because v20191111 was released, this issue doesn't occur in the latest.
`npm i google-closure-deps@ 20191027` reproduces it.

**Comment by shicks** [comment]
That release had an abnormality, and apparently I didn't fix it correctly.  Given that 20191111 seems to have fixed it, and it was a one-off issue, I think we should close this as obsolete.
